// Code generated by `v pbgen`. DO NOT EDIT.
//
// The service paths and interfaces below. The handler bodies are the
// caller's: `net.grpc` moves payloads as []u8 and never looks inside them, so
// only the codec needs to know the message types.

module kv

// kv_service_path is the fully qualified service name a gRPC client
// addresses this service by. It is a path, not a network address.
pub const kv_service_path = '/kv.KV'
// kv_method_get is the path of the `Get`
// method. A gRPC request line is this path, so a client and a server
// agree on it before any message is exchanged.
pub const kv_method_get = '/kv.KV/Get'
// kv_method_put is the path of the `Put`
// method. A gRPC request line is this path, so a client and a server
// agree on it before any message is exchanged.
pub const kv_method_put = '/kv.KV/Put'
// kv_method_scan is the path of the `Scan`
// method. A gRPC request line is this path, so a client and a server
// agree on it before any message is exchanged.
pub const kv_method_scan = '/kv.KV/Scan'
// kv_method_put_many is the path of the `PutMany`
// method. A gRPC request line is this path, so a client and a server
// agree on it before any message is exchanged.
pub const kv_method_put_many = '/kv.KV/PutMany'

// KV is the handler interface for the gRPC service `kv.KV`.
//
// A method returns a `grpc.StatusError` as its error to fail the call with a
// typed code; a transport error is something else entirely, and the client
// can only tell the two apart if they stay distinct.
//
// The signatures are transport-free on purpose: no `net.grpc` type appears, so
// this file compiles without the transport module and the adapter that
// registers a service is the caller's to write.
pub interface KV {
	// unary: one request, one response
	// Get is `GetRequest` -> `GetResponse`.
	get(req GetRequest) !GetResponse
	// unary
	// Put is `PutRequest` -> `PutResponse`.
	put(req PutRequest) !PutResponse
	// server streaming: one request, many responses
	// Scan is `GetRequest` -> `GetResponse` (server streaming).
	scan(req GetRequest) ![]GetResponse
	// client streaming: many requests, one response
	// PutMany is `PutRequest` -> `PutManyResponse` (client streaming).
	put_many(reqs []PutRequest) !PutManyResponse
}
