#!/usr/bin/env -S v

// gen.vsh writes the generated sources of the `simd` module:
// vectors_generated.v (types and methods), vectors_generated.c.v (C bindings),
// simd.h (C implementation) and vectors_generated_test.v (tests).
// Regenerate them after editing this file with: v run vlib/simd/gen.vsh
import os
import strings

const generated_note = '// Code generated by vlib/simd/gen.vsh; DO NOT EDIT.\n// Regenerate with: v run vlib/simd/gen.vsh'

enum Kind {
	float
	signed
	unsigned
}

struct Elem {
	name  string // V type name, e.g. `f32`
	bits  int
	kind  Kind
	ctype string // C type name, e.g. `float`
}

const elems = [
	Elem{'f32', 32, .float, 'float'},
	Elem{'f64', 64, .float, 'double'},
	Elem{'i8', 8, .signed, 'int8_t'},
	Elem{'i16', 16, .signed, 'int16_t'},
	Elem{'i32', 32, .signed, 'int32_t'},
	Elem{'i64', 64, .signed, 'int64_t'},
	Elem{'u8', 8, .unsigned, 'uint8_t'},
	Elem{'u16', 16, .unsigned, 'uint16_t'},
	Elem{'u32', 32, .unsigned, 'uint32_t'},
	Elem{'u64', 64, .unsigned, 'uint64_t'},
]

// lanes returns the lane counts of the 64, 128, 256 and 512-bit vectors of e.
// There are no single-lane vectors, so 64-bit lanes start at 128 bits.
fn (e Elem) lanes() []int {
	return match e.bits {
		8 { [8, 16, 32, 64] }
		16 { [4, 8, 16, 32] }
		32 { [2, 4, 8, 16] }
		else { [2, 4, 8] }
	}
}

fn (e Elem) is_int() bool {
	return e.kind != .float
}

// wide is the unsigned V type used for wrapping scalar arithmetic on e.
fn (e Elem) wide() string {
	return if e.bits == 64 { 'u64' } else { 'u32' }
}

fn (e Elem) cwide() string {
	return if e.bits == 64 { 'uint64_t' } else { 'uint32_t' }
}

fn (e Elem) uname() string {
	return 'u${e.bits}'
}

fn (e Elem) mname() string {
	return 'i${e.bits}'
}

fn (e Elem) uctype() string {
	return 'uint${e.bits}_t'
}

fn (e Elem) mctype() string {
	return 'int${e.bits}_t'
}

// partners returns the other element types with the same lane width, which are
// the targets of the cheap lane-count-preserving conversions.
fn (e Elem) partners() []Elem {
	return elems.filter(it.bits == e.bits && it.name != e.name)
}

fn vec_name(e Elem, n int) string {
	return e.name.to_upper()[..1] + e.name[1..] + 'x${n}'
}

fn mask_name(bits int, n int) string {
	return 'Mask${bits}x${n}'
}

fn mask_types(bits int, n int) string {
	names := elems.filter(it.bits == bits && n in it.lanes()).map(vec_name(it, n))
	return names[..names.len - 1].join(', ') + ' and ' + names.last()
}

const lane_params = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

fn main() {
	out_dir := os.dir(@FILE)
	write_formatted(os.join_path(out_dir, 'vectors_generated.v'), gen_vectors())
	write_formatted(os.join_path(out_dir, 'vectors_generated.c.v'), gen_bindings())
	write_formatted(os.join_path(out_dir, 'vectors_generated_test.v'), gen_tests())
	os.write_file(os.join_path(out_dir, 'simd.h'), gen_header()) or { panic(err) }
}

fn write_formatted(path string, content string) {
	os.write_file(path, content) or { panic(err) }
	res := os.exec([@VEXE, 'fmt', '-w', path])
	if res.exit_code != 0 {
		eprintln(res.output)
		exit(1)
	}
}

// Gen collects generated source text.
struct Gen {
mut:
	sb strings.Builder = strings.new_builder(1 << 16)
}

fn (mut g Gen) l(s string) {
	g.sb.writeln(s)
}

fn (mut g Gen) str() string {
	return g.sb.str()
}

// ---------------------------------------------------------------------------
// vectors_generated.v
// ---------------------------------------------------------------------------

fn gen_vectors() string {
	mut g := Gen{}
	g.l(generated_note)
	g.l('module simd\n\nimport math\n')
	for bits in [8, 16, 32, 64] {
		lanes := elems.filter(it.bits == bits)[0].lanes()
		for n in lanes {
			g.mask(bits, n)
		}
	}
	for e in elems {
		for n in e.lanes() {
			g.vector(e, n)
		}
	}
	return g.str()
}

fn (mut g Gen) mask(bits int, n int) {
	t := mask_name(bits, n)
	lt := 'i${bits}'
	low := t.to_lower()
	g.l('// ${t} is a lane mask for ${mask_types(bits, n)}.')
	g.l('// Comparisons return it and the select functions consume it.')
	g.l('pub struct ${t} {\nmut:\n\tvalues [${n}]${lt} // -1 for a set lane, 0 for a clear lane\n}\n')
	g.l('// splat_${low} returns a ${t} with every lane set to value.')
	g.l('pub fn splat_${low}(value bool) ${t} {')
	g.l('\tlane := if value { ${lt}(-1) } else { ${lt}(0) }')
	g.l('\treturn ${t}{\n\t\tvalues: [${n}]${lt}{init: lane}\n\t}\n}\n')
	g.l('// from_array_${low} returns a ${t} with lane i set when values[i] is true.')
	g.l('@[direct_array_access]')
	g.l('pub fn from_array_${low}(values [${n}]bool) ${t} {')
	g.l('\tmut r := ${t}{}\n\tfor i in 0 .. ${n} {\n\t\tif values[i] {\n\t\t\tr.values[i] = -1\n\t\t}\n\t}\n\treturn r\n}\n')
	g.l('// to_array returns the lanes in order, true for each set lane.')
	g.l('@[direct_array_access]')
	g.l('pub fn (m ${t}) to_array() [${n}]bool {')
	g.l('\tmut r := [${n}]bool{}\n\tfor i in 0 .. ${n} {\n\t\tr[i] = m.values[i] != 0\n\t}\n\treturn r\n}\n')
	g.l('// [] reports whether lane i is set. It panics if i is out of range.')
	g.l('@[direct_array_access]')
	g.l('pub fn (m ${t}) [] (i int) bool {')
	g.l('\tif i < 0 || i >= ${n} {\n\t\tlane_panic(i, ${n})\n\t}\n\treturn m.values[i] != 0\n}\n')
	g.l('// []= sets lane i when value is true and clears it otherwise.')
	g.l('// It panics if i is out of range.')
	g.l('@[direct_array_access]')
	g.l('pub fn (mut m ${t}) []= (i int, value bool) {')
	g.l('\tif i < 0 || i >= ${n} {\n\t\tlane_panic(i, ${n})\n\t}')
	g.l('\tm.values[i] = if value { ${lt}(-1) } else { ${lt}(0) }\n}\n')
	g.l('// all reports whether every lane is set.')
	g.l('@[direct_array_access]')
	g.l('pub fn (m ${t}) all() bool {')
	g.l('\tmut acc := ${lt}(-1)\n\tfor i in 0 .. ${n} {\n\t\tacc &= m.values[i]\n\t}\n\treturn acc != 0\n}\n')
	g.l('// any reports whether at least one lane is set.')
	g.l('@[direct_array_access]')
	g.l('pub fn (m ${t}) any() bool {')
	g.l('\tmut acc := ${lt}(0)\n\tfor i in 0 .. ${n} {\n\t\tacc |= m.values[i]\n\t}\n\treturn acc != 0\n}\n')
	g.l('// count returns the number of set lanes.')
	g.l('@[direct_array_access]')
	g.l('pub fn (m ${t}) count() int {')
	g.l('\tmut c := 0\n\tfor i in 0 .. ${n} {\n\t\tc += int(m.values[i] & 1)\n\t}\n\treturn c\n}\n')
	for op in [['and', '&', 'sets the lanes that are set in both m and o'],
		['or', '|', 'sets the lanes that are set in m, o or both'],
		['xor', '^', 'sets the lanes that are set in exactly one of m and o']] {
		g.l('// ${op[0]} returns a mask that ${op[2]}.')
		g.l('@[direct_array_access]')
		g.l('pub fn (m ${t}) ${op[0]}(o ${t}) ${t} {')
		g.l('\tmut r := ${t}{}')
		g.l("\t\$if @BACKEND == 'c' {")
		g.l('\t\tnative_${op[0]}_${lt}(&m.values[0], &o.values[0], &r.values[0], ${n})')
		g.l('\t} \$else {')
		g.l('\t\tfor i in 0 .. ${n} {\n\t\t\tr.values[i] = m.values[i] ${op[1]} o.values[i]\n\t\t}')
		g.l('\t}\n\treturn r\n}\n')
	}
	g.l('// not returns a mask with every lane flipped.')
	g.l('@[direct_array_access]')
	g.l('pub fn (m ${t}) not() ${t} {')
	g.l('\tmut r := ${t}{}')
	g.l("\t\$if @BACKEND == 'c' {")
	g.l('\t\tnative_not_${lt}(&m.values[0], &r.values[0], ${n})')
	g.l('\t} \$else {')
	g.l('\t\tfor i in 0 .. ${n} {\n\t\t\tr.values[i] = ~m.values[i]\n\t\t}')
	g.l('\t}\n\treturn r\n}\n')
}

// native emits the body of an element-wise method: a call of the C helper on
// the C backend and the equivalent scalar loop elsewhere.
fn (mut g Gen) native(rt string, call string, n int, scalar []string) {
	g.l('\tmut r := ${rt}{}')
	g.l("\t\$if @BACKEND == 'c' {")
	g.l('\t\t${call}')
	g.l('\t} \$else {')
	g.l('\t\tfor i in 0 .. ${n} {')
	for s in scalar {
		g.l('\t\t\t${s}')
	}
	g.l('\t\t}')
	g.l('\t}')
	g.l('\treturn r\n}\n')
}

// store_copy copies `count` lanes to dst[offset..]. V3 compiles element writes
// into a `mut []T` parameter as checked `array__set` calls, so the C backend
// copies the bytes directly; the caller has already checked the range.
fn (mut g Gen) store_copy(offset string, count string, s string) {
	g.l("\t\$if @BACKEND == 'c' {")
	g.l('\t\tunsafe { vmemcpy(&${s}(dst.data) + ${offset}, &v.values[0], ${count} * int(sizeof(${s}))) }')
	g.l('\t} \$else {')
	g.l('\t\tfor i in 0 .. ${count} {\n\t\t\tdst[${offset} + i] = v.values[i]\n\t\t}')
	g.l('\t}')
}

// wrap_expr returns the V expression converting the wide unsigned value `x`
// back to the element type.
fn wrap_expr(e Elem, x string) string {
	return if e.name == e.wide() { x } else { '${e.name}(${x})' }
}

fn wide_expr(e Elem, x string) string {
	return if e.name == e.wide() { x } else { '${e.wide()}(${x})' }
}

fn (mut g Gen) vector(e Elem, n int) {
	t := vec_name(e, n)
	low := t.to_lower()
	s := e.name
	m := mask_name(e.bits, n)
	is_float := e.kind == .float
	g.l('// ${t} holds ${n} ${s} lanes (${n * e.bits} bits).')
	g.l('pub struct ${t} {\nmut:\n\tvalues [${n}]${s}\n}\n')
	if n <= 8 {
		params := lane_params[..n]
		g.l('// ${low} creates a ${t} from its lanes in lane order.')
		g.l('pub fn ${low}(${params.map('${it} ${s}').join(', ')}) ${t} {')
		g.l('\treturn ${t}{\n\t\tvalues: [${params.join(', ')}]!\n\t}\n}\n')
	}
	g.l('// splat_${low} returns a ${t} with every lane set to value.')
	g.l('pub fn splat_${low}(value ${s}) ${t} {')
	g.l('\treturn ${t}{\n\t\tvalues: [${n}]${s}{init: value}\n\t}\n}\n')
	g.l('// from_array_${low} returns a ${t} holding values in lane order.')
	g.l('pub fn from_array_${low}(values [${n}]${s}) ${t} {')
	g.l('\treturn ${t}{\n\t\tvalues: values\n\t}\n}\n')
	g.l('// load_${low} loads ${n} values from the start of src.')
	g.l('// It returns an error if src has fewer than ${n} values.')
	g.l('pub fn load_${low}(src []${s}) !${t} {')
	g.l("\tif src.len < ${n} {\n\t\treturn error('simd.load_${low} needs at least ${n} values')\n\t}")
	g.l('\treturn load_${low}_at(src, 0)\n}\n')
	g.l('// load_${low}_part loads up to ${n} values from src and zero-fills the remaining lanes.')
	g.l('// It returns an error if src has more than ${n} values.')
	g.l('@[direct_array_access]')
	g.l('pub fn load_${low}_part(src []${s}) !${t} {')
	g.l("\tif src.len > ${n} {\n\t\treturn error('simd.load_${low}_part accepts at most ${n} values')\n\t}")
	g.l('\tmut r := ${t}{}\n\tfor i in 0 .. src.len {\n\t\tr.values[i] = src[i]\n\t}\n\treturn r\n}\n')
	g.l('// load_${low}_at loads ${n} values starting at src[offset].')
	g.l('// It panics if offset is negative or fewer than ${n} values follow it.')
	g.l('@[direct_array_access]')
	g.l('pub fn load_${low}_at(src []${s}, offset int) ${t} {')
	g.l("\tif offset < 0 || offset > src.len - ${n} {\n\t\trange_panic('simd.load_${low}_at', offset, src.len)\n\t}")
	g.l('\tmut r := ${t}{}\n\tfor i in 0 .. ${n} {\n\t\tr.values[i] = src[offset + i]\n\t}\n\treturn r\n}\n')
	g.l('// select_${low} returns the lanes of a where mask is set and the lanes of b')
	g.l('// where it is clear.')
	g.l('@[direct_array_access]')
	g.l('pub fn select_${low}(mask ${m}, a ${t}, b ${t}) ${t} {')
	g.native(t, 'native_select_${s}(&mask.values[0], &a.values[0], &b.values[0], &r.values[0], ${n})',
		n, ['r.values[i] = if mask.values[i] != 0 { a.values[i] } else { b.values[i] }'])

	g.l('// to_array returns the lanes in order.')
	g.l('pub fn (v ${t}) to_array() [${n}]${s} {\n\treturn v.values\n}\n')
	g.l('// [] returns lane i. It panics if i is out of range.')
	g.l('@[direct_array_access]')
	g.l('pub fn (v ${t}) [] (i int) ${s} {')
	g.l('\tif i < 0 || i >= ${n} {\n\t\tlane_panic(i, ${n})\n\t}\n\treturn v.values[i]\n}\n')
	g.l('// []= sets lane i to value. It panics if i is out of range.')
	g.l('@[direct_array_access]')
	g.l('pub fn (mut v ${t}) []= (i int, value ${s}) {')
	g.l('\tif i < 0 || i >= ${n} {\n\t\tlane_panic(i, ${n})\n\t}\n\tv.values[i] = value\n}\n')
	g.l('// store writes all ${n} lanes to the start of dst.')
	g.l('// It returns an error if dst has fewer than ${n} elements.')
	g.l('pub fn (v ${t}) store(mut dst []${s}) ! {')
	g.l("\tif dst.len < ${n} {\n\t\treturn error('simd.${t}.store needs at least ${n} values')\n\t}")
	g.l('\tv.store_at(mut dst, 0)\n}\n')
	g.l('// store_part writes one lane for each element of dst, up to ${n} elements.')
	g.l('// It returns an error if dst has more than ${n} elements.')
	g.l('@[direct_array_access]')
	g.l('pub fn (v ${t}) store_part(mut dst []${s}) ! {')
	g.l("\tif dst.len > ${n} {\n\t\treturn error('simd.${t}.store_part accepts at most ${n} values')\n\t}")
	g.store_copy('0', 'dst.len', s)
	g.l('}\n')
	g.l('// store_at writes all ${n} lanes to dst, starting at dst[offset].')
	g.l('// It panics if offset is negative or fewer than ${n} elements follow it.')
	g.l('@[direct_array_access]')
	g.l('pub fn (v ${t}) store_at(mut dst []${s}, offset int) {')
	g.l("\tif offset < 0 || offset > dst.len - ${n} {\n\t\trange_panic('simd.${t}.store_at', offset, dst.len)\n\t}")
	g.store_copy('offset', '${n}', s)
	g.l('}\n')

	// Arithmetic.
	arith := [['+', 'add', 'adds'], ['-', 'sub', 'subtracts'], ['*', 'mul', 'multiplies']]
	for op in arith {
		wraps := if e.is_int() { ', wrapping on overflow' } else { '' }
		g.l('// ${op[0]} ${op[2]} corresponding lanes${wraps}.')
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) ${op[0]} (b ${t}) ${t} {')
		scalar := if is_float {
			'a.values[i] ${op[0]} b.values[i]'
		} else {
			wrap_expr(e, '${wide_expr(e, 'a.values[i]')} ${op[0]} ${wide_expr(e, 'b.values[i]')}')
		}
		g.native(t, 'native_${op[1]}_${s}(&a.values[0], &b.values[0], &r.values[0], ${n})',
			n, ['r.values[i] = ${scalar}'])
	}
	if is_float {
		g.l('// / divides corresponding lanes.')
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) / (b ${t}) ${t} {')
		g.native(t, 'native_div_${s}(&a.values[0], &b.values[0], &r.values[0], ${n})', n,
			['r.values[i] = a.values[i] / b.values[i]'])
	} else {
		g.l('// / divides corresponding lanes, truncating toward zero.')
		if e.kind == .signed {
			g.l('// It panics if a lane of b is zero. min_${s} / -1 wraps to min_${s}.')
		} else {
			g.l('// It panics if a lane of b is zero.')
		}
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) / (b ${t}) ${t} {')
		g.l('\tmut r := ${t}{}\n\tfor i in 0 .. ${n} {')
		if e.kind == .signed {
			g.l('\t\tr.values[i] = div_${s}(a.values[i], b.values[i])')
		} else {
			g.l('\t\tr.values[i] = a.values[i] / b.values[i]')
		}
		g.l('\t}\n\treturn r\n}\n')
	}
	for op in [['+', 'add'], ['-', 'sub'], ['*', 'mul'], ['/', 'div']] {
		g.l('// ${op[1]} returns a ${op[0]} b.')
		g.l('pub fn (a ${t}) ${op[1]}(b ${t}) ${t} {\n\treturn a ${op[0]} b\n}\n')
	}
	if e.kind != .unsigned {
		g.l('// neg negates each lane${if is_float {
			''
		} else {
			', wrapping min_' + s + ' to itself'
		}}.')
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) neg() ${t} {')
		neg := if is_float {
			'-a.values[i]'
		} else {
			wrap_expr(e, '${e.wide()}(0) - ${e.wide()}(a.values[i])')
		}
		g.native(t, 'native_neg_${s}(&a.values[0], &r.values[0], ${n})', n, ['r.values[i] = ${neg}'])
		if is_float {
			g.l('// abs returns the absolute value of each lane by clearing its sign bit.')
		} else {
			g.l('// abs returns the absolute value of each lane. min_${s} wraps to itself.')
		}
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) abs() ${t} {')
		abs := if is_float {
			['r.values[i] = abs_${s}(a.values[i])']
		} else {
			['x := a.values[i]',
				'r.values[i] = if x < 0 { ${wrap_expr(e, '${e.wide()}(0) - ${e.wide()}(x)')} } else { x }']
		}
		g.native(t, 'native_abs_${s}(&a.values[0], &r.values[0], ${n})', n, abs)
	}
	for op in [['minimum', 'min', '<', 'smaller'], ['maximum', 'max', '>', 'larger']] {
		g.l('// ${op[0]} returns the ${op[3]} of each pair of lanes.')
		if is_float {
			g.l('// When one lane is NaN, the other lane is returned. Equal lanes, such as')
			g.l('// -0.0 and 0.0, return the lane of a.')
		}
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) ${op[0]}(b ${t}) ${t} {')
		body := if is_float {
			['x := a.values[i]', 'y := b.values[i]',
				'r.values[i] = if y ${op[2]} x || x != x { y } else { x }']
		} else {
			['x := a.values[i]', 'y := b.values[i]', 'r.values[i] = if y ${op[2]} x { y } else { x }']
		}
		g.native(t, 'native_${op[1]}_${s}(&a.values[0], &b.values[0], &r.values[0], ${n})',
			n, body)
	}
	if is_float {
		g.l('// sqrt returns the square root of each lane.')
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) sqrt() ${t} {')
		sq := if s == 'f32' { 'f32(math.sqrt(a.values[i]))' } else { 'math.sqrt(a.values[i])' }
		g.native(t, 'native_sqrt_${s}(&a.values[0], &r.values[0], ${n})', n, ['r.values[i] = ${sq}'])
		g.l('// mul_add returns v * multiplier + addend for each lane.')
		g.l('// It does not promise fused rounding.')
		g.l('pub fn (v ${t}) mul_add(multiplier ${t}, addend ${t}) ${t} {')
		g.l('\treturn v * multiplier + addend\n}\n')
	}

	// Comparisons.
	for op in [['eq', '==', 'equal to'], ['ne', '!=', 'not equal to'], ['lt', '<', 'less than'],
		['le', '<=', 'less than or equal to']] {
		g.l('// ${op[0]} returns a mask of the lanes where a is ${op[2]} b.')
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) ${op[0]}(b ${t}) ${m} {')
		g.native(m, 'native_${op[0]}_${s}(&a.values[0], &b.values[0], &r.values[0], ${n})',
			n, ['if a.values[i] ${op[1]} b.values[i] {', '\tr.values[i] = -1', '}'])
	}
	g.l('// gt returns a mask of the lanes where a is greater than b.')
	g.l('pub fn (a ${t}) gt(b ${t}) ${m} {\n\treturn b.lt(a)\n}\n')
	g.l('// ge returns a mask of the lanes where a is greater than or equal to b.')
	g.l('pub fn (a ${t}) ge(b ${t}) ${m} {\n\treturn b.le(a)\n}\n')

	// Bitwise operations and shifts.
	if e.is_int() {
		for op in [['and', '&', 'bitwise AND'], ['or', '|', 'bitwise OR'], ['xor', '^', 'bitwise XOR']] {
			g.l('// ${op[0]} returns the ${op[2]} of corresponding lanes.')
			g.l('@[direct_array_access]')
			g.l('pub fn (a ${t}) ${op[0]}(b ${t}) ${t} {')
			g.native(t, 'native_${op[0]}_${s}(&a.values[0], &b.values[0], &r.values[0], ${n})',
				n, ['r.values[i] = a.values[i] ${op[1]} b.values[i]'])
		}
		g.l('// not returns the bitwise complement of each lane.')
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) not() ${t} {')
		g.native(t, 'native_not_${s}(&a.values[0], &r.values[0], ${n})', n, ['r.values[i] = ~a.values[i]'])
		g.l('// shl shifts each lane left by count bits.')
		g.l('// A count of ${e.bits} or more shifts every bit out and returns zero lanes.')
		g.l('@[direct_array_access]')
		g.l('pub fn (a ${t}) shl(count u32) ${t} {')
		g.l('\tif count >= ${e.bits} {\n\t\treturn ${t}{}\n\t}')
		g.native(t, 'native_shl_${s}(&a.values[0], count, &r.values[0], ${n})', n,
			['r.values[i] = ${wrap_expr(e, '${e.wide()}(a.values[i]) << count')}'])
		g.l('// shr shifts each lane right by count bits.')
		if e.kind == .signed {
			g.l('// The shift is arithmetic: it copies the sign bit, and a count of ${e.bits} or')
			g.l('// more fills each lane with its sign bit.')
			g.l('@[direct_array_access]')
			g.l('pub fn (a ${t}) shr(count u32) ${t} {')
			g.l('\tc := if count >= ${e.bits} { u32(${e.bits - 1}) } else { count }')
			g.native(t, 'native_shr_${s}(&a.values[0], c, &r.values[0], ${n})', n,
				['r.values[i] = a.values[i] >> c'])
		} else {
			g.l('// A count of ${e.bits} or more shifts every bit out and returns zero lanes.')
			g.l('@[direct_array_access]')
			g.l('pub fn (a ${t}) shr(count u32) ${t} {')
			g.l('\tif count >= ${e.bits} {\n\t\treturn ${t}{}\n\t}')
			g.native(t, 'native_shr_${s}(&a.values[0], count, &r.values[0], ${n})', n,
				['r.values[i] = a.values[i] >> count'])
		}
	}

	// Reductions.
	if is_float {
		g.l('// sum adds the lanes in lane order.')
		g.l('@[direct_array_access]')
		g.l('pub fn (v ${t}) sum() ${s} {')
		g.l('\tmut acc := v.values[0]\n\tfor i in 1 .. ${n} {\n\t\tacc += v.values[i]\n\t}\n\treturn acc\n}\n')
	} else {
		g.l('// sum adds the lanes, wrapping on overflow.')
		g.l('@[direct_array_access]')
		g.l('pub fn (v ${t}) sum() ${s} {')
		g.l('\tmut acc := ${e.wide()}(0)\n\tfor i in 0 .. ${n} {\n\t\tacc += ${wide_expr(e, 'v.values[i]')}\n\t}\n\treturn ${wrap_expr(e, 'acc')}\n}\n')
	}
	for op in [['min', '<', 'smallest'], ['max', '>', 'largest']] {
		g.l('// ${op[0]}_element returns the index of the first lane holding the ${op[2]} value.')
		if is_float {
			g.l('// NaN lanes are ignored. If every lane is NaN, it returns 0.')
		}
		g.l('@[direct_array_access]')
		g.l('pub fn (v ${t}) ${op[0]}_element() int {')
		g.l('\tmut best := 0\n\tfor i in 1 .. ${n} {')
		if is_float {
			g.l('\t\tx := v.values[i]\n\t\ty := v.values[best]')
			g.l('\t\tif x ${op[1]} y || (y != y && x == x) {\n\t\t\tbest = i\n\t\t}')
		} else {
			g.l('\t\tif v.values[i] ${op[1]} v.values[best] {\n\t\t\tbest = i\n\t\t}')
		}
		g.l('\t}\n\treturn best\n}\n')
		g.l('// ${op[0]} returns the ${op[2]} lane value, the lane at index ${op[0]}_element().')
		if is_float {
			g.l('// NaN lanes are ignored unless every lane is NaN.')
		}
		g.l('@[direct_array_access]')
		g.l('pub fn (v ${t}) ${op[0]}() ${s} {\n\treturn v.values[v.${op[0]}_element()]\n}\n')
	}
	if is_float {
		g.l('// dot multiplies corresponding lanes and adds the products in lane order.')
	} else {
		g.l('// dot multiplies corresponding lanes and adds the products, wrapping on overflow.')
	}
	g.l('pub fn (a ${t}) dot(b ${t}) ${s} {\n\treturn (a * b).sum()\n}\n')

	// Conversions between element types of the same width.
	for p in e.partners() {
		pt := vec_name(p, n)
		g.l('// to_${pt.to_lower()} converts each lane to ${p.name}.')
		expr := if is_float {
			g.l('// It truncates toward zero, maps NaN to 0 and saturates values outside the')
			g.l('// range of ${p.name}.')
			'${s}_to_${p.name}(v.values[i])'
		} else if p.kind == .float {
			g.l('// It rounds to the nearest ${p.name} value.')
			'${p.name}(v.values[i])'
		} else {
			g.l('// It keeps the bits of each lane, so values wrap modulo 2^${e.bits}.')
			'${p.name}(v.values[i])'
		}
		g.l('@[direct_array_access]')
		g.l('pub fn (v ${t}) to_${pt.to_lower()}() ${pt} {')
		g.l('\tmut r := ${pt}{}\n\tfor i in 0 .. ${n} {\n\t\tr.values[i] = ${expr}\n\t}\n\treturn r\n}\n')
	}
}

// ---------------------------------------------------------------------------
// C operations, shared by simd.h and vectors_generated.c.v
// ---------------------------------------------------------------------------

enum Shape {
	bin   // (a, b) -> out
	un    // (a) -> out
	cmp   // (a, b) -> mask
	pick  // (a, b) -> out, picking b where the condition holds
	sel   // (mask, a, b) -> out
	shift // (a, count) -> out
	sqrt  // hand-written
}

struct COp {
	name   string
	shape  Shape
	vt     string // vector type the inputs are loaded as: `E` element, `U` unsigned, `M` mask
	vec    string // vector expression; VT, UT, MT and ET are replaced by type names
	scalar string // scalar expression for out[i]
}

fn c_ops(e Elem) []COp {
	mut ops := []COp{}
	if e.kind == .float {
		absmask := if e.bits == 32 { '0x7fffffffu' } else { '0x7fffffffffffffffull' }
		fabs := if e.bits == 32 { 'fabsf' } else { 'fabs' }
		ops << [
			COp{'add', .bin, 'E', 'vx + vy', 'a[i] + b[i]'},
			COp{'sub', .bin, 'E', 'vx - vy', 'a[i] - b[i]'},
			COp{'mul', .bin, 'E', 'vx * vy', 'a[i] * b[i]'},
			COp{'div', .bin, 'E', 'vx / vy', 'a[i] / b[i]'},
			COp{'neg', .un, 'E', '-vx', '-a[i]'},
			COp{'abs', .un, 'U', 'vx & ${absmask}', '${fabs}(a[i])'},
			COp{'min', .pick, 'E', '(vy < vx) | (vx != vx)', '(b[i] < a[i] || a[i] != a[i]) ? b[i] : a[i]'},
			COp{'max', .pick, 'E', '(vy > vx) | (vx != vx)', '(b[i] > a[i] || a[i] != a[i]) ? b[i] : a[i]'},
			COp{'sqrt', .sqrt, '', '', ''},
		]
	} else {
		w := e.cwide()
		ct := e.ctype
		ops << [
			COp{'add', .bin, 'U', 'vx + vy', '(${ct})((${w})a[i] + (${w})b[i])'},
			COp{'sub', .bin, 'U', 'vx - vy', '(${ct})((${w})a[i] - (${w})b[i])'},
			COp{'mul', .bin, 'U', 'vx * vy', '(${ct})((${w})a[i] * (${w})b[i])'},
			COp{'min', .pick, 'E', 'vy < vx', 'b[i] < a[i] ? b[i] : a[i]'},
			COp{'max', .pick, 'E', 'vy > vx', 'b[i] > a[i] ? b[i] : a[i]'},
			COp{'and', .bin, 'U', 'vx & vy', '(${ct})(a[i] & b[i])'},
			COp{'or', .bin, 'U', 'vx | vy', '(${ct})(a[i] | b[i])'},
			COp{'xor', .bin, 'U', 'vx ^ vy', '(${ct})(a[i] ^ b[i])'},
			COp{'not', .un, 'U', '~vx', '(${ct})~a[i]'},
			COp{'shl', .shift, 'U', 'vx << (UET)count', '(${ct})((${w})a[i] << count)'},
			COp{'shr', .shift, 'E', 'vx >> (ET)count', '(${ct})(a[i] >> count)'},
		]
		if e.kind == .signed {
			b1 := e.bits - 1
			ops << [
				COp{'neg', .un, 'U', '-vx', '(${ct})((${w})0 - (${w})a[i])'},
				COp{'abs', .un, 'E', '(VT)(((UT)vx ^ (UT)(vx >> ${b1})) - (UT)(vx >> ${b1}))', 'a[i] < 0 ? (${ct})((${w})0 - (${w})a[i]) : a[i]'},
			]
		}
	}
	for op in [['eq', '=='], ['ne', '!='], ['lt', '<'], ['le', '<=']] {
		ops << COp{op[0], .cmp, 'E', 'vx ${op[1]} vy', '(${e.mctype()})-(a[i] ${op[1]} b[i])'}
	}
	ops << COp{'select', .sel, 'U', '', 'm[i] ? a[i] : b[i]'}
	return ops
}

fn c_params(e Elem, op COp) string {
	t := e.ctype
	return match op.shape {
		.bin, .pick { 'const ${t} *a, const ${t} *b, ${t} *out, int n' }
		.un, .sqrt { 'const ${t} *a, ${t} *out, int n' }
		.cmp { 'const ${t} *a, const ${t} *b, ${e.mctype()} *out, int n' }
		.sel { 'const ${e.mctype()} *m, const ${t} *a, const ${t} *b, ${t} *out, int n' }
		.shift { 'const ${t} *a, unsigned count, ${t} *out, int n' }
	}
}

fn v_params(e Elem, op COp) (string, string) {
	s := e.name
	ms := e.mname()
	return match op.shape {
		.bin, .pick {
			'const_a &${s}, const_b &${s}, out &${s}, n int', 'a, b, out, n'
		}
		.un, .sqrt {
			'const_a &${s}, out &${s}, n int', 'a, out, n'
		}
		.cmp {
			'const_a &${s}, const_b &${s}, out &${ms}, n int', 'a, b, out, n'
		}
		.sel {
			'const_m &${ms}, const_a &${s}, const_b &${s}, out &${s}, n int', 'm, a, b, out, n'
		}
		.shift {
			'const_a &${s}, count u32, out &${s}, n int', 'a, count, out, n'
		}
	}
}

// ---------------------------------------------------------------------------
// vectors_generated.c.v
// ---------------------------------------------------------------------------

fn gen_bindings() string {
	mut g := Gen{}
	g.l(generated_note)
	g.l('module simd\n')
	for e in elems {
		for op in c_ops(e) {
			cparams, args := v_params(e, op)
			wparams := cparams.replace('const_', '')
			g.l('fn C.v_simd_${op.name}_${e.name}(${cparams})\n')
			g.l('fn native_${op.name}_${e.name}(${wparams}) {')
			g.l('\tC.v_simd_${op.name}_${e.name}(${args})\n}\n')
		}
	}
	return g.str()
}

// ---------------------------------------------------------------------------
// simd.h
// ---------------------------------------------------------------------------

const header_preamble = '#ifndef VLIB_SIMD_SIMD_H
#define VLIB_SIMD_SIMD_H

/*
 * Element-wise helpers for vlib/simd. Each function processes `n` lanes stored
 * in plain arrays, which V passes as pointers to the first lane of a vector.
 *
 * With gcc and clang, the lanes are loaded into vectors declared with
 * __attribute__((vector_size(N))), so the C compiler emits SIMD instructions
 * for the target (SSE/AVX, NEON, ...) and splits wide vectors as needed.
 * tcc, msvc and builds with -DV_SIMD_FORCE_SCALAR use the scalar loops.
 * Both paths compute the same results: integer arithmetic goes through
 * unsigned types so it wraps, and callers keep shift counts in range.
 */

#include <math.h>
#include <stdint.h>
#include <string.h>

#if !defined(V_SIMD_FORCE_SCALAR) && !defined(__TINYC__) && (defined(__GNUC__) || defined(__clang__))
#define V_SIMD_VECTOR_EXT 1
#endif

#if defined(V_SIMD_VECTOR_EXT) && defined(__SSE__)
#include <xmmintrin.h>
#define V_SIMD_HAS_SSE 1
#if defined(__SSE2__)
#include <emmintrin.h>
#define V_SIMD_HAS_SSE2 1
#endif
#elif defined(V_SIMD_VECTOR_EXT) && defined(__aarch64__)
#include <arm_neon.h>
#define V_SIMD_HAS_NEON 1
#endif

#if defined(V_SIMD_VECTOR_EXT)
#define V_SIMD_BIN(VT, EXPR) { VT vx, vy, vr; memcpy(&vx, a, sizeof vx); memcpy(&vy, b, sizeof vy); vr = (EXPR); memcpy(out, &vr, sizeof vr); return; }
#define V_SIMD_UN(VT, EXPR) { VT vx, vr; memcpy(&vx, a, sizeof vx); vr = (EXPR); memcpy(out, &vr, sizeof vr); return; }
#define V_SIMD_CMP(VT, MT, EXPR) { VT vx, vy; MT vr; memcpy(&vx, a, sizeof vx); memcpy(&vy, b, sizeof vy); vr = (MT)(EXPR); memcpy(out, &vr, sizeof vr); return; }
#define V_SIMD_PICK(VT, UT, EXPR) { VT vx, vy; UT vm, vr; memcpy(&vx, a, sizeof vx); memcpy(&vy, b, sizeof vy); vm = (UT)(EXPR); vr = (vm & (UT)vy) | (~vm & (UT)vx); memcpy(out, &vr, sizeof vr); return; }
#define V_SIMD_SEL(UT, MT) { MT vm; UT vx, vy, vr; memcpy(&vm, m, sizeof vm); memcpy(&vx, a, sizeof vx); memcpy(&vy, b, sizeof vy); vr = ((UT)vm & vx) | (~(UT)vm & vy); memcpy(out, &vr, sizeof vr); return; }
'

const header_sqrt = '
static inline void v_simd_sqrt_f32(const float *a, float *out, int n) {
	int i = 0;
#if defined(V_SIMD_HAS_SSE)
	for (; i + 4 <= n; i += 4) _mm_storeu_ps(out + i, _mm_sqrt_ps(_mm_loadu_ps(a + i)));
#elif defined(V_SIMD_HAS_NEON)
	for (; i + 4 <= n; i += 4) vst1q_f32(out + i, vsqrtq_f32(vld1q_f32(a + i)));
#endif
	for (; i < n; i++) out[i] = sqrtf(a[i]);
}

static inline void v_simd_sqrt_f64(const double *a, double *out, int n) {
	int i = 0;
#if defined(V_SIMD_HAS_SSE2)
	for (; i + 2 <= n; i += 2) _mm_storeu_pd(out + i, _mm_sqrt_pd(_mm_loadu_pd(a + i)));
#elif defined(V_SIMD_HAS_NEON)
	for (; i + 2 <= n; i += 2) vst1q_f64(out + i, vsqrtq_f64(vld1q_f64(a + i)));
#endif
	for (; i < n; i++) out[i] = sqrt(a[i]);
}
'

fn ctypes_name(name string, n int) string {
	return 'v_simd_${name}x${n}'
}

fn gen_header() string {
	mut g := Gen{}
	g.l(generated_note.replace('// ', '/* ').replace('\n', ' */\n') + ' */')
	g.l(header_preamble)
	for e in elems {
		for n in e.lanes() {
			g.l('typedef ${e.ctype} ${ctypes_name(e.name, n)} __attribute__((vector_size(${n * e.bits / 8})));')
		}
	}
	g.l('#endif')
	g.l(header_sqrt)
	for e in elems {
		for op in c_ops(e) {
			if op.shape == .sqrt {
				continue
			}
			g.l('static inline void v_simd_${op.name}_${e.name}(${c_params(e, op)}) {')
			g.l('#if defined(V_SIMD_VECTOR_EXT)')
			g.l('\tswitch (n) {')
			for n in e.lanes() {
				et := ctypes_name(e.name, n)
				ut := ctypes_name(e.uname(), n)
				mt := ctypes_name(e.mname(), n)
				vt := match op.vt {
					'U' { ut }
					'M' { mt }
					else { et }
				}
				expr := op.vec.replace('UET', e.uctype()).replace('ET', e.ctype).replace('VT',
					vt).replace('UT', ut).replace('MT', mt)
				body := match op.shape {
					.bin { 'V_SIMD_BIN(${vt}, ${expr})' }
					.un, .shift { 'V_SIMD_UN(${vt}, ${expr})' }
					.cmp { 'V_SIMD_CMP(${vt}, ${mt}, ${expr})' }
					.pick { 'V_SIMD_PICK(${vt}, ${ut}, ${expr})' }
					.sel { 'V_SIMD_SEL(${ut}, ${mt})' }
					.sqrt { '' }
				}
				g.l('\tcase ${n}: ${body}')
			}
			g.l('\tdefault: break;\n\t}\n#endif')
			g.l('\tfor (int i = 0; i < n; i++) out[i] = ${op.scalar};\n}\n')
		}
	}
	g.l('#endif')
	return g.str()
}

// ---------------------------------------------------------------------------
// vectors_generated_test.v
// ---------------------------------------------------------------------------

const test_preamble = 'import math
import simd

fn bools(n int, seed int) []bool {
	mut r := []bool{len: n}
	mut s := u64(seed) * 0x9e3779b97f4a7c15 + 1
	for i in 0 .. n {
		s = s * 6364136223846793005 + 1442695040888963407
		r[i] = match seed {
			0 { false }
			1 { true }
			else { (s >> 40) & 1 == 1 }
		}
	}
	return r
}

fn check_mask(label string, got []bool, want []bool) {
	assert got == want, label
}
'

fn edge_list(e Elem, which int) string {
	s := e.name
	if e.kind == .float {
		nan := '${s}(math.nan())'
		inf := '${s}(math.inf(1))'
		ninf := '${s}(math.inf(-1))'
		return match which {
			0 {
				'[${s}(0.0), -0.0, 1.5, -2.25, ${inf}, ${ninf}, ${nan}, 3.0, ${nan}, 1.0, -0.0, 2.0]'
			}
			1 {
				'[${s}(-0.0), 0.0, ${nan}, 2.0, ${inf}, 1.0, ${nan}, ${ninf}, 5.0, 1.0, -0.0, -2.0]'
			}
			else {
				'[${s}(3e9), -3e9, 2147483520.0, -2147483648.0, 4294967040.0, 4294967296.0, 1e20, -1e20, ${nan}, ${inf}, ${ninf}, -0.5, 0.75, -1.0, 9.2e18, -9.3e18, 1.9e19, 2.5]'
			}
		}
	}
	if e.kind == .signed {
		mn := 'min_${s}'
		mx := 'max_${s}'
		return match which {
			0 { '[${mn}, ${mn}, ${mx}, ${mx}, 0, -1, 1, ${mn} + 1, ${mx} - 1, 2, -2, 0]' }
			else { '[${s}(-1), 1, 1, -1, ${mn}, ${mx}, -1, 2, -2, ${mn}, 0, 0]' }
		}
	}
	mx := 'max_${s}'
	return match which {
		0 { '[${s}(0), 1, ${mx}, ${mx}, ${mx} - 1, 2, ${mx} / 2, 0, 1]' }
		else { '[${s}(1), ${mx}, ${mx}, 2, 0, ${mx}, 3, 0, 0]' }
	}
}

// test_helpers emits the scalar reference implementations for element type e.
fn (mut g Gen) test_helpers(e Elem) {
	s := e.name
	isf := e.kind == .float
	g.l('fn pool_${s}(seed u64, edges []${s}) []${s} {\n\tmut r := edges.clone()\n\tmut st := seed')
	g.l('\tfor r.len < 72 {\n\t\tst = st * 6364136223846793005 + 1442695040888963407')
	if isf {
		g.l('\t\tr << ${s}(i64(st >> 57) - 64) / 4')
	} else {
		g.l('\t\tr << ${s}(st >> ${64 - e.bits})')
	}
	g.l('\t}\n\treturn r\n}\n')
	if isf {
		g.l('fn same_${s}(x ${s}, y ${s}) bool {')
		g.l('\treturn (x != x && y != y) || math.${s}_bits(x) == math.${s}_bits(y)\n}\n')
		g.l('fn check_${s}(label string, got []${s}, want []${s}) {\n\tassert got.len == want.len, label')
		g.l("\tfor i in 0 .. got.len {\n\t\tassert same_${s}(got[i], want[i]), '\${label}: lane \${i}: got \${got[i]}, want \${want[i]}'\n\t}\n}\n")
	} else {
		g.l('fn check_${s}(label string, got []${s}, want []${s}) {\n\tassert got == want, label\n}\n')
	}
	// Binary references, computed independently of the implementation.
	g.l('fn ref2_${s}(op string, a []${s}, b []${s}) []${s} {\n\tmut r := []${s}{len: a.len}')
	g.l('\tfor i, x in a {\n\t\ty := b[i]\n\t\tr[i] = match op {')
	if isf {
		g.l("\t\t\t'add' { x + y }\n\t\t\t'sub' { x - y }\n\t\t\t'mul' { x * y }\n\t\t\t'div' { x / y }")
		g.l("\t\t\t'min' { if math.is_nan(f64(x)) { y } else if math.is_nan(f64(y)) { x } else if y < x { y } else { x } }")
		g.l('\t\t\telse { if math.is_nan(f64(x)) { y } else if math.is_nan(f64(y)) { x } else if y > x { y } else { x } }')
	} else {
		div := match e.kind {
			.unsigned { 'x / y' }
			else {
				if e.bits == 64 {
					'if x == min_i64 && y == -1 { x } else { x / y }'
				} else {
					'${s}(i64(x) / i64(y))'
				}
			}
		}
		g.l("\t\t\t'add' { ${s}(u64(x) + u64(y)) }\n\t\t\t'sub' { ${s}(u64(x) - u64(y)) }\n\t\t\t'mul' { ${s}(u64(x) * u64(y)) }")
		g.l("\t\t\t'div' { ${div} }\n\t\t\t'min' { if y < x { y } else { x } }\n\t\t\t'max' { if y > x { y } else { x } }")
		g.l("\t\t\t'and' { ${s}(u64(x) & u64(y)) }\n\t\t\t'or' { ${s}(u64(x) | u64(y)) }\n\t\t\telse { ${s}(u64(x) ^ u64(y)) }")
	}
	g.l('\t\t}\n\t}\n\treturn r\n}\n')
	g.l('fn ref1_${s}(op string, a []${s}) []${s} {\n\tmut r := []${s}{len: a.len}\n\tfor i, x in a {\n\t\tr[i] = match op {')
	if isf {
		g.l("\t\t\t'neg' { -x }\n\t\t\t'abs' { if math.signbit(f64(x)) { -x } else { x } }\n\t\t\telse { ${s}(math.sqrt(f64(x))) }")
	} else {
		g.l("\t\t\t'neg' { ${s}(u64(0) - u64(x)) }\n\t\t\t'abs' { if x < 0 { ${s}(u64(0) - u64(x)) } else { x } }\n\t\t\telse { ${s}(~u64(x)) }")
	}
	g.l('\t\t}\n\t}\n\treturn r\n}\n')
	g.l('fn refc_${s}(op string, a []${s}, b []${s}) []bool {\n\tmut r := []bool{len: a.len}\n\tfor i, x in a {\n\t\ty := b[i]\n\t\tr[i] = match op {')
	g.l("\t\t\t'eq' { x == y }\n\t\t\t'ne' { x != y }\n\t\t\t'lt' { x < y }\n\t\t\t'le' { x <= y }\n\t\t\t'gt' { x > y }\n\t\t\telse { x >= y }")
	g.l('\t\t}\n\t}\n\treturn r\n}\n')
	g.l('fn refsel_${s}(m []bool, a []${s}, b []${s}) []${s} {\n\tmut r := []${s}{len: a.len}')
	g.l('\tfor i in 0 .. a.len {\n\t\tr[i] = if m[i] { a[i] } else { b[i] }\n\t}\n\treturn r\n}\n')
	if isf {
		g.l('fn refsum_${s}(a []${s}) ${s} {\n\tmut acc := a[0]\n\tfor x in a[1..] {\n\t\tacc += x\n\t}\n\treturn acc\n}\n')
		g.l('fn refdot_${s}(a []${s}, b []${s}) ${s} {\n\tmut acc := a[0] * b[0]\n\tfor i in 1 .. a.len {\n\t\tacc += a[i] * b[i]\n\t}\n\treturn acc\n}\n')
		g.l('fn refidx_${s}(a []${s}, smallest bool) int {\n\tmut best := -1\n\tfor i, x in a {')
		g.l('\t\tif math.is_nan(f64(x)) {\n\t\t\tcontinue\n\t\t}')
		g.l('\t\tif best < 0 || (smallest && x < a[best]) || (!smallest && x > a[best]) {\n\t\t\tbest = i\n\t\t}')
		g.l('\t}\n\treturn if best < 0 { 0 } else { best }\n}\n')
		for p in e.partners() {
			lo, hi := match p.name {
				'i32' { '-2147483648.0', '2147483648.0' }
				'u32' { '0.0', '4294967296.0' }
				'i64' { '-9223372036854775808.0', '9223372036854775808.0' }
				else { '0.0', '18446744073709551616.0' }
			}
			low := if p.kind == .signed { 'min_${p.name}' } else { '0' }
			g.l('fn refconv_${s}_${p.name}(a []${s}) []${p.name} {\n\treturn a.map(fn (x ${s}) ${p.name} {')
			g.l('\t\tif math.is_nan(f64(x)) {\n\t\t\treturn 0\n\t\t}\n\t\tt := math.trunc(f64(x))')
			g.l('\t\treturn if t >= ${hi} { max_${p.name} } else if t < ${lo} { ${low} } else { ${p.name}(t) }\n\t})\n}\n')
		}
	} else {
		g.l('fn refsum_${s}(a []${s}) ${s} {\n\tmut acc := u64(0)\n\tfor x in a {\n\t\tacc += u64(x)\n\t}\n\treturn ${s}(acc)\n}\n')
		g.l('fn refdot_${s}(a []${s}, b []${s}) ${s} {\n\tmut acc := u64(0)\n\tfor i, x in a {\n\t\tacc += u64(x) * u64(b[i])\n\t}\n\treturn ${s}(acc)\n}\n')
		g.l('fn refidx_${s}(a []${s}, smallest bool) int {\n\tmut best := 0\n\tfor i, x in a {')
		g.l('\t\tif (smallest && x < a[best]) || (!smallest && x > a[best]) {\n\t\t\tbest = i\n\t\t}\n\t}\n\treturn best\n}\n')
		shr := if e.kind == .signed {
			'${s}(i64(x) >> (if c >= ${e.bits} { u32(${e.bits - 1}) } else { c }))'
		} else {
			'if c >= ${e.bits} { ${s}(0) } else { ${s}(u64(x) >> c) }'
		}
		g.l('fn refsh_${s}(left bool, a []${s}, c u32) []${s} {\n\tmut r := []${s}{len: a.len}\n\tfor i, x in a {')
		g.l('\t\tr[i] = if left { if c >= ${e.bits} { ${s}(0) } else { ${s}(u64(x) << c) } } else { ${shr} }')
		g.l('\t}\n\treturn r\n}\n')
	}
}

fn (mut g Gen) vector_test(e Elem, n int) {
	s := e.name
	t := vec_name(e, n)
	low := t.to_lower()
	isf := e.kind == .float
	arr := '.to_array()[..]'
	g.l('fn test_${low}() {')
	g.l('\ta := pool_${s}(${n * 2 + 1}, ${edge_list(e, 0)})')
	g.l('\tb := pool_${s}(${n * 2 + 2}, ${edge_list(e, 1)})')
	if isf {
		g.l('\tcv := pool_${s}(${n}, ${edge_list(e, 2)})')
		g.l('\tnz := b')
	} else {
		g.l('\tnz := b.map(if it == 0 { ${s}(3) } else { it })')
	}
	g.l('\tfor off := 0; off + ${n} <= a.len; off += 3 {')
	g.l('\t\tx := a[off..off + ${n}]\n\t\ty := b[off..off + ${n}]\n\t\tz := nz[off..off + ${n}]')
	g.l('\t\tva := simd.load_${low}_at(a, off)\n\t\tvb := simd.load_${low}_at(b, off)\n\t\tvz := simd.load_${low}_at(nz, off)')
	g.l("\t\tcheck_${s}('${t} load_at', va${arr}, x)")
	for op in [['+', 'add'], ['-', 'sub'], ['*', 'mul']] {
		g.l("\t\tcheck_${s}('${t} ${op[0]}', (va ${op[0]} vb)${arr}, ref2_${s}('${op[1]}', x, y))")
		g.l("\t\tcheck_${s}('${t} ${op[1]}', va.${op[1]}(vb)${arr}, ref2_${s}('${op[1]}', x, y))")
	}
	g.l("\t\tcheck_${s}('${t} /', (va / vz)${arr}, ref2_${s}('div', x, z))")
	g.l("\t\tcheck_${s}('${t} div', va.div(vz)${arr}, ref2_${s}('div', x, z))")
	g.l("\t\tcheck_${s}('${t} minimum', va.minimum(vb)${arr}, ref2_${s}('min', x, y))")
	g.l("\t\tcheck_${s}('${t} maximum', va.maximum(vb)${arr}, ref2_${s}('max', x, y))")
	mut unary := []string{}
	if e.kind != .unsigned {
		unary << ['neg', 'abs']
	}
	if isf {
		unary << 'sqrt'
		g.l("\t\tcheck_${s}('${t} mul_add', va.mul_add(vb, vz)${arr}, ref2_${s}('add', ref2_${s}('mul', x, y), z))")
	} else {
		unary << 'not'
		for op in ['and', 'or', 'xor'] {
			g.l("\t\tcheck_${s}('${t} ${op}', va.${op}(vb)${arr}, ref2_${s}('${op}', x, y))")
		}
		g.l('\t\tfor c in [u32(0), 1, ${e.bits - 1}, ${e.bits}, ${e.bits + 3}, 1000] {')
		g.l("\t\t\tcheck_${s}('${t} shl', va.shl(c)${arr}, refsh_${s}(true, x, c))")
		g.l("\t\t\tcheck_${s}('${t} shr', va.shr(c)${arr}, refsh_${s}(false, x, c))\n\t\t}")
	}
	for op in unary {
		g.l("\t\tcheck_${s}('${t} ${op}', va.${op}()${arr}, ref1_${s}('${op}', x))")
	}
	for op in ['eq', 'ne', 'lt', 'le', 'gt', 'ge'] {
		g.l("\t\tcheck_mask('${t} ${op}', va.${op}(vb)${arr}, refc_${s}('${op}', x, y))")
	}
	g.l("\t\tml := va.lt(vb)\n\t\tbl := refc_${s}('lt', x, y)")
	g.l("\t\tcheck_${s}('${t} select', simd.select_${low}(ml, va, vb)${arr}, refsel_${s}(bl, x, y))")
	g.l('\t\tassert ml.count() == bl.filter(it).len\n\t\tassert ml.all() == bl.all(it)\n\t\tassert ml.any() == bl.any(it)')
	g.l("\t\tcheck_${s}('${t} sum', [va.sum()], [refsum_${s}(x)])")
	g.l("\t\tcheck_${s}('${t} dot', [va.dot(vb)], [refdot_${s}(x, y)])")
	g.l('\t\tassert va.min_element() == refidx_${s}(x, true)\n\t\tassert va.max_element() == refidx_${s}(x, false)')
	g.l("\t\tcheck_${s}('${t} min', [va.min()], [x[refidx_${s}(x, true)]])")
	g.l("\t\tcheck_${s}('${t} max', [va.max()], [x[refidx_${s}(x, false)]])")
	for p in e.partners() {
		pl := vec_name(p, n).to_lower()
		if isf {
			if p.name == e.partners()[0].name {
				g.l('\t\tvc := simd.load_${low}_at(cv, off % (cv.len - ${n - 1}))')
			}
			g.l("\t\tcheck_${p.name}('${t} to_${pl}', vc.to_${pl}()${arr}, refconv_${s}_${p.name}(vc${arr}))")
		} else {
			g.l("\t\tcheck_${p.name}('${t} to_${pl}', va.to_${pl}()${arr}, x.map(${p.name}(it)))")
		}
	}
	g.l('\t\tmut vl := va\n\t\tvl[${n - 1}] = y[0]')
	g.l("\t\tcheck_${s}('${t} []', [vl[0], vl[${n - 1}]], [x[0], y[0]])")
	g.l('\t\tmut dst := []${s}{len: ${n + 2}}\n\t\tva.store_at(mut dst, 1)')
	g.l("\t\tcheck_${s}('${t} store_at', dst[1..${n + 1}], x)\n\t}")
	// Constructors and the error-returning load and store functions.
	g.l("\tcheck_${s}('${t} splat', simd.splat_${low}(a[2])${arr}, []${s}{len: ${n}, init: a[2]})")
	g.l('\tmut fa := [${n}]${s}{}\n\tfor i in 0 .. ${n} {\n\t\tfa[i] = a[i]\n\t}')
	g.l("\tcheck_${s}('${t} from_array', simd.from_array_${low}(fa)${arr}, a[..${n}])")
	if n <= 8 {
		args := []int{len: n, init: index}.map('a[${it}]').join(', ')
		g.l("\tcheck_${s}('${t} ${low}', simd.${low}(${args})${arr}, a[..${n}])")
	}
	g.l("\tvl := simd.load_${low}(a) or { panic(err) }\n\tcheck_${s}('${t} load', vl${arr}, a[..${n}])")
	g.l('\tvp := simd.load_${low}_part(a[..${n / 2}]) or { panic(err) }')
	g.l('\tmut want := a[..${n / 2}].clone()\n\twant << []${s}{len: ${n - n / 2}}')
	g.l("\tcheck_${s}('${t} load_part', vp${arr}, want)")
	g.l("\tmut out := []${s}{len: ${n}}\n\tvl.store(mut out) or { panic(err) }\n\tcheck_${s}('${t} store', out, a[..${n}])")
	g.l('\tmut tail := []${s}{len: ${n / 2}}\n\tvl.store_part(mut tail) or { panic(err) }')
	g.l("\tcheck_${s}('${t} store_part', tail, a[..${n / 2}])")
	g.l('\tif _ := simd.load_${low}(a[..${n - 1}]) {\n\t\tassert false\n\t}')
	g.l('\tif _ := simd.load_${low}_part(a[..${n + 1}]) {\n\t\tassert false\n\t}')
	g.l('\tvl.store(mut tail) or { tail.clear() }\n\tassert tail.len == 0')
	g.l('\tmut long := []${s}{len: ${n + 1}}\n\tvl.store_part(mut long) or { long.clear() }\n\tassert long.len == 0')
	g.l('}\n')
}

fn (mut g Gen) mask_test(bits int, n int) {
	t := mask_name(bits, n)
	low := t.to_lower()
	g.l('fn test_${low}() {\n\tfor seed in 0 .. 8 {')
	g.l('\t\tp := bools(${n}, seed)\n\t\tq := bools(${n}, seed + 8)')
	g.l('\t\tmut pa := [${n}]bool{}\n\t\tmut qa := [${n}]bool{}')
	g.l('\t\tfor i in 0 .. ${n} {\n\t\t\tpa[i] = p[i]\n\t\t\tqa[i] = q[i]\n\t\t}')
	g.l('\t\tm := simd.from_array_${low}(pa)\n\t\to := simd.from_array_${low}(qa)')
	g.l("\t\tcheck_mask('${t} to_array', m.to_array()[..], p)")
	g.l('\t\tassert m.all() == p.all(it)\n\t\tassert m.any() == p.any(it)\n\t\tassert m.count() == p.filter(it).len')
	for op in [['and', '&&'], ['or', '||'], ['xor', '!=']] {
		g.l("\t\tcheck_mask('${t} ${op[0]}', m.${op[0]}(o).to_array()[..], []bool{len: ${n}, init: p[index] ${op[1]} q[index]})")
	}
	g.l("\t\tcheck_mask('${t} not', m.not().to_array()[..], p.map(!it))")
	g.l('\t\tmut mm := m\n\t\tmm[${n - 1}] = !p[${n - 1}]\n\t\tassert mm[${n - 1}] == !p[${n - 1}]\n\t\tassert mm[0] == (p[0] != (${n - 1} == 0))\n\t}')
	g.l('\tassert simd.splat_${low}(true).all()\n\tassert !simd.splat_${low}(false).any()\n}\n')
}

fn gen_tests() string {
	mut g := Gen{}
	g.l(generated_note)
	g.l('module main\n')
	g.l(test_preamble)
	for e in elems {
		g.test_helpers(e)
	}
	for bits in [8, 16, 32, 64] {
		for n in elems.filter(it.bits == bits)[0].lanes() {
			g.mask_test(bits, n)
		}
	}
	for e in elems {
		for n in e.lanes() {
			g.vector_test(e, n)
		}
	}
	return g.str()
}
