/* Code generated by vlib/simd/gen.vsh; DO NOT EDIT. */
/* Regenerate with: v run vlib/simd/gen.vsh */
#ifndef VLIB_SIMD_SIMD_H
#define VLIB_SIMD_SIMD_H

/*
 * Element-wise helpers for vlib/simd. Each function processes `n` lanes stored
 * in plain arrays, which V passes as pointers to the first lane of a vector.
 *
 * With gcc and clang, the lanes are loaded into vectors declared with
 * __attribute__((vector_size(N))), so the C compiler emits SIMD instructions
 * for the target (SSE/AVX, NEON, ...) and splits wide vectors as needed.
 * tcc, msvc and builds with -DV_SIMD_FORCE_SCALAR use the scalar loops.
 * Both paths compute the same results: integer arithmetic goes through
 * unsigned types so it wraps, and callers keep shift counts in range.
 */

#include <math.h>
#include <stdint.h>
#include <string.h>

#if !defined(V_SIMD_FORCE_SCALAR) && !defined(__TINYC__) && (defined(__GNUC__) || defined(__clang__))
#define V_SIMD_VECTOR_EXT 1
#endif

#if defined(V_SIMD_VECTOR_EXT) && defined(__SSE__)
#include <xmmintrin.h>
#define V_SIMD_HAS_SSE 1
#if defined(__SSE2__)
#include <emmintrin.h>
#define V_SIMD_HAS_SSE2 1
#endif
#elif defined(V_SIMD_VECTOR_EXT) && defined(__aarch64__)
#include <arm_neon.h>
#define V_SIMD_HAS_NEON 1
#endif

#if defined(V_SIMD_VECTOR_EXT)
#define V_SIMD_BIN(VT, EXPR) { VT vx, vy, vr; memcpy(&vx, a, sizeof vx); memcpy(&vy, b, sizeof vy); vr = (EXPR); memcpy(out, &vr, sizeof vr); return; }
#define V_SIMD_UN(VT, EXPR) { VT vx, vr; memcpy(&vx, a, sizeof vx); vr = (EXPR); memcpy(out, &vr, sizeof vr); return; }
#define V_SIMD_CMP(VT, MT, EXPR) { VT vx, vy; MT vr; memcpy(&vx, a, sizeof vx); memcpy(&vy, b, sizeof vy); vr = (MT)(EXPR); memcpy(out, &vr, sizeof vr); return; }
#define V_SIMD_PICK(VT, UT, EXPR) { VT vx, vy; UT vm, vr; memcpy(&vx, a, sizeof vx); memcpy(&vy, b, sizeof vy); vm = (UT)(EXPR); vr = (vm & (UT)vy) | (~vm & (UT)vx); memcpy(out, &vr, sizeof vr); return; }
#define V_SIMD_SEL(UT, MT) { MT vm; UT vx, vy, vr; memcpy(&vm, m, sizeof vm); memcpy(&vx, a, sizeof vx); memcpy(&vy, b, sizeof vy); vr = ((UT)vm & vx) | (~(UT)vm & vy); memcpy(out, &vr, sizeof vr); return; }

typedef float v_simd_f32x2 __attribute__((vector_size(8)));
typedef float v_simd_f32x4 __attribute__((vector_size(16)));
typedef float v_simd_f32x8 __attribute__((vector_size(32)));
typedef float v_simd_f32x16 __attribute__((vector_size(64)));
typedef double v_simd_f64x2 __attribute__((vector_size(16)));
typedef double v_simd_f64x4 __attribute__((vector_size(32)));
typedef double v_simd_f64x8 __attribute__((vector_size(64)));
typedef int8_t v_simd_i8x8 __attribute__((vector_size(8)));
typedef int8_t v_simd_i8x16 __attribute__((vector_size(16)));
typedef int8_t v_simd_i8x32 __attribute__((vector_size(32)));
typedef int8_t v_simd_i8x64 __attribute__((vector_size(64)));
typedef int16_t v_simd_i16x4 __attribute__((vector_size(8)));
typedef int16_t v_simd_i16x8 __attribute__((vector_size(16)));
typedef int16_t v_simd_i16x16 __attribute__((vector_size(32)));
typedef int16_t v_simd_i16x32 __attribute__((vector_size(64)));
typedef int32_t v_simd_i32x2 __attribute__((vector_size(8)));
typedef int32_t v_simd_i32x4 __attribute__((vector_size(16)));
typedef int32_t v_simd_i32x8 __attribute__((vector_size(32)));
typedef int32_t v_simd_i32x16 __attribute__((vector_size(64)));
typedef int64_t v_simd_i64x2 __attribute__((vector_size(16)));
typedef int64_t v_simd_i64x4 __attribute__((vector_size(32)));
typedef int64_t v_simd_i64x8 __attribute__((vector_size(64)));
typedef uint8_t v_simd_u8x8 __attribute__((vector_size(8)));
typedef uint8_t v_simd_u8x16 __attribute__((vector_size(16)));
typedef uint8_t v_simd_u8x32 __attribute__((vector_size(32)));
typedef uint8_t v_simd_u8x64 __attribute__((vector_size(64)));
typedef uint16_t v_simd_u16x4 __attribute__((vector_size(8)));
typedef uint16_t v_simd_u16x8 __attribute__((vector_size(16)));
typedef uint16_t v_simd_u16x16 __attribute__((vector_size(32)));
typedef uint16_t v_simd_u16x32 __attribute__((vector_size(64)));
typedef uint32_t v_simd_u32x2 __attribute__((vector_size(8)));
typedef uint32_t v_simd_u32x4 __attribute__((vector_size(16)));
typedef uint32_t v_simd_u32x8 __attribute__((vector_size(32)));
typedef uint32_t v_simd_u32x16 __attribute__((vector_size(64)));
typedef uint64_t v_simd_u64x2 __attribute__((vector_size(16)));
typedef uint64_t v_simd_u64x4 __attribute__((vector_size(32)));
typedef uint64_t v_simd_u64x8 __attribute__((vector_size(64)));
#endif

static inline void v_simd_sqrt_f32(const float *a, float *out, int n) {
	int i = 0;
#if defined(V_SIMD_HAS_SSE)
	for (; i + 4 <= n; i += 4) _mm_storeu_ps(out + i, _mm_sqrt_ps(_mm_loadu_ps(a + i)));
#elif defined(V_SIMD_HAS_NEON)
	for (; i + 4 <= n; i += 4) vst1q_f32(out + i, vsqrtq_f32(vld1q_f32(a + i)));
#endif
	for (; i < n; i++) out[i] = sqrtf(a[i]);
}

static inline void v_simd_sqrt_f64(const double *a, double *out, int n) {
	int i = 0;
#if defined(V_SIMD_HAS_SSE2)
	for (; i + 2 <= n; i += 2) _mm_storeu_pd(out + i, _mm_sqrt_pd(_mm_loadu_pd(a + i)));
#elif defined(V_SIMD_HAS_NEON)
	for (; i + 2 <= n; i += 2) vst1q_f64(out + i, vsqrtq_f64(vld1q_f64(a + i)));
#endif
	for (; i < n; i++) out[i] = sqrt(a[i]);
}

static inline void v_simd_add_f32(const float *a, const float *b, float *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_f32x2, vx + vy)
	case 4: V_SIMD_BIN(v_simd_f32x4, vx + vy)
	case 8: V_SIMD_BIN(v_simd_f32x8, vx + vy)
	case 16: V_SIMD_BIN(v_simd_f32x16, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] + b[i];
}

static inline void v_simd_sub_f32(const float *a, const float *b, float *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_f32x2, vx - vy)
	case 4: V_SIMD_BIN(v_simd_f32x4, vx - vy)
	case 8: V_SIMD_BIN(v_simd_f32x8, vx - vy)
	case 16: V_SIMD_BIN(v_simd_f32x16, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] - b[i];
}

static inline void v_simd_mul_f32(const float *a, const float *b, float *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_f32x2, vx * vy)
	case 4: V_SIMD_BIN(v_simd_f32x4, vx * vy)
	case 8: V_SIMD_BIN(v_simd_f32x8, vx * vy)
	case 16: V_SIMD_BIN(v_simd_f32x16, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] * b[i];
}

static inline void v_simd_div_f32(const float *a, const float *b, float *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_f32x2, vx / vy)
	case 4: V_SIMD_BIN(v_simd_f32x4, vx / vy)
	case 8: V_SIMD_BIN(v_simd_f32x8, vx / vy)
	case 16: V_SIMD_BIN(v_simd_f32x16, vx / vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] / b[i];
}

static inline void v_simd_neg_f32(const float *a, float *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_f32x2, -vx)
	case 4: V_SIMD_UN(v_simd_f32x4, -vx)
	case 8: V_SIMD_UN(v_simd_f32x8, -vx)
	case 16: V_SIMD_UN(v_simd_f32x16, -vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = -a[i];
}

static inline void v_simd_abs_f32(const float *a, float *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u32x2, vx & 0x7fffffffu)
	case 4: V_SIMD_UN(v_simd_u32x4, vx & 0x7fffffffu)
	case 8: V_SIMD_UN(v_simd_u32x8, vx & 0x7fffffffu)
	case 16: V_SIMD_UN(v_simd_u32x16, vx & 0x7fffffffu)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = fabsf(a[i]);
}

static inline void v_simd_min_f32(const float *a, const float *b, float *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_f32x2, v_simd_u32x2, (vy < vx) | (vx != vx))
	case 4: V_SIMD_PICK(v_simd_f32x4, v_simd_u32x4, (vy < vx) | (vx != vx))
	case 8: V_SIMD_PICK(v_simd_f32x8, v_simd_u32x8, (vy < vx) | (vx != vx))
	case 16: V_SIMD_PICK(v_simd_f32x16, v_simd_u32x16, (vy < vx) | (vx != vx))
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (b[i] < a[i] || a[i] != a[i]) ? b[i] : a[i];
}

static inline void v_simd_max_f32(const float *a, const float *b, float *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_f32x2, v_simd_u32x2, (vy > vx) | (vx != vx))
	case 4: V_SIMD_PICK(v_simd_f32x4, v_simd_u32x4, (vy > vx) | (vx != vx))
	case 8: V_SIMD_PICK(v_simd_f32x8, v_simd_u32x8, (vy > vx) | (vx != vx))
	case 16: V_SIMD_PICK(v_simd_f32x16, v_simd_u32x16, (vy > vx) | (vx != vx))
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (b[i] > a[i] || a[i] != a[i]) ? b[i] : a[i];
}

static inline void v_simd_eq_f32(const float *a, const float *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_f32x2, v_simd_i32x2, vx == vy)
	case 4: V_SIMD_CMP(v_simd_f32x4, v_simd_i32x4, vx == vy)
	case 8: V_SIMD_CMP(v_simd_f32x8, v_simd_i32x8, vx == vy)
	case 16: V_SIMD_CMP(v_simd_f32x16, v_simd_i32x16, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_f32(const float *a, const float *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_f32x2, v_simd_i32x2, vx != vy)
	case 4: V_SIMD_CMP(v_simd_f32x4, v_simd_i32x4, vx != vy)
	case 8: V_SIMD_CMP(v_simd_f32x8, v_simd_i32x8, vx != vy)
	case 16: V_SIMD_CMP(v_simd_f32x16, v_simd_i32x16, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_f32(const float *a, const float *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_f32x2, v_simd_i32x2, vx < vy)
	case 4: V_SIMD_CMP(v_simd_f32x4, v_simd_i32x4, vx < vy)
	case 8: V_SIMD_CMP(v_simd_f32x8, v_simd_i32x8, vx < vy)
	case 16: V_SIMD_CMP(v_simd_f32x16, v_simd_i32x16, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] < b[i]);
}

static inline void v_simd_le_f32(const float *a, const float *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_f32x2, v_simd_i32x2, vx <= vy)
	case 4: V_SIMD_CMP(v_simd_f32x4, v_simd_i32x4, vx <= vy)
	case 8: V_SIMD_CMP(v_simd_f32x8, v_simd_i32x8, vx <= vy)
	case 16: V_SIMD_CMP(v_simd_f32x16, v_simd_i32x16, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_f32(const int32_t *m, const float *a, const float *b, float *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_SEL(v_simd_u32x2, v_simd_i32x2)
	case 4: V_SIMD_SEL(v_simd_u32x4, v_simd_i32x4)
	case 8: V_SIMD_SEL(v_simd_u32x8, v_simd_i32x8)
	case 16: V_SIMD_SEL(v_simd_u32x16, v_simd_i32x16)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

static inline void v_simd_add_f64(const double *a, const double *b, double *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_f64x2, vx + vy)
	case 4: V_SIMD_BIN(v_simd_f64x4, vx + vy)
	case 8: V_SIMD_BIN(v_simd_f64x8, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] + b[i];
}

static inline void v_simd_sub_f64(const double *a, const double *b, double *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_f64x2, vx - vy)
	case 4: V_SIMD_BIN(v_simd_f64x4, vx - vy)
	case 8: V_SIMD_BIN(v_simd_f64x8, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] - b[i];
}

static inline void v_simd_mul_f64(const double *a, const double *b, double *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_f64x2, vx * vy)
	case 4: V_SIMD_BIN(v_simd_f64x4, vx * vy)
	case 8: V_SIMD_BIN(v_simd_f64x8, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] * b[i];
}

static inline void v_simd_div_f64(const double *a, const double *b, double *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_f64x2, vx / vy)
	case 4: V_SIMD_BIN(v_simd_f64x4, vx / vy)
	case 8: V_SIMD_BIN(v_simd_f64x8, vx / vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] / b[i];
}

static inline void v_simd_neg_f64(const double *a, double *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_f64x2, -vx)
	case 4: V_SIMD_UN(v_simd_f64x4, -vx)
	case 8: V_SIMD_UN(v_simd_f64x8, -vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = -a[i];
}

static inline void v_simd_abs_f64(const double *a, double *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u64x2, vx & 0x7fffffffffffffffull)
	case 4: V_SIMD_UN(v_simd_u64x4, vx & 0x7fffffffffffffffull)
	case 8: V_SIMD_UN(v_simd_u64x8, vx & 0x7fffffffffffffffull)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = fabs(a[i]);
}

static inline void v_simd_min_f64(const double *a, const double *b, double *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_f64x2, v_simd_u64x2, (vy < vx) | (vx != vx))
	case 4: V_SIMD_PICK(v_simd_f64x4, v_simd_u64x4, (vy < vx) | (vx != vx))
	case 8: V_SIMD_PICK(v_simd_f64x8, v_simd_u64x8, (vy < vx) | (vx != vx))
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (b[i] < a[i] || a[i] != a[i]) ? b[i] : a[i];
}

static inline void v_simd_max_f64(const double *a, const double *b, double *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_f64x2, v_simd_u64x2, (vy > vx) | (vx != vx))
	case 4: V_SIMD_PICK(v_simd_f64x4, v_simd_u64x4, (vy > vx) | (vx != vx))
	case 8: V_SIMD_PICK(v_simd_f64x8, v_simd_u64x8, (vy > vx) | (vx != vx))
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (b[i] > a[i] || a[i] != a[i]) ? b[i] : a[i];
}

static inline void v_simd_eq_f64(const double *a, const double *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_f64x2, v_simd_i64x2, vx == vy)
	case 4: V_SIMD_CMP(v_simd_f64x4, v_simd_i64x4, vx == vy)
	case 8: V_SIMD_CMP(v_simd_f64x8, v_simd_i64x8, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_f64(const double *a, const double *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_f64x2, v_simd_i64x2, vx != vy)
	case 4: V_SIMD_CMP(v_simd_f64x4, v_simd_i64x4, vx != vy)
	case 8: V_SIMD_CMP(v_simd_f64x8, v_simd_i64x8, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_f64(const double *a, const double *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_f64x2, v_simd_i64x2, vx < vy)
	case 4: V_SIMD_CMP(v_simd_f64x4, v_simd_i64x4, vx < vy)
	case 8: V_SIMD_CMP(v_simd_f64x8, v_simd_i64x8, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] < b[i]);
}

static inline void v_simd_le_f64(const double *a, const double *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_f64x2, v_simd_i64x2, vx <= vy)
	case 4: V_SIMD_CMP(v_simd_f64x4, v_simd_i64x4, vx <= vy)
	case 8: V_SIMD_CMP(v_simd_f64x8, v_simd_i64x8, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_f64(const int64_t *m, const double *a, const double *b, double *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_SEL(v_simd_u64x2, v_simd_i64x2)
	case 4: V_SIMD_SEL(v_simd_u64x4, v_simd_i64x4)
	case 8: V_SIMD_SEL(v_simd_u64x8, v_simd_i64x8)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

static inline void v_simd_add_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx + vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx + vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx + vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)((uint32_t)a[i] + (uint32_t)b[i]);
}

static inline void v_simd_sub_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx - vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx - vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx - vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)((uint32_t)a[i] - (uint32_t)b[i]);
}

static inline void v_simd_mul_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx * vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx * vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx * vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)((uint32_t)a[i] * (uint32_t)b[i]);
}

static inline void v_simd_min_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_PICK(v_simd_i8x8, v_simd_u8x8, vy < vx)
	case 16: V_SIMD_PICK(v_simd_i8x16, v_simd_u8x16, vy < vx)
	case 32: V_SIMD_PICK(v_simd_i8x32, v_simd_u8x32, vy < vx)
	case 64: V_SIMD_PICK(v_simd_i8x64, v_simd_u8x64, vy < vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] < a[i] ? b[i] : a[i];
}

static inline void v_simd_max_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_PICK(v_simd_i8x8, v_simd_u8x8, vy > vx)
	case 16: V_SIMD_PICK(v_simd_i8x16, v_simd_u8x16, vy > vx)
	case 32: V_SIMD_PICK(v_simd_i8x32, v_simd_u8x32, vy > vx)
	case 64: V_SIMD_PICK(v_simd_i8x64, v_simd_u8x64, vy > vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] > a[i] ? b[i] : a[i];
}

static inline void v_simd_and_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx & vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx & vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx & vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx & vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)(a[i] & b[i]);
}

static inline void v_simd_or_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx | vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx | vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx | vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx | vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)(a[i] | b[i]);
}

static inline void v_simd_xor_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx ^ vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx ^ vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx ^ vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx ^ vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)(a[i] ^ b[i]);
}

static inline void v_simd_not_i8(const int8_t *a, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_UN(v_simd_u8x8, ~vx)
	case 16: V_SIMD_UN(v_simd_u8x16, ~vx)
	case 32: V_SIMD_UN(v_simd_u8x32, ~vx)
	case 64: V_SIMD_UN(v_simd_u8x64, ~vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)~a[i];
}

static inline void v_simd_shl_i8(const int8_t *a, unsigned count, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_UN(v_simd_u8x8, vx << (uint8_t)count)
	case 16: V_SIMD_UN(v_simd_u8x16, vx << (uint8_t)count)
	case 32: V_SIMD_UN(v_simd_u8x32, vx << (uint8_t)count)
	case 64: V_SIMD_UN(v_simd_u8x64, vx << (uint8_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)((uint32_t)a[i] << count);
}

static inline void v_simd_shr_i8(const int8_t *a, unsigned count, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_UN(v_simd_i8x8, vx >> (int8_t)count)
	case 16: V_SIMD_UN(v_simd_i8x16, vx >> (int8_t)count)
	case 32: V_SIMD_UN(v_simd_i8x32, vx >> (int8_t)count)
	case 64: V_SIMD_UN(v_simd_i8x64, vx >> (int8_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)(a[i] >> count);
}

static inline void v_simd_neg_i8(const int8_t *a, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_UN(v_simd_u8x8, -vx)
	case 16: V_SIMD_UN(v_simd_u8x16, -vx)
	case 32: V_SIMD_UN(v_simd_u8x32, -vx)
	case 64: V_SIMD_UN(v_simd_u8x64, -vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)((uint32_t)0 - (uint32_t)a[i]);
}

static inline void v_simd_abs_i8(const int8_t *a, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_UN(v_simd_i8x8, (v_simd_i8x8)(((v_simd_u8x8)vx ^ (v_simd_u8x8)(vx >> 7)) - (v_simd_u8x8)(vx >> 7)))
	case 16: V_SIMD_UN(v_simd_i8x16, (v_simd_i8x16)(((v_simd_u8x16)vx ^ (v_simd_u8x16)(vx >> 7)) - (v_simd_u8x16)(vx >> 7)))
	case 32: V_SIMD_UN(v_simd_i8x32, (v_simd_i8x32)(((v_simd_u8x32)vx ^ (v_simd_u8x32)(vx >> 7)) - (v_simd_u8x32)(vx >> 7)))
	case 64: V_SIMD_UN(v_simd_i8x64, (v_simd_i8x64)(((v_simd_u8x64)vx ^ (v_simd_u8x64)(vx >> 7)) - (v_simd_u8x64)(vx >> 7)))
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] < 0 ? (int8_t)((uint32_t)0 - (uint32_t)a[i]) : a[i];
}

static inline void v_simd_eq_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_CMP(v_simd_i8x8, v_simd_i8x8, vx == vy)
	case 16: V_SIMD_CMP(v_simd_i8x16, v_simd_i8x16, vx == vy)
	case 32: V_SIMD_CMP(v_simd_i8x32, v_simd_i8x32, vx == vy)
	case 64: V_SIMD_CMP(v_simd_i8x64, v_simd_i8x64, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_CMP(v_simd_i8x8, v_simd_i8x8, vx != vy)
	case 16: V_SIMD_CMP(v_simd_i8x16, v_simd_i8x16, vx != vy)
	case 32: V_SIMD_CMP(v_simd_i8x32, v_simd_i8x32, vx != vy)
	case 64: V_SIMD_CMP(v_simd_i8x64, v_simd_i8x64, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_CMP(v_simd_i8x8, v_simd_i8x8, vx < vy)
	case 16: V_SIMD_CMP(v_simd_i8x16, v_simd_i8x16, vx < vy)
	case 32: V_SIMD_CMP(v_simd_i8x32, v_simd_i8x32, vx < vy)
	case 64: V_SIMD_CMP(v_simd_i8x64, v_simd_i8x64, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)-(a[i] < b[i]);
}

static inline void v_simd_le_i8(const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_CMP(v_simd_i8x8, v_simd_i8x8, vx <= vy)
	case 16: V_SIMD_CMP(v_simd_i8x16, v_simd_i8x16, vx <= vy)
	case 32: V_SIMD_CMP(v_simd_i8x32, v_simd_i8x32, vx <= vy)
	case 64: V_SIMD_CMP(v_simd_i8x64, v_simd_i8x64, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_i8(const int8_t *m, const int8_t *a, const int8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_SEL(v_simd_u8x8, v_simd_i8x8)
	case 16: V_SIMD_SEL(v_simd_u8x16, v_simd_i8x16)
	case 32: V_SIMD_SEL(v_simd_u8x32, v_simd_i8x32)
	case 64: V_SIMD_SEL(v_simd_u8x64, v_simd_i8x64)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

static inline void v_simd_add_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx + vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx + vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx + vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)((uint32_t)a[i] + (uint32_t)b[i]);
}

static inline void v_simd_sub_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx - vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx - vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx - vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)((uint32_t)a[i] - (uint32_t)b[i]);
}

static inline void v_simd_mul_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx * vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx * vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx * vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)((uint32_t)a[i] * (uint32_t)b[i]);
}

static inline void v_simd_min_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_PICK(v_simd_i16x4, v_simd_u16x4, vy < vx)
	case 8: V_SIMD_PICK(v_simd_i16x8, v_simd_u16x8, vy < vx)
	case 16: V_SIMD_PICK(v_simd_i16x16, v_simd_u16x16, vy < vx)
	case 32: V_SIMD_PICK(v_simd_i16x32, v_simd_u16x32, vy < vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] < a[i] ? b[i] : a[i];
}

static inline void v_simd_max_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_PICK(v_simd_i16x4, v_simd_u16x4, vy > vx)
	case 8: V_SIMD_PICK(v_simd_i16x8, v_simd_u16x8, vy > vx)
	case 16: V_SIMD_PICK(v_simd_i16x16, v_simd_u16x16, vy > vx)
	case 32: V_SIMD_PICK(v_simd_i16x32, v_simd_u16x32, vy > vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] > a[i] ? b[i] : a[i];
}

static inline void v_simd_and_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx & vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx & vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx & vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx & vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)(a[i] & b[i]);
}

static inline void v_simd_or_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx | vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx | vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx | vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx | vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)(a[i] | b[i]);
}

static inline void v_simd_xor_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx ^ vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx ^ vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx ^ vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx ^ vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)(a[i] ^ b[i]);
}

static inline void v_simd_not_i16(const int16_t *a, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_UN(v_simd_u16x4, ~vx)
	case 8: V_SIMD_UN(v_simd_u16x8, ~vx)
	case 16: V_SIMD_UN(v_simd_u16x16, ~vx)
	case 32: V_SIMD_UN(v_simd_u16x32, ~vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)~a[i];
}

static inline void v_simd_shl_i16(const int16_t *a, unsigned count, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_UN(v_simd_u16x4, vx << (uint16_t)count)
	case 8: V_SIMD_UN(v_simd_u16x8, vx << (uint16_t)count)
	case 16: V_SIMD_UN(v_simd_u16x16, vx << (uint16_t)count)
	case 32: V_SIMD_UN(v_simd_u16x32, vx << (uint16_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)((uint32_t)a[i] << count);
}

static inline void v_simd_shr_i16(const int16_t *a, unsigned count, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_UN(v_simd_i16x4, vx >> (int16_t)count)
	case 8: V_SIMD_UN(v_simd_i16x8, vx >> (int16_t)count)
	case 16: V_SIMD_UN(v_simd_i16x16, vx >> (int16_t)count)
	case 32: V_SIMD_UN(v_simd_i16x32, vx >> (int16_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)(a[i] >> count);
}

static inline void v_simd_neg_i16(const int16_t *a, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_UN(v_simd_u16x4, -vx)
	case 8: V_SIMD_UN(v_simd_u16x8, -vx)
	case 16: V_SIMD_UN(v_simd_u16x16, -vx)
	case 32: V_SIMD_UN(v_simd_u16x32, -vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)((uint32_t)0 - (uint32_t)a[i]);
}

static inline void v_simd_abs_i16(const int16_t *a, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_UN(v_simd_i16x4, (v_simd_i16x4)(((v_simd_u16x4)vx ^ (v_simd_u16x4)(vx >> 15)) - (v_simd_u16x4)(vx >> 15)))
	case 8: V_SIMD_UN(v_simd_i16x8, (v_simd_i16x8)(((v_simd_u16x8)vx ^ (v_simd_u16x8)(vx >> 15)) - (v_simd_u16x8)(vx >> 15)))
	case 16: V_SIMD_UN(v_simd_i16x16, (v_simd_i16x16)(((v_simd_u16x16)vx ^ (v_simd_u16x16)(vx >> 15)) - (v_simd_u16x16)(vx >> 15)))
	case 32: V_SIMD_UN(v_simd_i16x32, (v_simd_i16x32)(((v_simd_u16x32)vx ^ (v_simd_u16x32)(vx >> 15)) - (v_simd_u16x32)(vx >> 15)))
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] < 0 ? (int16_t)((uint32_t)0 - (uint32_t)a[i]) : a[i];
}

static inline void v_simd_eq_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_CMP(v_simd_i16x4, v_simd_i16x4, vx == vy)
	case 8: V_SIMD_CMP(v_simd_i16x8, v_simd_i16x8, vx == vy)
	case 16: V_SIMD_CMP(v_simd_i16x16, v_simd_i16x16, vx == vy)
	case 32: V_SIMD_CMP(v_simd_i16x32, v_simd_i16x32, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_CMP(v_simd_i16x4, v_simd_i16x4, vx != vy)
	case 8: V_SIMD_CMP(v_simd_i16x8, v_simd_i16x8, vx != vy)
	case 16: V_SIMD_CMP(v_simd_i16x16, v_simd_i16x16, vx != vy)
	case 32: V_SIMD_CMP(v_simd_i16x32, v_simd_i16x32, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_CMP(v_simd_i16x4, v_simd_i16x4, vx < vy)
	case 8: V_SIMD_CMP(v_simd_i16x8, v_simd_i16x8, vx < vy)
	case 16: V_SIMD_CMP(v_simd_i16x16, v_simd_i16x16, vx < vy)
	case 32: V_SIMD_CMP(v_simd_i16x32, v_simd_i16x32, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)-(a[i] < b[i]);
}

static inline void v_simd_le_i16(const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_CMP(v_simd_i16x4, v_simd_i16x4, vx <= vy)
	case 8: V_SIMD_CMP(v_simd_i16x8, v_simd_i16x8, vx <= vy)
	case 16: V_SIMD_CMP(v_simd_i16x16, v_simd_i16x16, vx <= vy)
	case 32: V_SIMD_CMP(v_simd_i16x32, v_simd_i16x32, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_i16(const int16_t *m, const int16_t *a, const int16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_SEL(v_simd_u16x4, v_simd_i16x4)
	case 8: V_SIMD_SEL(v_simd_u16x8, v_simd_i16x8)
	case 16: V_SIMD_SEL(v_simd_u16x16, v_simd_i16x16)
	case 32: V_SIMD_SEL(v_simd_u16x32, v_simd_i16x32)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

static inline void v_simd_add_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx + vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx + vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx + vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)((uint32_t)a[i] + (uint32_t)b[i]);
}

static inline void v_simd_sub_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx - vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx - vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx - vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)((uint32_t)a[i] - (uint32_t)b[i]);
}

static inline void v_simd_mul_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx * vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx * vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx * vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)((uint32_t)a[i] * (uint32_t)b[i]);
}

static inline void v_simd_min_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_i32x2, v_simd_u32x2, vy < vx)
	case 4: V_SIMD_PICK(v_simd_i32x4, v_simd_u32x4, vy < vx)
	case 8: V_SIMD_PICK(v_simd_i32x8, v_simd_u32x8, vy < vx)
	case 16: V_SIMD_PICK(v_simd_i32x16, v_simd_u32x16, vy < vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] < a[i] ? b[i] : a[i];
}

static inline void v_simd_max_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_i32x2, v_simd_u32x2, vy > vx)
	case 4: V_SIMD_PICK(v_simd_i32x4, v_simd_u32x4, vy > vx)
	case 8: V_SIMD_PICK(v_simd_i32x8, v_simd_u32x8, vy > vx)
	case 16: V_SIMD_PICK(v_simd_i32x16, v_simd_u32x16, vy > vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] > a[i] ? b[i] : a[i];
}

static inline void v_simd_and_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx & vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx & vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx & vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx & vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)(a[i] & b[i]);
}

static inline void v_simd_or_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx | vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx | vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx | vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx | vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)(a[i] | b[i]);
}

static inline void v_simd_xor_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx ^ vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx ^ vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx ^ vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx ^ vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)(a[i] ^ b[i]);
}

static inline void v_simd_not_i32(const int32_t *a, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u32x2, ~vx)
	case 4: V_SIMD_UN(v_simd_u32x4, ~vx)
	case 8: V_SIMD_UN(v_simd_u32x8, ~vx)
	case 16: V_SIMD_UN(v_simd_u32x16, ~vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)~a[i];
}

static inline void v_simd_shl_i32(const int32_t *a, unsigned count, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u32x2, vx << (uint32_t)count)
	case 4: V_SIMD_UN(v_simd_u32x4, vx << (uint32_t)count)
	case 8: V_SIMD_UN(v_simd_u32x8, vx << (uint32_t)count)
	case 16: V_SIMD_UN(v_simd_u32x16, vx << (uint32_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)((uint32_t)a[i] << count);
}

static inline void v_simd_shr_i32(const int32_t *a, unsigned count, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_i32x2, vx >> (int32_t)count)
	case 4: V_SIMD_UN(v_simd_i32x4, vx >> (int32_t)count)
	case 8: V_SIMD_UN(v_simd_i32x8, vx >> (int32_t)count)
	case 16: V_SIMD_UN(v_simd_i32x16, vx >> (int32_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)(a[i] >> count);
}

static inline void v_simd_neg_i32(const int32_t *a, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u32x2, -vx)
	case 4: V_SIMD_UN(v_simd_u32x4, -vx)
	case 8: V_SIMD_UN(v_simd_u32x8, -vx)
	case 16: V_SIMD_UN(v_simd_u32x16, -vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)((uint32_t)0 - (uint32_t)a[i]);
}

static inline void v_simd_abs_i32(const int32_t *a, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_i32x2, (v_simd_i32x2)(((v_simd_u32x2)vx ^ (v_simd_u32x2)(vx >> 31)) - (v_simd_u32x2)(vx >> 31)))
	case 4: V_SIMD_UN(v_simd_i32x4, (v_simd_i32x4)(((v_simd_u32x4)vx ^ (v_simd_u32x4)(vx >> 31)) - (v_simd_u32x4)(vx >> 31)))
	case 8: V_SIMD_UN(v_simd_i32x8, (v_simd_i32x8)(((v_simd_u32x8)vx ^ (v_simd_u32x8)(vx >> 31)) - (v_simd_u32x8)(vx >> 31)))
	case 16: V_SIMD_UN(v_simd_i32x16, (v_simd_i32x16)(((v_simd_u32x16)vx ^ (v_simd_u32x16)(vx >> 31)) - (v_simd_u32x16)(vx >> 31)))
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] < 0 ? (int32_t)((uint32_t)0 - (uint32_t)a[i]) : a[i];
}

static inline void v_simd_eq_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_i32x2, v_simd_i32x2, vx == vy)
	case 4: V_SIMD_CMP(v_simd_i32x4, v_simd_i32x4, vx == vy)
	case 8: V_SIMD_CMP(v_simd_i32x8, v_simd_i32x8, vx == vy)
	case 16: V_SIMD_CMP(v_simd_i32x16, v_simd_i32x16, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_i32x2, v_simd_i32x2, vx != vy)
	case 4: V_SIMD_CMP(v_simd_i32x4, v_simd_i32x4, vx != vy)
	case 8: V_SIMD_CMP(v_simd_i32x8, v_simd_i32x8, vx != vy)
	case 16: V_SIMD_CMP(v_simd_i32x16, v_simd_i32x16, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_i32x2, v_simd_i32x2, vx < vy)
	case 4: V_SIMD_CMP(v_simd_i32x4, v_simd_i32x4, vx < vy)
	case 8: V_SIMD_CMP(v_simd_i32x8, v_simd_i32x8, vx < vy)
	case 16: V_SIMD_CMP(v_simd_i32x16, v_simd_i32x16, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] < b[i]);
}

static inline void v_simd_le_i32(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_i32x2, v_simd_i32x2, vx <= vy)
	case 4: V_SIMD_CMP(v_simd_i32x4, v_simd_i32x4, vx <= vy)
	case 8: V_SIMD_CMP(v_simd_i32x8, v_simd_i32x8, vx <= vy)
	case 16: V_SIMD_CMP(v_simd_i32x16, v_simd_i32x16, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_i32(const int32_t *m, const int32_t *a, const int32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_SEL(v_simd_u32x2, v_simd_i32x2)
	case 4: V_SIMD_SEL(v_simd_u32x4, v_simd_i32x4)
	case 8: V_SIMD_SEL(v_simd_u32x8, v_simd_i32x8)
	case 16: V_SIMD_SEL(v_simd_u32x16, v_simd_i32x16)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

static inline void v_simd_add_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx + vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx + vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)((uint64_t)a[i] + (uint64_t)b[i]);
}

static inline void v_simd_sub_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx - vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx - vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)((uint64_t)a[i] - (uint64_t)b[i]);
}

static inline void v_simd_mul_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx * vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx * vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)((uint64_t)a[i] * (uint64_t)b[i]);
}

static inline void v_simd_min_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_i64x2, v_simd_u64x2, vy < vx)
	case 4: V_SIMD_PICK(v_simd_i64x4, v_simd_u64x4, vy < vx)
	case 8: V_SIMD_PICK(v_simd_i64x8, v_simd_u64x8, vy < vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] < a[i] ? b[i] : a[i];
}

static inline void v_simd_max_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_i64x2, v_simd_u64x2, vy > vx)
	case 4: V_SIMD_PICK(v_simd_i64x4, v_simd_u64x4, vy > vx)
	case 8: V_SIMD_PICK(v_simd_i64x8, v_simd_u64x8, vy > vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] > a[i] ? b[i] : a[i];
}

static inline void v_simd_and_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx & vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx & vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx & vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)(a[i] & b[i]);
}

static inline void v_simd_or_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx | vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx | vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx | vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)(a[i] | b[i]);
}

static inline void v_simd_xor_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx ^ vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx ^ vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx ^ vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)(a[i] ^ b[i]);
}

static inline void v_simd_not_i64(const int64_t *a, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u64x2, ~vx)
	case 4: V_SIMD_UN(v_simd_u64x4, ~vx)
	case 8: V_SIMD_UN(v_simd_u64x8, ~vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)~a[i];
}

static inline void v_simd_shl_i64(const int64_t *a, unsigned count, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u64x2, vx << (uint64_t)count)
	case 4: V_SIMD_UN(v_simd_u64x4, vx << (uint64_t)count)
	case 8: V_SIMD_UN(v_simd_u64x8, vx << (uint64_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)((uint64_t)a[i] << count);
}

static inline void v_simd_shr_i64(const int64_t *a, unsigned count, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_i64x2, vx >> (int64_t)count)
	case 4: V_SIMD_UN(v_simd_i64x4, vx >> (int64_t)count)
	case 8: V_SIMD_UN(v_simd_i64x8, vx >> (int64_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)(a[i] >> count);
}

static inline void v_simd_neg_i64(const int64_t *a, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u64x2, -vx)
	case 4: V_SIMD_UN(v_simd_u64x4, -vx)
	case 8: V_SIMD_UN(v_simd_u64x8, -vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)((uint64_t)0 - (uint64_t)a[i]);
}

static inline void v_simd_abs_i64(const int64_t *a, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_i64x2, (v_simd_i64x2)(((v_simd_u64x2)vx ^ (v_simd_u64x2)(vx >> 63)) - (v_simd_u64x2)(vx >> 63)))
	case 4: V_SIMD_UN(v_simd_i64x4, (v_simd_i64x4)(((v_simd_u64x4)vx ^ (v_simd_u64x4)(vx >> 63)) - (v_simd_u64x4)(vx >> 63)))
	case 8: V_SIMD_UN(v_simd_i64x8, (v_simd_i64x8)(((v_simd_u64x8)vx ^ (v_simd_u64x8)(vx >> 63)) - (v_simd_u64x8)(vx >> 63)))
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = a[i] < 0 ? (int64_t)((uint64_t)0 - (uint64_t)a[i]) : a[i];
}

static inline void v_simd_eq_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_i64x2, v_simd_i64x2, vx == vy)
	case 4: V_SIMD_CMP(v_simd_i64x4, v_simd_i64x4, vx == vy)
	case 8: V_SIMD_CMP(v_simd_i64x8, v_simd_i64x8, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_i64x2, v_simd_i64x2, vx != vy)
	case 4: V_SIMD_CMP(v_simd_i64x4, v_simd_i64x4, vx != vy)
	case 8: V_SIMD_CMP(v_simd_i64x8, v_simd_i64x8, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_i64x2, v_simd_i64x2, vx < vy)
	case 4: V_SIMD_CMP(v_simd_i64x4, v_simd_i64x4, vx < vy)
	case 8: V_SIMD_CMP(v_simd_i64x8, v_simd_i64x8, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] < b[i]);
}

static inline void v_simd_le_i64(const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_i64x2, v_simd_i64x2, vx <= vy)
	case 4: V_SIMD_CMP(v_simd_i64x4, v_simd_i64x4, vx <= vy)
	case 8: V_SIMD_CMP(v_simd_i64x8, v_simd_i64x8, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_i64(const int64_t *m, const int64_t *a, const int64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_SEL(v_simd_u64x2, v_simd_i64x2)
	case 4: V_SIMD_SEL(v_simd_u64x4, v_simd_i64x4)
	case 8: V_SIMD_SEL(v_simd_u64x8, v_simd_i64x8)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

static inline void v_simd_add_u8(const uint8_t *a, const uint8_t *b, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx + vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx + vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx + vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint8_t)((uint32_t)a[i] + (uint32_t)b[i]);
}

static inline void v_simd_sub_u8(const uint8_t *a, const uint8_t *b, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx - vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx - vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx - vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint8_t)((uint32_t)a[i] - (uint32_t)b[i]);
}

static inline void v_simd_mul_u8(const uint8_t *a, const uint8_t *b, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx * vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx * vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx * vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint8_t)((uint32_t)a[i] * (uint32_t)b[i]);
}

static inline void v_simd_min_u8(const uint8_t *a, const uint8_t *b, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_PICK(v_simd_u8x8, v_simd_u8x8, vy < vx)
	case 16: V_SIMD_PICK(v_simd_u8x16, v_simd_u8x16, vy < vx)
	case 32: V_SIMD_PICK(v_simd_u8x32, v_simd_u8x32, vy < vx)
	case 64: V_SIMD_PICK(v_simd_u8x64, v_simd_u8x64, vy < vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] < a[i] ? b[i] : a[i];
}

static inline void v_simd_max_u8(const uint8_t *a, const uint8_t *b, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_PICK(v_simd_u8x8, v_simd_u8x8, vy > vx)
	case 16: V_SIMD_PICK(v_simd_u8x16, v_simd_u8x16, vy > vx)
	case 32: V_SIMD_PICK(v_simd_u8x32, v_simd_u8x32, vy > vx)
	case 64: V_SIMD_PICK(v_simd_u8x64, v_simd_u8x64, vy > vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] > a[i] ? b[i] : a[i];
}

static inline void v_simd_and_u8(const uint8_t *a, const uint8_t *b, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx & vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx & vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx & vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx & vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint8_t)(a[i] & b[i]);
}

static inline void v_simd_or_u8(const uint8_t *a, const uint8_t *b, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx | vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx | vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx | vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx | vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint8_t)(a[i] | b[i]);
}

static inline void v_simd_xor_u8(const uint8_t *a, const uint8_t *b, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_BIN(v_simd_u8x8, vx ^ vy)
	case 16: V_SIMD_BIN(v_simd_u8x16, vx ^ vy)
	case 32: V_SIMD_BIN(v_simd_u8x32, vx ^ vy)
	case 64: V_SIMD_BIN(v_simd_u8x64, vx ^ vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint8_t)(a[i] ^ b[i]);
}

static inline void v_simd_not_u8(const uint8_t *a, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_UN(v_simd_u8x8, ~vx)
	case 16: V_SIMD_UN(v_simd_u8x16, ~vx)
	case 32: V_SIMD_UN(v_simd_u8x32, ~vx)
	case 64: V_SIMD_UN(v_simd_u8x64, ~vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint8_t)~a[i];
}

static inline void v_simd_shl_u8(const uint8_t *a, unsigned count, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_UN(v_simd_u8x8, vx << (uint8_t)count)
	case 16: V_SIMD_UN(v_simd_u8x16, vx << (uint8_t)count)
	case 32: V_SIMD_UN(v_simd_u8x32, vx << (uint8_t)count)
	case 64: V_SIMD_UN(v_simd_u8x64, vx << (uint8_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint8_t)((uint32_t)a[i] << count);
}

static inline void v_simd_shr_u8(const uint8_t *a, unsigned count, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_UN(v_simd_u8x8, vx >> (uint8_t)count)
	case 16: V_SIMD_UN(v_simd_u8x16, vx >> (uint8_t)count)
	case 32: V_SIMD_UN(v_simd_u8x32, vx >> (uint8_t)count)
	case 64: V_SIMD_UN(v_simd_u8x64, vx >> (uint8_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint8_t)(a[i] >> count);
}

static inline void v_simd_eq_u8(const uint8_t *a, const uint8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_CMP(v_simd_u8x8, v_simd_i8x8, vx == vy)
	case 16: V_SIMD_CMP(v_simd_u8x16, v_simd_i8x16, vx == vy)
	case 32: V_SIMD_CMP(v_simd_u8x32, v_simd_i8x32, vx == vy)
	case 64: V_SIMD_CMP(v_simd_u8x64, v_simd_i8x64, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_u8(const uint8_t *a, const uint8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_CMP(v_simd_u8x8, v_simd_i8x8, vx != vy)
	case 16: V_SIMD_CMP(v_simd_u8x16, v_simd_i8x16, vx != vy)
	case 32: V_SIMD_CMP(v_simd_u8x32, v_simd_i8x32, vx != vy)
	case 64: V_SIMD_CMP(v_simd_u8x64, v_simd_i8x64, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_u8(const uint8_t *a, const uint8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_CMP(v_simd_u8x8, v_simd_i8x8, vx < vy)
	case 16: V_SIMD_CMP(v_simd_u8x16, v_simd_i8x16, vx < vy)
	case 32: V_SIMD_CMP(v_simd_u8x32, v_simd_i8x32, vx < vy)
	case 64: V_SIMD_CMP(v_simd_u8x64, v_simd_i8x64, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)-(a[i] < b[i]);
}

static inline void v_simd_le_u8(const uint8_t *a, const uint8_t *b, int8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_CMP(v_simd_u8x8, v_simd_i8x8, vx <= vy)
	case 16: V_SIMD_CMP(v_simd_u8x16, v_simd_i8x16, vx <= vy)
	case 32: V_SIMD_CMP(v_simd_u8x32, v_simd_i8x32, vx <= vy)
	case 64: V_SIMD_CMP(v_simd_u8x64, v_simd_i8x64, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int8_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_u8(const int8_t *m, const uint8_t *a, const uint8_t *b, uint8_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 8: V_SIMD_SEL(v_simd_u8x8, v_simd_i8x8)
	case 16: V_SIMD_SEL(v_simd_u8x16, v_simd_i8x16)
	case 32: V_SIMD_SEL(v_simd_u8x32, v_simd_i8x32)
	case 64: V_SIMD_SEL(v_simd_u8x64, v_simd_i8x64)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

static inline void v_simd_add_u16(const uint16_t *a, const uint16_t *b, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx + vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx + vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx + vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint16_t)((uint32_t)a[i] + (uint32_t)b[i]);
}

static inline void v_simd_sub_u16(const uint16_t *a, const uint16_t *b, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx - vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx - vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx - vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint16_t)((uint32_t)a[i] - (uint32_t)b[i]);
}

static inline void v_simd_mul_u16(const uint16_t *a, const uint16_t *b, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx * vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx * vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx * vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint16_t)((uint32_t)a[i] * (uint32_t)b[i]);
}

static inline void v_simd_min_u16(const uint16_t *a, const uint16_t *b, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_PICK(v_simd_u16x4, v_simd_u16x4, vy < vx)
	case 8: V_SIMD_PICK(v_simd_u16x8, v_simd_u16x8, vy < vx)
	case 16: V_SIMD_PICK(v_simd_u16x16, v_simd_u16x16, vy < vx)
	case 32: V_SIMD_PICK(v_simd_u16x32, v_simd_u16x32, vy < vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] < a[i] ? b[i] : a[i];
}

static inline void v_simd_max_u16(const uint16_t *a, const uint16_t *b, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_PICK(v_simd_u16x4, v_simd_u16x4, vy > vx)
	case 8: V_SIMD_PICK(v_simd_u16x8, v_simd_u16x8, vy > vx)
	case 16: V_SIMD_PICK(v_simd_u16x16, v_simd_u16x16, vy > vx)
	case 32: V_SIMD_PICK(v_simd_u16x32, v_simd_u16x32, vy > vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] > a[i] ? b[i] : a[i];
}

static inline void v_simd_and_u16(const uint16_t *a, const uint16_t *b, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx & vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx & vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx & vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx & vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint16_t)(a[i] & b[i]);
}

static inline void v_simd_or_u16(const uint16_t *a, const uint16_t *b, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx | vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx | vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx | vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx | vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint16_t)(a[i] | b[i]);
}

static inline void v_simd_xor_u16(const uint16_t *a, const uint16_t *b, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_BIN(v_simd_u16x4, vx ^ vy)
	case 8: V_SIMD_BIN(v_simd_u16x8, vx ^ vy)
	case 16: V_SIMD_BIN(v_simd_u16x16, vx ^ vy)
	case 32: V_SIMD_BIN(v_simd_u16x32, vx ^ vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint16_t)(a[i] ^ b[i]);
}

static inline void v_simd_not_u16(const uint16_t *a, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_UN(v_simd_u16x4, ~vx)
	case 8: V_SIMD_UN(v_simd_u16x8, ~vx)
	case 16: V_SIMD_UN(v_simd_u16x16, ~vx)
	case 32: V_SIMD_UN(v_simd_u16x32, ~vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint16_t)~a[i];
}

static inline void v_simd_shl_u16(const uint16_t *a, unsigned count, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_UN(v_simd_u16x4, vx << (uint16_t)count)
	case 8: V_SIMD_UN(v_simd_u16x8, vx << (uint16_t)count)
	case 16: V_SIMD_UN(v_simd_u16x16, vx << (uint16_t)count)
	case 32: V_SIMD_UN(v_simd_u16x32, vx << (uint16_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint16_t)((uint32_t)a[i] << count);
}

static inline void v_simd_shr_u16(const uint16_t *a, unsigned count, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_UN(v_simd_u16x4, vx >> (uint16_t)count)
	case 8: V_SIMD_UN(v_simd_u16x8, vx >> (uint16_t)count)
	case 16: V_SIMD_UN(v_simd_u16x16, vx >> (uint16_t)count)
	case 32: V_SIMD_UN(v_simd_u16x32, vx >> (uint16_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint16_t)(a[i] >> count);
}

static inline void v_simd_eq_u16(const uint16_t *a, const uint16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_CMP(v_simd_u16x4, v_simd_i16x4, vx == vy)
	case 8: V_SIMD_CMP(v_simd_u16x8, v_simd_i16x8, vx == vy)
	case 16: V_SIMD_CMP(v_simd_u16x16, v_simd_i16x16, vx == vy)
	case 32: V_SIMD_CMP(v_simd_u16x32, v_simd_i16x32, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_u16(const uint16_t *a, const uint16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_CMP(v_simd_u16x4, v_simd_i16x4, vx != vy)
	case 8: V_SIMD_CMP(v_simd_u16x8, v_simd_i16x8, vx != vy)
	case 16: V_SIMD_CMP(v_simd_u16x16, v_simd_i16x16, vx != vy)
	case 32: V_SIMD_CMP(v_simd_u16x32, v_simd_i16x32, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_u16(const uint16_t *a, const uint16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_CMP(v_simd_u16x4, v_simd_i16x4, vx < vy)
	case 8: V_SIMD_CMP(v_simd_u16x8, v_simd_i16x8, vx < vy)
	case 16: V_SIMD_CMP(v_simd_u16x16, v_simd_i16x16, vx < vy)
	case 32: V_SIMD_CMP(v_simd_u16x32, v_simd_i16x32, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)-(a[i] < b[i]);
}

static inline void v_simd_le_u16(const uint16_t *a, const uint16_t *b, int16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_CMP(v_simd_u16x4, v_simd_i16x4, vx <= vy)
	case 8: V_SIMD_CMP(v_simd_u16x8, v_simd_i16x8, vx <= vy)
	case 16: V_SIMD_CMP(v_simd_u16x16, v_simd_i16x16, vx <= vy)
	case 32: V_SIMD_CMP(v_simd_u16x32, v_simd_i16x32, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int16_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_u16(const int16_t *m, const uint16_t *a, const uint16_t *b, uint16_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 4: V_SIMD_SEL(v_simd_u16x4, v_simd_i16x4)
	case 8: V_SIMD_SEL(v_simd_u16x8, v_simd_i16x8)
	case 16: V_SIMD_SEL(v_simd_u16x16, v_simd_i16x16)
	case 32: V_SIMD_SEL(v_simd_u16x32, v_simd_i16x32)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

static inline void v_simd_add_u32(const uint32_t *a, const uint32_t *b, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx + vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx + vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx + vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint32_t)((uint32_t)a[i] + (uint32_t)b[i]);
}

static inline void v_simd_sub_u32(const uint32_t *a, const uint32_t *b, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx - vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx - vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx - vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint32_t)((uint32_t)a[i] - (uint32_t)b[i]);
}

static inline void v_simd_mul_u32(const uint32_t *a, const uint32_t *b, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx * vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx * vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx * vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint32_t)((uint32_t)a[i] * (uint32_t)b[i]);
}

static inline void v_simd_min_u32(const uint32_t *a, const uint32_t *b, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_u32x2, v_simd_u32x2, vy < vx)
	case 4: V_SIMD_PICK(v_simd_u32x4, v_simd_u32x4, vy < vx)
	case 8: V_SIMD_PICK(v_simd_u32x8, v_simd_u32x8, vy < vx)
	case 16: V_SIMD_PICK(v_simd_u32x16, v_simd_u32x16, vy < vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] < a[i] ? b[i] : a[i];
}

static inline void v_simd_max_u32(const uint32_t *a, const uint32_t *b, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_u32x2, v_simd_u32x2, vy > vx)
	case 4: V_SIMD_PICK(v_simd_u32x4, v_simd_u32x4, vy > vx)
	case 8: V_SIMD_PICK(v_simd_u32x8, v_simd_u32x8, vy > vx)
	case 16: V_SIMD_PICK(v_simd_u32x16, v_simd_u32x16, vy > vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] > a[i] ? b[i] : a[i];
}

static inline void v_simd_and_u32(const uint32_t *a, const uint32_t *b, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx & vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx & vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx & vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx & vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint32_t)(a[i] & b[i]);
}

static inline void v_simd_or_u32(const uint32_t *a, const uint32_t *b, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx | vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx | vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx | vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx | vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint32_t)(a[i] | b[i]);
}

static inline void v_simd_xor_u32(const uint32_t *a, const uint32_t *b, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u32x2, vx ^ vy)
	case 4: V_SIMD_BIN(v_simd_u32x4, vx ^ vy)
	case 8: V_SIMD_BIN(v_simd_u32x8, vx ^ vy)
	case 16: V_SIMD_BIN(v_simd_u32x16, vx ^ vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint32_t)(a[i] ^ b[i]);
}

static inline void v_simd_not_u32(const uint32_t *a, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u32x2, ~vx)
	case 4: V_SIMD_UN(v_simd_u32x4, ~vx)
	case 8: V_SIMD_UN(v_simd_u32x8, ~vx)
	case 16: V_SIMD_UN(v_simd_u32x16, ~vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint32_t)~a[i];
}

static inline void v_simd_shl_u32(const uint32_t *a, unsigned count, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u32x2, vx << (uint32_t)count)
	case 4: V_SIMD_UN(v_simd_u32x4, vx << (uint32_t)count)
	case 8: V_SIMD_UN(v_simd_u32x8, vx << (uint32_t)count)
	case 16: V_SIMD_UN(v_simd_u32x16, vx << (uint32_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint32_t)((uint32_t)a[i] << count);
}

static inline void v_simd_shr_u32(const uint32_t *a, unsigned count, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u32x2, vx >> (uint32_t)count)
	case 4: V_SIMD_UN(v_simd_u32x4, vx >> (uint32_t)count)
	case 8: V_SIMD_UN(v_simd_u32x8, vx >> (uint32_t)count)
	case 16: V_SIMD_UN(v_simd_u32x16, vx >> (uint32_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint32_t)(a[i] >> count);
}

static inline void v_simd_eq_u32(const uint32_t *a, const uint32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_u32x2, v_simd_i32x2, vx == vy)
	case 4: V_SIMD_CMP(v_simd_u32x4, v_simd_i32x4, vx == vy)
	case 8: V_SIMD_CMP(v_simd_u32x8, v_simd_i32x8, vx == vy)
	case 16: V_SIMD_CMP(v_simd_u32x16, v_simd_i32x16, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_u32(const uint32_t *a, const uint32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_u32x2, v_simd_i32x2, vx != vy)
	case 4: V_SIMD_CMP(v_simd_u32x4, v_simd_i32x4, vx != vy)
	case 8: V_SIMD_CMP(v_simd_u32x8, v_simd_i32x8, vx != vy)
	case 16: V_SIMD_CMP(v_simd_u32x16, v_simd_i32x16, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_u32(const uint32_t *a, const uint32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_u32x2, v_simd_i32x2, vx < vy)
	case 4: V_SIMD_CMP(v_simd_u32x4, v_simd_i32x4, vx < vy)
	case 8: V_SIMD_CMP(v_simd_u32x8, v_simd_i32x8, vx < vy)
	case 16: V_SIMD_CMP(v_simd_u32x16, v_simd_i32x16, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] < b[i]);
}

static inline void v_simd_le_u32(const uint32_t *a, const uint32_t *b, int32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_u32x2, v_simd_i32x2, vx <= vy)
	case 4: V_SIMD_CMP(v_simd_u32x4, v_simd_i32x4, vx <= vy)
	case 8: V_SIMD_CMP(v_simd_u32x8, v_simd_i32x8, vx <= vy)
	case 16: V_SIMD_CMP(v_simd_u32x16, v_simd_i32x16, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int32_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_u32(const int32_t *m, const uint32_t *a, const uint32_t *b, uint32_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_SEL(v_simd_u32x2, v_simd_i32x2)
	case 4: V_SIMD_SEL(v_simd_u32x4, v_simd_i32x4)
	case 8: V_SIMD_SEL(v_simd_u32x8, v_simd_i32x8)
	case 16: V_SIMD_SEL(v_simd_u32x16, v_simd_i32x16)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

static inline void v_simd_add_u64(const uint64_t *a, const uint64_t *b, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx + vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx + vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx + vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint64_t)((uint64_t)a[i] + (uint64_t)b[i]);
}

static inline void v_simd_sub_u64(const uint64_t *a, const uint64_t *b, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx - vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx - vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx - vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint64_t)((uint64_t)a[i] - (uint64_t)b[i]);
}

static inline void v_simd_mul_u64(const uint64_t *a, const uint64_t *b, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx * vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx * vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx * vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint64_t)((uint64_t)a[i] * (uint64_t)b[i]);
}

static inline void v_simd_min_u64(const uint64_t *a, const uint64_t *b, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_u64x2, v_simd_u64x2, vy < vx)
	case 4: V_SIMD_PICK(v_simd_u64x4, v_simd_u64x4, vy < vx)
	case 8: V_SIMD_PICK(v_simd_u64x8, v_simd_u64x8, vy < vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] < a[i] ? b[i] : a[i];
}

static inline void v_simd_max_u64(const uint64_t *a, const uint64_t *b, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_PICK(v_simd_u64x2, v_simd_u64x2, vy > vx)
	case 4: V_SIMD_PICK(v_simd_u64x4, v_simd_u64x4, vy > vx)
	case 8: V_SIMD_PICK(v_simd_u64x8, v_simd_u64x8, vy > vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = b[i] > a[i] ? b[i] : a[i];
}

static inline void v_simd_and_u64(const uint64_t *a, const uint64_t *b, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx & vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx & vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx & vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint64_t)(a[i] & b[i]);
}

static inline void v_simd_or_u64(const uint64_t *a, const uint64_t *b, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx | vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx | vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx | vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint64_t)(a[i] | b[i]);
}

static inline void v_simd_xor_u64(const uint64_t *a, const uint64_t *b, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_BIN(v_simd_u64x2, vx ^ vy)
	case 4: V_SIMD_BIN(v_simd_u64x4, vx ^ vy)
	case 8: V_SIMD_BIN(v_simd_u64x8, vx ^ vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint64_t)(a[i] ^ b[i]);
}

static inline void v_simd_not_u64(const uint64_t *a, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u64x2, ~vx)
	case 4: V_SIMD_UN(v_simd_u64x4, ~vx)
	case 8: V_SIMD_UN(v_simd_u64x8, ~vx)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint64_t)~a[i];
}

static inline void v_simd_shl_u64(const uint64_t *a, unsigned count, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u64x2, vx << (uint64_t)count)
	case 4: V_SIMD_UN(v_simd_u64x4, vx << (uint64_t)count)
	case 8: V_SIMD_UN(v_simd_u64x8, vx << (uint64_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint64_t)((uint64_t)a[i] << count);
}

static inline void v_simd_shr_u64(const uint64_t *a, unsigned count, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_UN(v_simd_u64x2, vx >> (uint64_t)count)
	case 4: V_SIMD_UN(v_simd_u64x4, vx >> (uint64_t)count)
	case 8: V_SIMD_UN(v_simd_u64x8, vx >> (uint64_t)count)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (uint64_t)(a[i] >> count);
}

static inline void v_simd_eq_u64(const uint64_t *a, const uint64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_u64x2, v_simd_i64x2, vx == vy)
	case 4: V_SIMD_CMP(v_simd_u64x4, v_simd_i64x4, vx == vy)
	case 8: V_SIMD_CMP(v_simd_u64x8, v_simd_i64x8, vx == vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] == b[i]);
}

static inline void v_simd_ne_u64(const uint64_t *a, const uint64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_u64x2, v_simd_i64x2, vx != vy)
	case 4: V_SIMD_CMP(v_simd_u64x4, v_simd_i64x4, vx != vy)
	case 8: V_SIMD_CMP(v_simd_u64x8, v_simd_i64x8, vx != vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] != b[i]);
}

static inline void v_simd_lt_u64(const uint64_t *a, const uint64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_u64x2, v_simd_i64x2, vx < vy)
	case 4: V_SIMD_CMP(v_simd_u64x4, v_simd_i64x4, vx < vy)
	case 8: V_SIMD_CMP(v_simd_u64x8, v_simd_i64x8, vx < vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] < b[i]);
}

static inline void v_simd_le_u64(const uint64_t *a, const uint64_t *b, int64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_CMP(v_simd_u64x2, v_simd_i64x2, vx <= vy)
	case 4: V_SIMD_CMP(v_simd_u64x4, v_simd_i64x4, vx <= vy)
	case 8: V_SIMD_CMP(v_simd_u64x8, v_simd_i64x8, vx <= vy)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = (int64_t)-(a[i] <= b[i]);
}

static inline void v_simd_select_u64(const int64_t *m, const uint64_t *a, const uint64_t *b, uint64_t *out, int n) {
#if defined(V_SIMD_VECTOR_EXT)
	switch (n) {
	case 2: V_SIMD_SEL(v_simd_u64x2, v_simd_i64x2)
	case 4: V_SIMD_SEL(v_simd_u64x4, v_simd_i64x4)
	case 8: V_SIMD_SEL(v_simd_u64x8, v_simd_i64x8)
	default: break;
	}
#endif
	for (int i = 0; i < n; i++) out[i] = m[i] ? a[i] : b[i];
}

#endif
