// Code generated by vlib/simd/gen.vsh; DO NOT EDIT.
// Regenerate with: v run vlib/simd/gen.vsh
module simd

fn C.v_simd_add_f32(const_a &f32, const_b &f32, out &f32, n int)

fn native_add_f32(a &f32, b &f32, out &f32, n int) {
	C.v_simd_add_f32(a, b, out, n)
}

fn C.v_simd_sub_f32(const_a &f32, const_b &f32, out &f32, n int)

fn native_sub_f32(a &f32, b &f32, out &f32, n int) {
	C.v_simd_sub_f32(a, b, out, n)
}

fn C.v_simd_mul_f32(const_a &f32, const_b &f32, out &f32, n int)

fn native_mul_f32(a &f32, b &f32, out &f32, n int) {
	C.v_simd_mul_f32(a, b, out, n)
}

fn C.v_simd_div_f32(const_a &f32, const_b &f32, out &f32, n int)

fn native_div_f32(a &f32, b &f32, out &f32, n int) {
	C.v_simd_div_f32(a, b, out, n)
}

fn C.v_simd_neg_f32(const_a &f32, out &f32, n int)

fn native_neg_f32(a &f32, out &f32, n int) {
	C.v_simd_neg_f32(a, out, n)
}

fn C.v_simd_abs_f32(const_a &f32, out &f32, n int)

fn native_abs_f32(a &f32, out &f32, n int) {
	C.v_simd_abs_f32(a, out, n)
}

fn C.v_simd_min_f32(const_a &f32, const_b &f32, out &f32, n int)

fn native_min_f32(a &f32, b &f32, out &f32, n int) {
	C.v_simd_min_f32(a, b, out, n)
}

fn C.v_simd_max_f32(const_a &f32, const_b &f32, out &f32, n int)

fn native_max_f32(a &f32, b &f32, out &f32, n int) {
	C.v_simd_max_f32(a, b, out, n)
}

fn C.v_simd_sqrt_f32(const_a &f32, out &f32, n int)

fn native_sqrt_f32(a &f32, out &f32, n int) {
	C.v_simd_sqrt_f32(a, out, n)
}

fn C.v_simd_eq_f32(const_a &f32, const_b &f32, out &i32, n int)

fn native_eq_f32(a &f32, b &f32, out &i32, n int) {
	C.v_simd_eq_f32(a, b, out, n)
}

fn C.v_simd_ne_f32(const_a &f32, const_b &f32, out &i32, n int)

fn native_ne_f32(a &f32, b &f32, out &i32, n int) {
	C.v_simd_ne_f32(a, b, out, n)
}

fn C.v_simd_lt_f32(const_a &f32, const_b &f32, out &i32, n int)

fn native_lt_f32(a &f32, b &f32, out &i32, n int) {
	C.v_simd_lt_f32(a, b, out, n)
}

fn C.v_simd_le_f32(const_a &f32, const_b &f32, out &i32, n int)

fn native_le_f32(a &f32, b &f32, out &i32, n int) {
	C.v_simd_le_f32(a, b, out, n)
}

fn C.v_simd_select_f32(const_m &i32, const_a &f32, const_b &f32, out &f32, n int)

fn native_select_f32(m &i32, a &f32, b &f32, out &f32, n int) {
	C.v_simd_select_f32(m, a, b, out, n)
}

fn C.v_simd_add_f64(const_a &f64, const_b &f64, out &f64, n int)

fn native_add_f64(a &f64, b &f64, out &f64, n int) {
	C.v_simd_add_f64(a, b, out, n)
}

fn C.v_simd_sub_f64(const_a &f64, const_b &f64, out &f64, n int)

fn native_sub_f64(a &f64, b &f64, out &f64, n int) {
	C.v_simd_sub_f64(a, b, out, n)
}

fn C.v_simd_mul_f64(const_a &f64, const_b &f64, out &f64, n int)

fn native_mul_f64(a &f64, b &f64, out &f64, n int) {
	C.v_simd_mul_f64(a, b, out, n)
}

fn C.v_simd_div_f64(const_a &f64, const_b &f64, out &f64, n int)

fn native_div_f64(a &f64, b &f64, out &f64, n int) {
	C.v_simd_div_f64(a, b, out, n)
}

fn C.v_simd_neg_f64(const_a &f64, out &f64, n int)

fn native_neg_f64(a &f64, out &f64, n int) {
	C.v_simd_neg_f64(a, out, n)
}

fn C.v_simd_abs_f64(const_a &f64, out &f64, n int)

fn native_abs_f64(a &f64, out &f64, n int) {
	C.v_simd_abs_f64(a, out, n)
}

fn C.v_simd_min_f64(const_a &f64, const_b &f64, out &f64, n int)

fn native_min_f64(a &f64, b &f64, out &f64, n int) {
	C.v_simd_min_f64(a, b, out, n)
}

fn C.v_simd_max_f64(const_a &f64, const_b &f64, out &f64, n int)

fn native_max_f64(a &f64, b &f64, out &f64, n int) {
	C.v_simd_max_f64(a, b, out, n)
}

fn C.v_simd_sqrt_f64(const_a &f64, out &f64, n int)

fn native_sqrt_f64(a &f64, out &f64, n int) {
	C.v_simd_sqrt_f64(a, out, n)
}

fn C.v_simd_eq_f64(const_a &f64, const_b &f64, out &i64, n int)

fn native_eq_f64(a &f64, b &f64, out &i64, n int) {
	C.v_simd_eq_f64(a, b, out, n)
}

fn C.v_simd_ne_f64(const_a &f64, const_b &f64, out &i64, n int)

fn native_ne_f64(a &f64, b &f64, out &i64, n int) {
	C.v_simd_ne_f64(a, b, out, n)
}

fn C.v_simd_lt_f64(const_a &f64, const_b &f64, out &i64, n int)

fn native_lt_f64(a &f64, b &f64, out &i64, n int) {
	C.v_simd_lt_f64(a, b, out, n)
}

fn C.v_simd_le_f64(const_a &f64, const_b &f64, out &i64, n int)

fn native_le_f64(a &f64, b &f64, out &i64, n int) {
	C.v_simd_le_f64(a, b, out, n)
}

fn C.v_simd_select_f64(const_m &i64, const_a &f64, const_b &f64, out &f64, n int)

fn native_select_f64(m &i64, a &f64, b &f64, out &f64, n int) {
	C.v_simd_select_f64(m, a, b, out, n)
}

fn C.v_simd_add_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_add_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_add_i8(a, b, out, n)
}

fn C.v_simd_sub_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_sub_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_sub_i8(a, b, out, n)
}

fn C.v_simd_mul_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_mul_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_mul_i8(a, b, out, n)
}

fn C.v_simd_min_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_min_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_min_i8(a, b, out, n)
}

fn C.v_simd_max_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_max_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_max_i8(a, b, out, n)
}

fn C.v_simd_and_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_and_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_and_i8(a, b, out, n)
}

fn C.v_simd_or_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_or_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_or_i8(a, b, out, n)
}

fn C.v_simd_xor_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_xor_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_xor_i8(a, b, out, n)
}

fn C.v_simd_not_i8(const_a &i8, out &i8, n int)

fn native_not_i8(a &i8, out &i8, n int) {
	C.v_simd_not_i8(a, out, n)
}

fn C.v_simd_shl_i8(const_a &i8, count u32, out &i8, n int)

fn native_shl_i8(a &i8, count u32, out &i8, n int) {
	C.v_simd_shl_i8(a, count, out, n)
}

fn C.v_simd_shr_i8(const_a &i8, count u32, out &i8, n int)

fn native_shr_i8(a &i8, count u32, out &i8, n int) {
	C.v_simd_shr_i8(a, count, out, n)
}

fn C.v_simd_neg_i8(const_a &i8, out &i8, n int)

fn native_neg_i8(a &i8, out &i8, n int) {
	C.v_simd_neg_i8(a, out, n)
}

fn C.v_simd_abs_i8(const_a &i8, out &i8, n int)

fn native_abs_i8(a &i8, out &i8, n int) {
	C.v_simd_abs_i8(a, out, n)
}

fn C.v_simd_eq_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_eq_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_eq_i8(a, b, out, n)
}

fn C.v_simd_ne_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_ne_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_ne_i8(a, b, out, n)
}

fn C.v_simd_lt_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_lt_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_lt_i8(a, b, out, n)
}

fn C.v_simd_le_i8(const_a &i8, const_b &i8, out &i8, n int)

fn native_le_i8(a &i8, b &i8, out &i8, n int) {
	C.v_simd_le_i8(a, b, out, n)
}

fn C.v_simd_select_i8(const_m &i8, const_a &i8, const_b &i8, out &i8, n int)

fn native_select_i8(m &i8, a &i8, b &i8, out &i8, n int) {
	C.v_simd_select_i8(m, a, b, out, n)
}

fn C.v_simd_add_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_add_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_add_i16(a, b, out, n)
}

fn C.v_simd_sub_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_sub_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_sub_i16(a, b, out, n)
}

fn C.v_simd_mul_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_mul_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_mul_i16(a, b, out, n)
}

fn C.v_simd_min_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_min_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_min_i16(a, b, out, n)
}

fn C.v_simd_max_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_max_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_max_i16(a, b, out, n)
}

fn C.v_simd_and_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_and_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_and_i16(a, b, out, n)
}

fn C.v_simd_or_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_or_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_or_i16(a, b, out, n)
}

fn C.v_simd_xor_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_xor_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_xor_i16(a, b, out, n)
}

fn C.v_simd_not_i16(const_a &i16, out &i16, n int)

fn native_not_i16(a &i16, out &i16, n int) {
	C.v_simd_not_i16(a, out, n)
}

fn C.v_simd_shl_i16(const_a &i16, count u32, out &i16, n int)

fn native_shl_i16(a &i16, count u32, out &i16, n int) {
	C.v_simd_shl_i16(a, count, out, n)
}

fn C.v_simd_shr_i16(const_a &i16, count u32, out &i16, n int)

fn native_shr_i16(a &i16, count u32, out &i16, n int) {
	C.v_simd_shr_i16(a, count, out, n)
}

fn C.v_simd_neg_i16(const_a &i16, out &i16, n int)

fn native_neg_i16(a &i16, out &i16, n int) {
	C.v_simd_neg_i16(a, out, n)
}

fn C.v_simd_abs_i16(const_a &i16, out &i16, n int)

fn native_abs_i16(a &i16, out &i16, n int) {
	C.v_simd_abs_i16(a, out, n)
}

fn C.v_simd_eq_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_eq_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_eq_i16(a, b, out, n)
}

fn C.v_simd_ne_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_ne_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_ne_i16(a, b, out, n)
}

fn C.v_simd_lt_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_lt_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_lt_i16(a, b, out, n)
}

fn C.v_simd_le_i16(const_a &i16, const_b &i16, out &i16, n int)

fn native_le_i16(a &i16, b &i16, out &i16, n int) {
	C.v_simd_le_i16(a, b, out, n)
}

fn C.v_simd_select_i16(const_m &i16, const_a &i16, const_b &i16, out &i16, n int)

fn native_select_i16(m &i16, a &i16, b &i16, out &i16, n int) {
	C.v_simd_select_i16(m, a, b, out, n)
}

fn C.v_simd_add_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_add_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_add_i32(a, b, out, n)
}

fn C.v_simd_sub_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_sub_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_sub_i32(a, b, out, n)
}

fn C.v_simd_mul_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_mul_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_mul_i32(a, b, out, n)
}

fn C.v_simd_min_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_min_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_min_i32(a, b, out, n)
}

fn C.v_simd_max_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_max_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_max_i32(a, b, out, n)
}

fn C.v_simd_and_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_and_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_and_i32(a, b, out, n)
}

fn C.v_simd_or_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_or_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_or_i32(a, b, out, n)
}

fn C.v_simd_xor_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_xor_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_xor_i32(a, b, out, n)
}

fn C.v_simd_not_i32(const_a &i32, out &i32, n int)

fn native_not_i32(a &i32, out &i32, n int) {
	C.v_simd_not_i32(a, out, n)
}

fn C.v_simd_shl_i32(const_a &i32, count u32, out &i32, n int)

fn native_shl_i32(a &i32, count u32, out &i32, n int) {
	C.v_simd_shl_i32(a, count, out, n)
}

fn C.v_simd_shr_i32(const_a &i32, count u32, out &i32, n int)

fn native_shr_i32(a &i32, count u32, out &i32, n int) {
	C.v_simd_shr_i32(a, count, out, n)
}

fn C.v_simd_neg_i32(const_a &i32, out &i32, n int)

fn native_neg_i32(a &i32, out &i32, n int) {
	C.v_simd_neg_i32(a, out, n)
}

fn C.v_simd_abs_i32(const_a &i32, out &i32, n int)

fn native_abs_i32(a &i32, out &i32, n int) {
	C.v_simd_abs_i32(a, out, n)
}

fn C.v_simd_eq_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_eq_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_eq_i32(a, b, out, n)
}

fn C.v_simd_ne_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_ne_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_ne_i32(a, b, out, n)
}

fn C.v_simd_lt_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_lt_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_lt_i32(a, b, out, n)
}

fn C.v_simd_le_i32(const_a &i32, const_b &i32, out &i32, n int)

fn native_le_i32(a &i32, b &i32, out &i32, n int) {
	C.v_simd_le_i32(a, b, out, n)
}

fn C.v_simd_select_i32(const_m &i32, const_a &i32, const_b &i32, out &i32, n int)

fn native_select_i32(m &i32, a &i32, b &i32, out &i32, n int) {
	C.v_simd_select_i32(m, a, b, out, n)
}

fn C.v_simd_add_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_add_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_add_i64(a, b, out, n)
}

fn C.v_simd_sub_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_sub_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_sub_i64(a, b, out, n)
}

fn C.v_simd_mul_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_mul_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_mul_i64(a, b, out, n)
}

fn C.v_simd_min_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_min_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_min_i64(a, b, out, n)
}

fn C.v_simd_max_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_max_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_max_i64(a, b, out, n)
}

fn C.v_simd_and_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_and_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_and_i64(a, b, out, n)
}

fn C.v_simd_or_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_or_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_or_i64(a, b, out, n)
}

fn C.v_simd_xor_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_xor_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_xor_i64(a, b, out, n)
}

fn C.v_simd_not_i64(const_a &i64, out &i64, n int)

fn native_not_i64(a &i64, out &i64, n int) {
	C.v_simd_not_i64(a, out, n)
}

fn C.v_simd_shl_i64(const_a &i64, count u32, out &i64, n int)

fn native_shl_i64(a &i64, count u32, out &i64, n int) {
	C.v_simd_shl_i64(a, count, out, n)
}

fn C.v_simd_shr_i64(const_a &i64, count u32, out &i64, n int)

fn native_shr_i64(a &i64, count u32, out &i64, n int) {
	C.v_simd_shr_i64(a, count, out, n)
}

fn C.v_simd_neg_i64(const_a &i64, out &i64, n int)

fn native_neg_i64(a &i64, out &i64, n int) {
	C.v_simd_neg_i64(a, out, n)
}

fn C.v_simd_abs_i64(const_a &i64, out &i64, n int)

fn native_abs_i64(a &i64, out &i64, n int) {
	C.v_simd_abs_i64(a, out, n)
}

fn C.v_simd_eq_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_eq_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_eq_i64(a, b, out, n)
}

fn C.v_simd_ne_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_ne_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_ne_i64(a, b, out, n)
}

fn C.v_simd_lt_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_lt_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_lt_i64(a, b, out, n)
}

fn C.v_simd_le_i64(const_a &i64, const_b &i64, out &i64, n int)

fn native_le_i64(a &i64, b &i64, out &i64, n int) {
	C.v_simd_le_i64(a, b, out, n)
}

fn C.v_simd_select_i64(const_m &i64, const_a &i64, const_b &i64, out &i64, n int)

fn native_select_i64(m &i64, a &i64, b &i64, out &i64, n int) {
	C.v_simd_select_i64(m, a, b, out, n)
}

fn C.v_simd_add_u8(const_a &u8, const_b &u8, out &u8, n int)

fn native_add_u8(a &u8, b &u8, out &u8, n int) {
	C.v_simd_add_u8(a, b, out, n)
}

fn C.v_simd_sub_u8(const_a &u8, const_b &u8, out &u8, n int)

fn native_sub_u8(a &u8, b &u8, out &u8, n int) {
	C.v_simd_sub_u8(a, b, out, n)
}

fn C.v_simd_mul_u8(const_a &u8, const_b &u8, out &u8, n int)

fn native_mul_u8(a &u8, b &u8, out &u8, n int) {
	C.v_simd_mul_u8(a, b, out, n)
}

fn C.v_simd_min_u8(const_a &u8, const_b &u8, out &u8, n int)

fn native_min_u8(a &u8, b &u8, out &u8, n int) {
	C.v_simd_min_u8(a, b, out, n)
}

fn C.v_simd_max_u8(const_a &u8, const_b &u8, out &u8, n int)

fn native_max_u8(a &u8, b &u8, out &u8, n int) {
	C.v_simd_max_u8(a, b, out, n)
}

fn C.v_simd_and_u8(const_a &u8, const_b &u8, out &u8, n int)

fn native_and_u8(a &u8, b &u8, out &u8, n int) {
	C.v_simd_and_u8(a, b, out, n)
}

fn C.v_simd_or_u8(const_a &u8, const_b &u8, out &u8, n int)

fn native_or_u8(a &u8, b &u8, out &u8, n int) {
	C.v_simd_or_u8(a, b, out, n)
}

fn C.v_simd_xor_u8(const_a &u8, const_b &u8, out &u8, n int)

fn native_xor_u8(a &u8, b &u8, out &u8, n int) {
	C.v_simd_xor_u8(a, b, out, n)
}

fn C.v_simd_not_u8(const_a &u8, out &u8, n int)

fn native_not_u8(a &u8, out &u8, n int) {
	C.v_simd_not_u8(a, out, n)
}

fn C.v_simd_shl_u8(const_a &u8, count u32, out &u8, n int)

fn native_shl_u8(a &u8, count u32, out &u8, n int) {
	C.v_simd_shl_u8(a, count, out, n)
}

fn C.v_simd_shr_u8(const_a &u8, count u32, out &u8, n int)

fn native_shr_u8(a &u8, count u32, out &u8, n int) {
	C.v_simd_shr_u8(a, count, out, n)
}

fn C.v_simd_eq_u8(const_a &u8, const_b &u8, out &i8, n int)

fn native_eq_u8(a &u8, b &u8, out &i8, n int) {
	C.v_simd_eq_u8(a, b, out, n)
}

fn C.v_simd_ne_u8(const_a &u8, const_b &u8, out &i8, n int)

fn native_ne_u8(a &u8, b &u8, out &i8, n int) {
	C.v_simd_ne_u8(a, b, out, n)
}

fn C.v_simd_lt_u8(const_a &u8, const_b &u8, out &i8, n int)

fn native_lt_u8(a &u8, b &u8, out &i8, n int) {
	C.v_simd_lt_u8(a, b, out, n)
}

fn C.v_simd_le_u8(const_a &u8, const_b &u8, out &i8, n int)

fn native_le_u8(a &u8, b &u8, out &i8, n int) {
	C.v_simd_le_u8(a, b, out, n)
}

fn C.v_simd_select_u8(const_m &i8, const_a &u8, const_b &u8, out &u8, n int)

fn native_select_u8(m &i8, a &u8, b &u8, out &u8, n int) {
	C.v_simd_select_u8(m, a, b, out, n)
}

fn C.v_simd_add_u16(const_a &u16, const_b &u16, out &u16, n int)

fn native_add_u16(a &u16, b &u16, out &u16, n int) {
	C.v_simd_add_u16(a, b, out, n)
}

fn C.v_simd_sub_u16(const_a &u16, const_b &u16, out &u16, n int)

fn native_sub_u16(a &u16, b &u16, out &u16, n int) {
	C.v_simd_sub_u16(a, b, out, n)
}

fn C.v_simd_mul_u16(const_a &u16, const_b &u16, out &u16, n int)

fn native_mul_u16(a &u16, b &u16, out &u16, n int) {
	C.v_simd_mul_u16(a, b, out, n)
}

fn C.v_simd_min_u16(const_a &u16, const_b &u16, out &u16, n int)

fn native_min_u16(a &u16, b &u16, out &u16, n int) {
	C.v_simd_min_u16(a, b, out, n)
}

fn C.v_simd_max_u16(const_a &u16, const_b &u16, out &u16, n int)

fn native_max_u16(a &u16, b &u16, out &u16, n int) {
	C.v_simd_max_u16(a, b, out, n)
}

fn C.v_simd_and_u16(const_a &u16, const_b &u16, out &u16, n int)

fn native_and_u16(a &u16, b &u16, out &u16, n int) {
	C.v_simd_and_u16(a, b, out, n)
}

fn C.v_simd_or_u16(const_a &u16, const_b &u16, out &u16, n int)

fn native_or_u16(a &u16, b &u16, out &u16, n int) {
	C.v_simd_or_u16(a, b, out, n)
}

fn C.v_simd_xor_u16(const_a &u16, const_b &u16, out &u16, n int)

fn native_xor_u16(a &u16, b &u16, out &u16, n int) {
	C.v_simd_xor_u16(a, b, out, n)
}

fn C.v_simd_not_u16(const_a &u16, out &u16, n int)

fn native_not_u16(a &u16, out &u16, n int) {
	C.v_simd_not_u16(a, out, n)
}

fn C.v_simd_shl_u16(const_a &u16, count u32, out &u16, n int)

fn native_shl_u16(a &u16, count u32, out &u16, n int) {
	C.v_simd_shl_u16(a, count, out, n)
}

fn C.v_simd_shr_u16(const_a &u16, count u32, out &u16, n int)

fn native_shr_u16(a &u16, count u32, out &u16, n int) {
	C.v_simd_shr_u16(a, count, out, n)
}

fn C.v_simd_eq_u16(const_a &u16, const_b &u16, out &i16, n int)

fn native_eq_u16(a &u16, b &u16, out &i16, n int) {
	C.v_simd_eq_u16(a, b, out, n)
}

fn C.v_simd_ne_u16(const_a &u16, const_b &u16, out &i16, n int)

fn native_ne_u16(a &u16, b &u16, out &i16, n int) {
	C.v_simd_ne_u16(a, b, out, n)
}

fn C.v_simd_lt_u16(const_a &u16, const_b &u16, out &i16, n int)

fn native_lt_u16(a &u16, b &u16, out &i16, n int) {
	C.v_simd_lt_u16(a, b, out, n)
}

fn C.v_simd_le_u16(const_a &u16, const_b &u16, out &i16, n int)

fn native_le_u16(a &u16, b &u16, out &i16, n int) {
	C.v_simd_le_u16(a, b, out, n)
}

fn C.v_simd_select_u16(const_m &i16, const_a &u16, const_b &u16, out &u16, n int)

fn native_select_u16(m &i16, a &u16, b &u16, out &u16, n int) {
	C.v_simd_select_u16(m, a, b, out, n)
}

fn C.v_simd_add_u32(const_a &u32, const_b &u32, out &u32, n int)

fn native_add_u32(a &u32, b &u32, out &u32, n int) {
	C.v_simd_add_u32(a, b, out, n)
}

fn C.v_simd_sub_u32(const_a &u32, const_b &u32, out &u32, n int)

fn native_sub_u32(a &u32, b &u32, out &u32, n int) {
	C.v_simd_sub_u32(a, b, out, n)
}

fn C.v_simd_mul_u32(const_a &u32, const_b &u32, out &u32, n int)

fn native_mul_u32(a &u32, b &u32, out &u32, n int) {
	C.v_simd_mul_u32(a, b, out, n)
}

fn C.v_simd_min_u32(const_a &u32, const_b &u32, out &u32, n int)

fn native_min_u32(a &u32, b &u32, out &u32, n int) {
	C.v_simd_min_u32(a, b, out, n)
}

fn C.v_simd_max_u32(const_a &u32, const_b &u32, out &u32, n int)

fn native_max_u32(a &u32, b &u32, out &u32, n int) {
	C.v_simd_max_u32(a, b, out, n)
}

fn C.v_simd_and_u32(const_a &u32, const_b &u32, out &u32, n int)

fn native_and_u32(a &u32, b &u32, out &u32, n int) {
	C.v_simd_and_u32(a, b, out, n)
}

fn C.v_simd_or_u32(const_a &u32, const_b &u32, out &u32, n int)

fn native_or_u32(a &u32, b &u32, out &u32, n int) {
	C.v_simd_or_u32(a, b, out, n)
}

fn C.v_simd_xor_u32(const_a &u32, const_b &u32, out &u32, n int)

fn native_xor_u32(a &u32, b &u32, out &u32, n int) {
	C.v_simd_xor_u32(a, b, out, n)
}

fn C.v_simd_not_u32(const_a &u32, out &u32, n int)

fn native_not_u32(a &u32, out &u32, n int) {
	C.v_simd_not_u32(a, out, n)
}

fn C.v_simd_shl_u32(const_a &u32, count u32, out &u32, n int)

fn native_shl_u32(a &u32, count u32, out &u32, n int) {
	C.v_simd_shl_u32(a, count, out, n)
}

fn C.v_simd_shr_u32(const_a &u32, count u32, out &u32, n int)

fn native_shr_u32(a &u32, count u32, out &u32, n int) {
	C.v_simd_shr_u32(a, count, out, n)
}

fn C.v_simd_eq_u32(const_a &u32, const_b &u32, out &i32, n int)

fn native_eq_u32(a &u32, b &u32, out &i32, n int) {
	C.v_simd_eq_u32(a, b, out, n)
}

fn C.v_simd_ne_u32(const_a &u32, const_b &u32, out &i32, n int)

fn native_ne_u32(a &u32, b &u32, out &i32, n int) {
	C.v_simd_ne_u32(a, b, out, n)
}

fn C.v_simd_lt_u32(const_a &u32, const_b &u32, out &i32, n int)

fn native_lt_u32(a &u32, b &u32, out &i32, n int) {
	C.v_simd_lt_u32(a, b, out, n)
}

fn C.v_simd_le_u32(const_a &u32, const_b &u32, out &i32, n int)

fn native_le_u32(a &u32, b &u32, out &i32, n int) {
	C.v_simd_le_u32(a, b, out, n)
}

fn C.v_simd_select_u32(const_m &i32, const_a &u32, const_b &u32, out &u32, n int)

fn native_select_u32(m &i32, a &u32, b &u32, out &u32, n int) {
	C.v_simd_select_u32(m, a, b, out, n)
}

fn C.v_simd_add_u64(const_a &u64, const_b &u64, out &u64, n int)

fn native_add_u64(a &u64, b &u64, out &u64, n int) {
	C.v_simd_add_u64(a, b, out, n)
}

fn C.v_simd_sub_u64(const_a &u64, const_b &u64, out &u64, n int)

fn native_sub_u64(a &u64, b &u64, out &u64, n int) {
	C.v_simd_sub_u64(a, b, out, n)
}

fn C.v_simd_mul_u64(const_a &u64, const_b &u64, out &u64, n int)

fn native_mul_u64(a &u64, b &u64, out &u64, n int) {
	C.v_simd_mul_u64(a, b, out, n)
}

fn C.v_simd_min_u64(const_a &u64, const_b &u64, out &u64, n int)

fn native_min_u64(a &u64, b &u64, out &u64, n int) {
	C.v_simd_min_u64(a, b, out, n)
}

fn C.v_simd_max_u64(const_a &u64, const_b &u64, out &u64, n int)

fn native_max_u64(a &u64, b &u64, out &u64, n int) {
	C.v_simd_max_u64(a, b, out, n)
}

fn C.v_simd_and_u64(const_a &u64, const_b &u64, out &u64, n int)

fn native_and_u64(a &u64, b &u64, out &u64, n int) {
	C.v_simd_and_u64(a, b, out, n)
}

fn C.v_simd_or_u64(const_a &u64, const_b &u64, out &u64, n int)

fn native_or_u64(a &u64, b &u64, out &u64, n int) {
	C.v_simd_or_u64(a, b, out, n)
}

fn C.v_simd_xor_u64(const_a &u64, const_b &u64, out &u64, n int)

fn native_xor_u64(a &u64, b &u64, out &u64, n int) {
	C.v_simd_xor_u64(a, b, out, n)
}

fn C.v_simd_not_u64(const_a &u64, out &u64, n int)

fn native_not_u64(a &u64, out &u64, n int) {
	C.v_simd_not_u64(a, out, n)
}

fn C.v_simd_shl_u64(const_a &u64, count u32, out &u64, n int)

fn native_shl_u64(a &u64, count u32, out &u64, n int) {
	C.v_simd_shl_u64(a, count, out, n)
}

fn C.v_simd_shr_u64(const_a &u64, count u32, out &u64, n int)

fn native_shr_u64(a &u64, count u32, out &u64, n int) {
	C.v_simd_shr_u64(a, count, out, n)
}

fn C.v_simd_eq_u64(const_a &u64, const_b &u64, out &i64, n int)

fn native_eq_u64(a &u64, b &u64, out &i64, n int) {
	C.v_simd_eq_u64(a, b, out, n)
}

fn C.v_simd_ne_u64(const_a &u64, const_b &u64, out &i64, n int)

fn native_ne_u64(a &u64, b &u64, out &i64, n int) {
	C.v_simd_ne_u64(a, b, out, n)
}

fn C.v_simd_lt_u64(const_a &u64, const_b &u64, out &i64, n int)

fn native_lt_u64(a &u64, b &u64, out &i64, n int) {
	C.v_simd_lt_u64(a, b, out, n)
}

fn C.v_simd_le_u64(const_a &u64, const_b &u64, out &i64, n int)

fn native_le_u64(a &u64, b &u64, out &i64, n int) {
	C.v_simd_le_u64(a, b, out, n)
}

fn C.v_simd_select_u64(const_m &i64, const_a &u64, const_b &u64, out &u64, n int)

fn native_select_u64(m &i64, a &u64, b &u64, out &u64, n int) {
	C.v_simd_select_u64(m, a, b, out, n)
}
