module quic

// Client-side handling of a received Version Negotiation packet (RFC 9000
// §6.2, §17.2.1). header.v's parse_version_negotiation (Phase 1) already
// parses the wire format; this file adds the client-side interpretation
// policy for what to do with a parsed one.

// handle_version_negotiation inspects a parsed Version Negotiation packet
// against quic_v1, the only version this module implements or ever offers.
// VN packets are UNAUTHENTICATED (sent before any keys exist), so RFC 9000
// §6.2 draws a sharp line between discarding one and treating it as
// terminal -- a caller must not conflate them into one "VN always aborts"
// policy. ANY ONE of the following makes this function discard silently
// (return success, caller continues the existing connection attempt as if
// the packet had never arrived) rather than fail the connection attempt:
//
//   - `already_processed_other_packet` is true: RFC 9000 §6.2, first
//     sentence -- "A client MUST discard any Version Negotiation packet if
//     it has received and successfully processed any other packet,
//     including an earlier Version Negotiation packet." Once ANY other
//     packet (Initial, Handshake, or an earlier VN) has been successfully
//     processed, the connection attempt is already past the point where a
//     VN packet could be legitimate -- tracking this fact is connection-
//     lifecycle state the caller (Phase 9 QuicConn) must supply, since
//     this function is a stateless verification primitive.
//   - The VN packet's connection IDs don't echo this client's own Initial
//     (RFC 9000 §17.2.1: "The server MUST include the value from the
//     Source Connection ID field of the packet it receives in the
//     Destination Connection ID field. The value for Source Connection ID
//     MUST be copied from the Destination Connection ID of the received
//     packet... Echoing BOTH connection IDs gives clients some assurance
//     that the server received the packet and that the Version
//     Negotiation packet was not generated by an entity that did not
//     observe the Initial packet."). BOTH directions are checked: the VN
//     packet's DCID must equal this client's own SCID, AND the VN
//     packet's SCID must equal this client's own DCID -- mirroring
//     retry.v's analogous two-sided echo validation for Retry packets.
//   - The server's offered-version list INCLUDES v1: RFC 9000 §6.2, second
//     sentence -- "A client MUST discard a Version Negotiation packet that
//     lists the QUIC version selected by the client." This is the exact
//     shape a spoofed, off-path-injected VN packet would have (an attacker
//     with no visibility into the real server's actual (non-)response
//     cannot know whether v1 will be listed, but a client that abandons
//     its attempt on ANY VN packet turns this into a trivial connection-
//     kill primitive for such an attacker).
//
// If none of the above hold and the list does NOT include v1: the normal,
// genuinely terminal case -- this client has no other version to fall back
// to, so the connection attempt fails cleanly. This is the only outcome
// that returns an error.
pub fn handle_version_negotiation(vn QuicVersionNegotiation, original_dcid []u8, original_scid []u8, already_processed_other_packet bool) ! {
	if already_processed_other_packet {
		return
	}
	if vn.dcid != original_scid || vn.scid != original_dcid {
		return
	}
	for v in vn.versions {
		if v == quic_v1 {
			return
		}
	}
	return error('quic: server does not support QUIC v1 (Version Negotiation offered: ${vn.versions}); this client implements only v1, connection cannot proceed')
}
