module fasthttp

import net

#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/epoll.h>
#include <sys/sendfile.h>
#include <sys/stat.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <pthread.h>
#include <signal.h>
#include <time.h>

fn C.socket(domain i32, typ i32, protocol i32) i32

fn C.bind(sockfd i32, addr voidptr, addrlen u32) i32

fn C.send(__fd i32, __buf voidptr, __n usize, __flags i32) i32

fn C.recv(__fd i32, __buf voidptr, __n usize, __flags i32) i32

fn C.setsockopt(__fd i32, __level i32, __optname i32, __optval voidptr, __optlen u32) i32

fn C.listen(__fd i32, __n i32) i32

fn C.perror(s &u8)

fn C.close(fd i32) i32

fn C.htons(__hostshort u16) u16

fn C.fcntl(fd i32, cmd i32, arg ...voidptr) i32

fn C.accept4(sockfd i32, addr &net.Addr, addrlen &u32, flags i32) i32

fn C.epoll_create1(__flags i32) i32

fn C.epoll_ctl(__epfd i32, __op i32, __fd i32, __event &C.epoll_event) i32

fn C.epoll_wait(__epfd i32, __events &C.epoll_event, __maxevents i32, __timeout i32) i32

fn C.sendfile(out_fd i32, in_fd i32, offset voidptr, count usize) i32

@[typedef]
struct C.sigset_t {}

fn C.sigemptyset(set &C.sigset_t)

fn C.sigaddset(set &C.sigset_t, signum i32) i32

fn C.sigpending(set &C.sigset_t) i32

fn C.sigismember(const_set &C.sigset_t, signum i32) i32

fn C.pthread_sigmask(how i32, const_set voidptr, oldset voidptr) i32

fn C.sigtimedwait(const_set &C.sigset_t, info voidptr, const_timeout &C.timespec) i32

// sendfile_without_sigpipe confines SIGPIPE blocking to one sendfile call.
fn sendfile_without_sigpipe(out_fd i32, in_fd i32, offset &i64, count usize) i32 {
	mut sigpipe_set := C.sigset_t{}
	mut previous_mask := C.sigset_t{}
	C.sigemptyset(&sigpipe_set)
	if C.sigaddset(&sigpipe_set, C.SIGPIPE) != 0 {
		return -1
	}
	mask_result := C.pthread_sigmask(C.SIG_BLOCK, &sigpipe_set, &previous_mask)
	if mask_result != 0 {
		C.errno = mask_result
		return -1
	}

	mut pending_set := C.sigset_t{}
	// A pre-existing pending SIGPIPE belongs to the application and must not be consumed here.
	had_pending_sigpipe := C.sigpending(&pending_set) == 0
		&& C.sigismember(&pending_set, C.SIGPIPE) == 1
	sent := C.sendfile(out_fd, in_fd, voidptr(offset), count)
	sendfile_errno := C.errno
	if sent < 0 && sendfile_errno == C.EPIPE && !had_pending_sigpipe {
		// Consume only the SIGPIPE generated by sendfile before restoring an unblocked mask.
		timeout := C.timespec{}
		for {
			wait_result := C.sigtimedwait(&sigpipe_set, C.NULL, &timeout)
			if wait_result == C.SIGPIPE || C.errno != C.EINTR {
				break
			}
		}
	}

	restore_result := C.pthread_sigmask(C.SIG_SETMASK, &previous_mask, C.NULL)
	if restore_result != 0 {
		C.errno = restore_result
		return -1
	}
	C.errno = sendfile_errno
	return sent
}

fn C.fstat(fd i32, buf &C.stat) i32

fn C.open(pathname &char, flags i32, mode ...int) i32

fn C.memmove(dest voidptr, src voidptr, n usize) voidptr

@[typedef]
union C.epoll_data_t {
mut:
	ptr voidptr
	fd  int
	u32 u32
	u64 u64
}

struct C.epoll_event {
mut:
	events u32
	data   C.epoll_data_t
}
