module main

import encoding.protobuf

// The emitter writes V source for a resolved schema.
//
// The generated code is explicit rather than reflective: it calls the Packer and
// Unpacker for each field by name. That is a deliberate trade. A comptime
// reflection API would be less code here and less code in the output, but the
// generated source is the artefact a reader actually debugs, and a stack trace
// through `encode_field` tells them nothing about which field was wrong while
// `packer.write_int32(7, msg.written)` does. It also keeps the generator out of the
// compiler's comptime reflection, which in this compiler version only resolves
// one hop from a concrete type.
//
// Nothing here decides anything: the resolver has already chosen every V type
// and every field number, so the emitter only has to spell them out.

// Emitter builds generated V source.
pub struct Emitter {
mut:
	b []u8
}

// new_emitter returns an Emitter writing to a fresh buffer.
pub fn new_emitter() &Emitter {
	return &Emitter{}
}

// w writes `s` followed by a newline. Every line the emitter produces ends this
// way, so the output is well-formed regardless of which helper wrote it.
pub fn (mut e Emitter) w(s string) {
	e.b << s.bytes()
	e.b << `\n`
}

// wln writes `s` indented `depth` levels and followed by a newline.
pub fn (mut e Emitter) wln(depth int, s string) {
	indent(mut e, depth)
	e.w(s)
}

// indent writes `depth` levels of one tab each.
pub fn indent(mut e Emitter, depth int) {
	for _ in 0 .. depth {
		e.b << `\t`
	}
}

// result returns the generated source.
pub fn (e &Emitter) result() string {
	return e.b.bytestr()
}

// emit_codec writes the codec for a resolved schema: one struct per message, one
// enum per enum, and an `encode`/`decode` pair per message.
pub fn emit_codec(res &ResolvedFile) string {
	mut e := new_emitter()
	e.w('// Code generated by `v pbgen`. DO NOT EDIT.')
	e.w('//')
	e.w('// Regenerate it from the .proto source instead: an edit here is lost the')
	e.w('// next time the generator runs, and the schema and this file would then')
	e.w('// disagree with no compiler error to catch it.')
	e.w('')
	e.w('module ${res.module}')
	e.w('')
	e.w('import encoding.protobuf')
	e.w('')
	for en in res.enums {
		emit_enum(mut e, en)
	}
	for m in res.messages {
		emit_message_struct(mut e, m)
		emit_message_encode(mut e, m)
		emit_message_decode(mut e, m)
		emit_map_functions(mut e, m)
	}
	return e.result()
}

// emit_enum writes a V enum for a proto enum.
//
// The zero member is written first regardless of the schema's own ordering,
// because proto3 requires an enum's zero value to be present and V's zero value
// has to be a declared member: reading a field that was never set produces the
// zero, and an enum that cannot name it has no way to express "unset".
pub fn emit_enum(mut e Emitter, en ResolvedEnum) {
	for line in en.comments {
		e.wln(0, '// ${line}')
	}
	e.wln(0, 'pub enum ${en.v_name} {')
	for v in en.values {
		for line in v.comments {
			e.wln(1, '// ${line}')
		}
		e.wln(1, '${v.name} = ${v.number}')
	}
	e.wln(0, '}')
	e.w('')
}

// emit_message_struct writes the struct a message decodes into.
pub fn emit_message_struct(mut e Emitter, m ResolvedMessage) {
	for line in m.comments {
		e.wln(0, '// ${line}')
	}
	e.wln(0, '// ${m.v_name} is the generated form of the proto3 message `${m.doc_name}`.')
	e.wln(0, '//')
	e.wln(0, "// The @[protobuf: n] attributes record each field's wire number. They are")
	e.wln(0, '// what a reader checks a payload against, so they are written literally')
	e.wln(0, '// rather than inferred from declaration order.')
	if m.fields.len == 0 {
		e.wln(0, 'pub struct ${m.v_name} {}')
		e.w('')
		return
	}
	e.wln(0, 'pub struct ${m.v_name} {')
	e.wln(1, 'pub mut:')
	for f in m.fields {
		for line in f.comments {
			e.wln(2, '// ${line}')
		}
		e.wln(2, '// ${f.name} is `${field_declaration(f)}`.')
		e.wln(2, '${f.name} ${declared_type(f)} @[protobuf: ${f.number}]')
	}
	e.wln(0, '}')
	e.w('')
}

// field_declaration spells the field as the schema wrote it, for the doc comment.
pub fn field_declaration(f Resolved) string {
	label := match f.label {
		.repeated { 'repeated ' }
		.optional { 'optional ' }
		.singular { '' }
	}
	return '${label}${f.proto_type} ${f.name} = ${f.number}'
}

// declared_type returns the V type a field is declared as. A field with explicit
// presence is declared optional, so that a set default is still distinguishable
// from an absent field. That covers a proto3 `optional` field as well as a
// `oneof` member; a plain singular field keeps its bare type.
pub fn declared_type(f Resolved) string {
	if f.has_explicit_presence() {
		return '?${f.v_type}'
	}
	return f.v_type
}

// emit_message_encode writes `encode` and `encode_with` for one message.
//
// The two exist because the rule that decides whether a field at its default is
// written belongs to the caller, not to the Packer: a proto3 producer omits it,
// and a proto2-style producer keeps explicit presence. `encode` is the proto3
// case, and `encode_with` is the one that can be asked for the other.
pub fn emit_message_encode(mut e Emitter, m ResolvedMessage) {
	e.wln(0, '// encode serializes `msg` to the proto3 wire format.')
	e.wln(0, '//')
	e.wln(0, '// A proto3 field holding its default is not written: on the wire an absent')
	e.wln(0, '// field and a field set to its default are the same thing, so encoding a')
	e.wln(0, '// zero value produces no bytes for it. A field declared `optional`, or')
	e.wln(0, '// holding a member of a `oneof`, is the exception: it records presence,')
	e.wln(0, '// so it is written even at its default.')
	e.wln(0, '//')
	e.wln(0, '// Use encode_with when the peer expects explicit presence instead.')
	e.wln(0, 'pub fn (msg ${m.v_name}) encode() ![]u8 {')
	e.wln(1, 'return msg.encode_with(protobuf.EncodeOpts{})')
	e.wln(0, '}')
	e.w('')
	e.wln(0, '// encode_with serializes `msg` with `opts`.')
	e.wln(0, '//')
	e.wln(0, '// `opts.emit_defaults` writes a field that holds its default instead of')
	e.wln(0, '// leaving it off the wire, which is what a consumer expecting explicit')
	e.wln(0, '// presence needs. The options also reach nested messages and map entries.')
	e.wln(0, 'pub fn (msg ${m.v_name}) encode_with(opts protobuf.EncodeOpts) ![]u8 {')
	e.wln(1, 'mut packer := protobuf.new_packer(opts)')
	if m.fields.len == 0 {
		e.wln(1, '_ = &packer')
	}
	for f in m.fields {
		emit_encode_field(mut e, f)
	}
	e.wln(1, 'return packer.bytes()')
	e.wln(0, '}')
	e.w('')
}

// emit_encode_field writes the statements that put one field on the wire.
pub fn emit_encode_field(mut e Emitter, f Resolved) {
	n := f.number
	value := 'msg.${f.name}'
	match f.kind {
		.map {
			// An empty map writes nothing either way, so the options only matter
			// for the entries that are written.
			e.wln(1, 'if ${value}.len > 0 {')
			e.wln(2, 'emit_map_${f.name}(mut packer, ${n}, ${value}, opts)!')
			e.wln(1, '}')
			return
		}
		else {}
	}
	if f.is_repeated() {
		emit_encode_repeated(mut e, f, value)
		return
	}
	if f.has_explicit_presence() {
		// A field with explicit presence is written whenever it holds a value,
		// including one holding the default, because the difference between "set
		// to the default" and "never set" is the whole point of declaring the
		// presence in the first place. `emit_defaults` changes nothing here: this
		// field already writes its default whenever it is set.
		e.wln(1, 'if inner := ${value} {')
		line := emit_single_encode(f, n, 'inner')
		if line != '' {
			e.wln(2, line)
		}
		e.wln(1, '}')
		return
	}
	// proto3 implicit presence: skip a field at its default, unless the caller
	// asked for the fields that hold one to be written anyway.
	if f.kind == .message {
		// A nested message is present whenever the field is, even when all of
		// its own fields hold defaults, so it is written unconditionally.
		e.wln(1, 'packer.write_message(${n}, ${value}.encode_with(opts)!)')
		return
	}
	e.wln(1, 'if ${emit_default_test(f, value)} {')
	line := emit_single_encode(f, n, value)
	if line != '' {
		e.wln(2, line)
	}
	e.wln(1, '}')
}

// emit_default_test returns the condition under which a singular proto3 field is
// present. A `bytes` field is present when it has bytes rather than when the
// slice is non-nil, since a zero-length slice written as empty and one that was
// never set are the same message.
//
// `opts.emit_defaults` is ORed into the condition rather than branching the whole
// function, so a caller that never sets it pays one test per field and a caller
// that does gets every field written.
pub fn emit_default_test(f Resolved, value string) string {
	return 'opts.emit_defaults || ${default_test(f, value)}'
}

// default_test returns the bare presence condition, without the option.
fn default_test(f Resolved, value string) string {
	return match f.kind {
		.text { '${value}.len > 0' }
		.bytes { '${value}.len > 0' }
		.enum { 'int(${value}) != 0' }
		.scalar {
			match f.scalar {
				.boolean { value }
				.float32, .float64 { '${value} != 0.0' }
				else { '${value} != 0' }
			}
		}
		else { 'true' }
	}
}

// emit_single_encode returns the one statement that writes a non-repeated
// field's value, or an empty string when the kind has no such statement.
pub fn emit_single_encode(f Resolved, n int, value string) string {
	match f.kind {
		.text { return 'packer.write_string(${n}, ${value})!' }
		.bytes { return 'packer.write_bytes(${n}, ${value})' }
		.message { return 'packer.write_message(${n}, ${value}.encode_with(opts)!)' }
		.enum { return 'packer.write_enum(${n}, int(${value}))' }
		.scalar {
			return match f.scalar {
				.boolean { 'packer.write_bool(${n}, ${value})' }
				.int32 { 'packer.write_int32(${n}, ${value})' }
				.int64 { 'packer.write_int64(${n}, ${value})' }
				.uint32 { 'packer.write_uint32(${n}, ${value})' }
				.uint64 { 'packer.write_uint64(${n}, ${value})' }
				.sint32 { 'packer.write_sint32(${n}, ${value})' }
				.sint64 { 'packer.write_sint64(${n}, ${value})' }
				.fixed32 { 'packer.write_fixed32(${n}, ${value})' }
				.sfixed32 { 'packer.write_sfixed32(${n}, ${value})' }
				.fixed64 { 'packer.write_fixed64(${n}, ${value})' }
				.sfixed64 { 'packer.write_sfixed64(${n}, ${value})' }
				.float32 { 'packer.write_float(${n}, ${value})' }
				.float64 { 'packer.write_double(${n}, ${value})' }
			}
		}
		else { return '' }
	}
}

// emit_encode_repeated writes the statements for a list field.
//
// A repeated numeric field uses the packed form, which is the spec's default: one
// tag and one length, then the values back to back. A repeated string, bytes, or
// message has no packed form, so each element carries its own tag.
//
// proto3 omits an empty repeated field, so the length check guards the whole
// thing: writing a tag and a zero length for an empty list would put bytes on
// the wire that the reference implementation does not write.
pub fn emit_encode_repeated(mut e Emitter, f Resolved, value string) {
	n := f.number
	e.wln(1, 'if ${value}.len > 0 {')
	if !f.is_packed() {
		e.wln(2, 'for item in ${value} {')
		line := emit_single_encode_elem(f, n, 'item')
		if line != '' {
			e.wln(3, line)
		}
		e.wln(2, '}')
	} else {
		// The element's own wire type: the enclosing tag says only that the
		// payload is a length-delimited run.
		wire := f.scalar.wire_type()
		e.wln(2, 'mut payload := []u8{cap: ${value}.len * ${packed_width(f.scalar)}}')
		e.wln(2, 'for item in ${value} {')
		e.wln(3, packed_element_call(f.scalar, 'item'))
		e.wln(2, '}')
		e.wln(2, 'packer.write_packed_payload(${n}, protobuf.WireType.${wire}, payload)')
	}
	e.wln(1, '}')
}

// packed_width returns how many bytes one packed element of `s` takes, used to
// size the payload buffer once instead of growing it per element.
pub fn packed_width(s protobuf.ProtoScalar) int {
	return match s {
		.float64, .fixed64, .sfixed64 { 8 }
		.float32, .fixed32, .sfixed32 { 4 }
		else { 1 }
	}
}

// packed_element_call returns the statement that appends one element to a packed
// payload. The module's own put_* helpers are used rather than a Packer, because
// a Packer would write a tag per element, which is what packing exists to avoid.
pub fn packed_element_call(s protobuf.ProtoScalar, value string) string {
	return match s {
		.boolean { 'protobuf.put_varint(mut payload, if ${value} { u64(1) } else { u64(0) })' }
		.int32 { 'protobuf.put_varint(mut payload, protobuf.int32_varint(${value}))' }
		.int64 { 'protobuf.put_varint(mut payload, protobuf.int64_varint(${value}))' }
		.uint32, .uint64 { 'protobuf.put_varint(mut payload, u64(${value}))' }
		.sint32 { 'protobuf.put_varint(mut payload, u64(protobuf.zigzag_encode_i32(${value})))' }
		.sint64 { 'protobuf.put_varint(mut payload, protobuf.zigzag_encode_i64(${value}))' }
		.fixed32 { 'protobuf.put_fixed32(mut payload, ${value})' }
		.sfixed32 { 'protobuf.put_fixed32(mut payload, u32(${value}))' }
		.fixed64 { 'protobuf.put_fixed64(mut payload, ${value})' }
		.sfixed64 { 'protobuf.put_fixed64(mut payload, u64(${value}))' }
		.float32 { 'protobuf.put_float(mut payload, ${value})' }
		.float64 { 'protobuf.put_double(mut payload, ${value})' }
	}
}

// emit_single_encode_elem returns the statement that writes one element of a
// repeated field, where a message element is encoded by its own codec.
pub fn emit_single_encode_elem(f Resolved, n int, value string) string {
	if f.kind == .message {
		return 'packer.write_message(${n}, ${value}.encode_with(opts)!)'
	}
	return emit_single_encode(f, n, value)
}
