module mysql

/* MYSQL CONNECT FLAGS */
pub const (
	// CAN_HANDLE_EXPIRED_PASSWORDS       = C.CAN_HANDLE_EXPIRED_PASSWORDS
	CLIENT_COMPRESS                    = C.CLIENT_COMPRESS
	CLIENT_FOUND_ROWS                  = C.CLIENT_FOUND_ROWS
	CLIENT_IGNORE_SIGPIPE              = C.CLIENT_IGNORE_SIGPIPE
	CLIENT_IGNORE_SPACE                = C.CLIENT_IGNORE_SPACE
	CLIENT_INTERACTIVE                 = C.CLIENT_INTERACTIVE
	CLIENT_LOCAL_FILES                 = C.CLIENT_LOCAL_FILES
	CLIENT_MULTI_RESULTS               = C.CLIENT_MULTI_RESULTS
	CLIENT_MULTI_STATEMENTS            = C.CLIENT_MULTI_STATEMENTS
	CLIENT_NO_SCHEMA                   = C.CLIENT_NO_SCHEMA
	CLIENT_ODBC                        = C.CLIENT_ODBC
	// CLIENT_OPTIONAL_RESULTSET_METADATA = C.CLIENT_OPTIONAL_RESULTSET_METADATA
	CLIENT_SSL                         = C.CLIENT_SSL
	CLIENT_REMEMBER_OPTIONS            = C.CLIENT_REMEMBER_OPTIONS
)

/* MYSQL REFRESH FLAGS */
pub const (
	REFRESH_GRANT   = u32(C.REFRESH_GRANT)
	REFRESH_LOG     = u32(C.REFRESH_LOG)
	REFRESH_TABLES  = u32(C.REFRESH_TABLES)
	REFRESH_HOSTS   = u32(C.REFRESH_HOSTS)
	REFRESH_STATUS  = u32(C.REFRESH_STATUS)
	REFRESH_THREADS = u32(C.REFRESH_THREADS)
	REFRESH_SLAVE   = u32(C.REFRESH_SLAVE)
	REFRESH_MASTER  = u32(C.REFRESH_MASTER)
)
