name: 📕 Documentation Issue
description: Report an issue in the Reference documentation or Developer Guide
labels: ['Unit: Documentation']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links
      description: Include links to affected documentation page(s).
    validations:
      required: true
