// Copyright (c) 2019-2024 Alexander Medvednikov. All rights reserved.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.
module http

// h2_hpack_static_table is the HPACK static table (RFC 7541 Appendix A).
// HPACK indexes into it are 1-based, so entry N is at index N-1 here.
const h2_hpack_static_table = [
	H2HeaderField{':authority', ''},
	H2HeaderField{':method', 'GET'},
	H2HeaderField{':method', 'POST'},
	H2HeaderField{':path', '/'},
	H2HeaderField{':path', '/index.html'},
	H2HeaderField{':scheme', 'http'},
	H2HeaderField{':scheme', 'https'},
	H2HeaderField{':status', '200'},
	H2HeaderField{':status', '204'},
	H2HeaderField{':status', '206'},
	H2HeaderField{':status', '304'},
	H2HeaderField{':status', '400'},
	H2HeaderField{':status', '404'},
	H2HeaderField{':status', '500'},
	H2HeaderField{'accept-charset', ''},
	H2HeaderField{'accept-encoding', 'gzip, deflate'},
	H2HeaderField{'accept-language', ''},
	H2HeaderField{'accept-ranges', ''},
	H2HeaderField{'accept', ''},
	H2HeaderField{'access-control-allow-origin', ''},
	H2HeaderField{'age', ''},
	H2HeaderField{'allow', ''},
	H2HeaderField{'authorization', ''},
	H2HeaderField{'cache-control', ''},
	H2HeaderField{'content-disposition', ''},
	H2HeaderField{'content-encoding', ''},
	H2HeaderField{'content-language', ''},
	H2HeaderField{'content-length', ''},
	H2HeaderField{'content-location', ''},
	H2HeaderField{'content-range', ''},
	H2HeaderField{'content-type', ''},
	H2HeaderField{'cookie', ''},
	H2HeaderField{'date', ''},
	H2HeaderField{'etag', ''},
	H2HeaderField{'expect', ''},
	H2HeaderField{'expires', ''},
	H2HeaderField{'from', ''},
	H2HeaderField{'host', ''},
	H2HeaderField{'if-match', ''},
	H2HeaderField{'if-modified-since', ''},
	H2HeaderField{'if-none-match', ''},
	H2HeaderField{'if-range', ''},
	H2HeaderField{'if-unmodified-since', ''},
	H2HeaderField{'last-modified', ''},
	H2HeaderField{'link', ''},
	H2HeaderField{'location', ''},
	H2HeaderField{'max-forwards', ''},
	H2HeaderField{'proxy-authenticate', ''},
	H2HeaderField{'proxy-authorization', ''},
	H2HeaderField{'range', ''},
	H2HeaderField{'referer', ''},
	H2HeaderField{'refresh', ''},
	H2HeaderField{'retry-after', ''},
	H2HeaderField{'server', ''},
	H2HeaderField{'set-cookie', ''},
	H2HeaderField{'strict-transport-security', ''},
	H2HeaderField{'transfer-encoding', ''},
	H2HeaderField{'user-agent', ''},
	H2HeaderField{'vary', ''},
	H2HeaderField{'via', ''},
	H2HeaderField{'www-authenticate', ''},
]!

// h2_hpack_static_len is the number of entries in the HPACK static table.
const h2_hpack_static_len = h2_hpack_static_table.len
