// Copyright (c) 2019-2024 Alexander Medvednikov. All rights reserved.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.
module ecdsa

import crypto.sha512

// test_sign_with_custom_hash_is_not_implemented locks in PrivateKey.sign()'s
// own documented restriction: .with_custom_hash signing is not implemented
// on the default mbedTLS backend (mbedtls_ecdsa_write_signature's RFC 6979
// deterministic-nonce path rejects MBEDTLS_MD_NONE outright -- see sign()'s
// own doc comment). This restriction applies only to the DEFAULT backend --
// under -d use_openssl the same call succeeds instead (see util_test.v's
// test_key_signing_verifying_with_custom_hash), so this test skips itself
// via `$if use_openssl ?` rather than asserting failure when the whole
// crypto.ecdsa directory is run with -d use_openssl explicitly (this file
// carries no vtest vflags of its own to force the flag either way).
fn test_sign_with_custom_hash_is_not_implemented() ! {
	$if use_openssl ? {
		eprintln('skipping: .with_custom_hash signing IS implemented under -d use_openssl')
		return
	}
	pv := PrivateKey.new()!
	defer { pv.free() }
	opt := SignerOpts{
		hash_config: .with_custom_hash
		allow_custom_hash: true
		custom_hash: sha512.new()
	}
	pv.sign('a message'.bytes(), opt) or {
		assert err.msg().contains('-d use_openssl')
		return
	}
	assert false, '.with_custom_hash signing should not be implemented on the default backend'
}

// test_verify_cross_implementation_oracle_vector closes a real test-coverage
// gap: every OTHER sign/verify test on the default mbedTLS backend is a
// self-consistency round trip (sign with a freshly generated key, verify
// with the very same key/code path) -- a bug in calc_digest()'s curve->hash
// selection, or in sign_digest()/verify()'s digest handling, could apply
// identically on both sides of such a round trip and never be caught. This
// test instead verifies a signature this mbedTLS backend never produced --
// generated by this repo's own INDEPENDENT OpenSSL backend (a completely
// different crypto library, its own digest/DER/curve-parameter code paths)
// -- proving mbedTLS's verify() genuinely agrees with real cryptographic
// ground truth, not just with itself.
//
// Vector generated once via: `./vnew -d use_openssl -cflags ... run` on a
// small script calling ecdsa.new_key_from_seed(seed)!, .sign(message)!, and
// .public_key()!.uncompressed_bytes()! against the OpenSSL backend, from a
// fixed seed and a fixed message -- reproducible from crypto.ecdsa's own
// public API, not hand-fabricated.
fn test_verify_cross_implementation_oracle_vector() ! {
	pubkey_bytes := [u8(0x04), 0x01, 0xcb, 0x89, 0x0e, 0x0e, 0x7f, 0x4c, 0x80, 0x55, 0x8f, 0x6a,
		0x4f, 0xa1, 0x04, 0xbc, 0x69, 0x13, 0x40, 0x67, 0xde, 0xf0, 0x72, 0x01, 0xd3, 0x7f, 0x57,
		0x21, 0xc1, 0xfa, 0xc7, 0x03, 0xc4, 0xe2, 0xdb, 0x92, 0xb1, 0x37, 0xd3, 0x19, 0x4c, 0x3c,
		0x7d, 0x81, 0x5a, 0x81, 0xe6, 0x68, 0x14, 0xd7, 0xea, 0x3f, 0x6c, 0xe9, 0xf1, 0xd6, 0x4d,
		0xcc, 0xa4, 0x76, 0xd8, 0xe4, 0xc6, 0xd1, 0x4b]
	message := 'crypto.ecdsa mbedTLS-vs-OpenSSL cross-implementation oracle vector'.bytes()
	sig := [u8(0x30), 0x45, 0x02, 0x20, 0x73, 0xca, 0x75, 0x5b, 0x45, 0xa5, 0x1f, 0x65, 0x8c, 0xf5,
		0xdb, 0x04, 0x30, 0xdb, 0xa5, 0x6b, 0xa7, 0x7d, 0xf5, 0xb0, 0x03, 0x8c, 0x02, 0xff, 0xe9,
		0x58, 0x3a, 0x3c, 0x17, 0x2b, 0x82, 0xe9, 0x02, 0x21, 0x00, 0x99, 0x11, 0xfb, 0x81, 0x0b,
		0x1f, 0xc4, 0xf2, 0xa6, 0xef, 0x39, 0x9f, 0x5b, 0x4d, 0x8d, 0x4a, 0x18, 0x88, 0xd6, 0xe9,
		0xc9, 0x23, 0x26, 0x1a, 0x0f, 0xad, 0x1a, 0x51, 0x59, 0x17, 0x9a, 0x37]

	pb := PublicKey.from_uncompressed_bytes(pubkey_bytes)!
	defer { pb.free() }
	assert pb.verify(message, sig)!
}

// test_generate_key_for_every_curve closes a real test-coverage gap:
// mbedtls_group_id() maps all four Nid variants to four distinct, visually
// similar C.MBEDTLS_ECP_DP_* constants -- a classic copy/paste-slip target
// -- but every other test on the default backend, and every production
// caller in net.quic, only ever requests .prime256v1, so the other three
// arms had zero coverage: a swap would compile cleanly and stay green until
// a real caller requested one of the untested curves. Exercising all four
// here, and asserting each produces the CORRECT curve-native byte size
// (32/48/66/32), catches a size-changing swap (e.g. secp384r1<->secp521r1)
// outright; a same-size swap (prime256v1<->secp256k1) would still at least
// need to produce a working, self-consistent keypair on SOME valid curve to
// pass, which a wrong C constant is not guaranteed to do.
fn test_generate_key_for_every_curve() ! {
	sizes := {
		Nid.prime256v1: 32
		Nid.secp384r1:  48
		Nid.secp521r1:  66
		Nid.secp256k1:  32
	}
	for nid, want_size in sizes {
		// Explicit per-iteration free, not `defer`: defer inside a loop only
		// fires at function exit (not per iteration), which would hold all
		// four curves' keypairs allocated simultaneously instead of freeing
		// each as its own iteration finishes.
		pb, pv := generate_key(nid: nid)!
		assert pv.bytes()!.len == want_size, 'curve ${nid} should produce a ${want_size}-byte private key'
		message := 'per-curve coverage for ${nid}'.bytes()
		signature := pv.sign(message)!
		assert pb.verify(message, signature)!
		pb.free()
		pv.free()
	}
}
