// gen_quote_data.go generates the Unicode tables in ../printable_tables.v and
// the expected results that ../quote_test.v and ../unquote_test.v compare the
// V port against, all from Go's own unicode and strconv packages.
//
// Run it from this directory, with the Go release named in the header of
// ../printable_tables.v (go1.26.1, Unicode 15.0.0) to reproduce the committed
// files exactly:
//
//	go run gen_quote_data.go
//
// It rewrites ../printable_tables.v, and the lines between the begin and end
// markers in the two test files. Its output is already formatted, so
// `v fmt -verify vlib/strconv` passes without running `v fmt -w`. A newer Go
// release may carry a newer Unicode version; the tables and the expected
// results then change together.

//go:build ignore

package main

import (
	"fmt"
	"hash/fnv"
	"log"
	"os"
	"runtime"
	"strconv"
	"strings"
	"unicode"
)

const beginMarker = "// begin: generated by testdata/gen_quote_data.go, do not edit"
const endMarker = "// end: generated by testdata/gen_quote_data.go"

func main() {
	writeFile("../printable_tables.v", printableTables())
	replaceBlock("../quote_test.v", quoteTestData())
	replaceBlock("../unquote_test.v", unquoteTestData())
}

func writeFile(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		log.Fatal(err)
	}
}

// replaceBlock replaces the lines between the begin and end markers of the file
// at path with content.
func replaceBlock(path, content string) {
	data, err := os.ReadFile(path)
	if err != nil {
		log.Fatal(err)
	}
	src := string(data)
	begin := strings.Index(src, beginMarker+"\n")
	end := strings.Index(src, endMarker+"\n")
	if begin < 0 || end < begin {
		log.Fatalf("%s: missing generated block markers", path)
	}
	begin += len(beginMarker) + 1
	writeFile(path, src[:begin]+content+src[end:])
}

// version names the Go release and the Unicode version the data comes from.
func version() string {
	return fmt.Sprintf("%s (Unicode %s)", runtime.Version(), unicode.Version)
}

// printableTables reproduces Go's src/strconv/makeisprint.go, which produces
// src/strconv/isprint.go, but writes V fixed arrays.
func printableTables() string {
	rang, except := scan(0, 0xFFFF)
	range16 := to16(rang)
	except16 := to16(except)
	range32, except32 := scan(0x10000, unicode.MaxRune)
	var notPrint32 []uint16
	for _, r := range except32 {
		if r >= 0x20000 {
			log.Fatalf("%U too big for is_not_print32", r)
		}
		notPrint32 = append(notPrint32, uint16(r-0x10000))
	}
	var graphic []uint16
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if unicode.IsPrint(r) != unicode.IsGraphic(r) {
			if !unicode.IsGraphic(r) {
				log.Fatalf("%U is printable but not graphic", r)
			}
			if r > 0xFFFF {
				log.Fatalf("%U too big for is_graphic_list", r)
			}
			graphic = append(graphic, uint16(r))
		}
	}

	var b strings.Builder
	b.WriteString("module strconv\n\n")
	fmt.Fprintf(&b, "// Code generated by testdata/gen_quote_data.go from %s; DO NOT EDIT.\n", version())
	b.WriteString("// The values are those of Go's src/strconv/isprint.go for that release.\n\n")
	b.WriteString("// is_print16 lists the printable runes below U+10000 as inclusive ranges,\n")
	b.WriteString("// one pair of values per range.\n")
	writeU16s(&b, "is_print16", range16)
	b.WriteString("\n// is_not_print16 lists the runes inside those ranges that are not printable.\n")
	writeU16s(&b, "is_not_print16", except16)
	b.WriteString("\n// is_print32 lists the printable runes from U+10000 as inclusive ranges.\n")
	b.WriteString("const is_print32 = [\n")
	for _, v := range range32 {
		fmt.Fprintf(&b, "\tu32(%#06x),\n", v)
	}
	b.WriteString("]!\n")
	b.WriteString("\n// is_not_print32 lists the runes inside those ranges that are not printable,\n")
	b.WriteString("// minus 0x10000.\n")
	writeU16s(&b, "is_not_print32", notPrint32)
	b.WriteString("\n// is_graphic_list lists the graphic runes that are not printable.\n")
	writeU16s(&b, "is_graphic_list", graphic)
	return b.String()
}

func writeU16s(b *strings.Builder, name string, values []uint16) {
	fmt.Fprintf(b, "const %s = [\n", name)
	for _, v := range values {
		fmt.Fprintf(b, "\tu16(%#04x),\n", v)
	}
	b.WriteString("]!\n")
}

// scan is makeisprint.go's scan: it splits [min, max] into printable ranges,
// recording an isolated non-printable rune as an exception instead of
// splitting a range around it.
func scan(min, max rune) (rang, except []uint32) {
	lo := rune(-1)
	for i := min; ; i++ {
		if (i > max || !unicode.IsPrint(i)) && lo >= 0 {
			// End range, but avoid flip flop.
			if i+1 <= max && unicode.IsPrint(i+1) {
				except = append(except, uint32(i))
				continue
			}
			rang = append(rang, uint32(lo), uint32(i-1))
			lo = -1
		}
		if i > max {
			break
		}
		if lo < 0 && unicode.IsPrint(i) {
			lo = i
		}
	}
	return
}

func to16(x []uint32) []uint16 {
	var y []uint16
	for _, v := range x {
		if uint32(uint16(v)) != v {
			panic("bad 32->16 conversion")
		}
		y = append(y, uint16(v))
	}
	return y
}

// quoteCorpus is the input list for the quote tests: a few strings, every
// single byte, then the escape, UTF-8 boundary and invalid UTF-8 cases.
func quoteCorpus() []string {
	out := []string{"", "hello", "caf\u00e9", "\u20ac", "\U0001F600", "a\uFFFDb"}
	for i := 0; i < 256; i++ {
		out = append(out, string([]byte{byte(i)}))
	}
	return append(out,
		"a\nb", "a\tb", "a\\b", "a\"b", "a'b", "\a\b\f\n\r\t\v\\\"'", "\\n", "\\\\", "\x7f",
		// the first and last rune of each UTF-8 length, and around the surrogates
		"\u0080", "\u07ff", "\u0800", "\ud7ff", "\ue000", "\uffff", "\U00010000",
		"\ufffd", "\ufffe", "\uffff", "\U00010000", "\U0010fffe", "\U0010ffff",
		"\ufffd", "\ufffd",
		// invalid UTF-8: stray continuation bytes, truncated and overlong
		// sequences, surrogates and out-of-range lead bytes
		"\x80", "\xbf", "\xc3", "\xc3(", "\xe2(\xa1", "\xe2\x82", "\xf0(\x8c(",
		"\xf0\x90(\xbc", "\xf4\x90\x80\x80", "\xc0\xaf", "\xc1\xbf", "\xed\xa0\x80",
		"\xfe", "\xff", "\xf5\x80\x80\x80", "valid\xfftail", "\xff\xfe\xfd", "\ufffd",
		"", "a", "hello world", "has space", "has\ttab", "has\nnl", "has\rcr",
		"has`backquote", "has\\backslash", "has\"", "`", "`x", "x`", "\u00e9",
		"\u4e16\u754c",
	)
}

// quoteRunes is the input list for the rune tests, including invalid runes.
var quoteRunes = []rune{
	0x7f, 0x80, 0x7ff, 0x800, 0xd7ff, 0xe000, 0xffff, 0x10000, 0xfffd, 0xfffe,
	0xffff, 0x10000, 0x10fffe, 0x10ffff, 0xd800, 0xdfff, 0, 1, 7, 8, 9, 10, 11,
	12, 13, 27, 31, 32, 33, 34, 39, 92, 96, 127, 128, 160, 173, 233, 8232, 0xfffd,
	0x1f600, 0x10ffff, 0xd800, 0xdfff, 0x110000, -1, -200, 0x7fffffff,
}

func quoteTestData() string {
	corpus := quoteCorpus()
	var b strings.Builder
	fmt.Fprintf(&b, "// Expected results from %s.\n", version())
	writeHash(&b, "go_is_print_hash", flagHash(unicode.IsPrint))
	writeHash(&b, "go_is_graphic_hash", flagHash(unicode.IsGraphic))
	writeHash(&b, "go_can_backquote_hash", flagHash(func(r rune) bool {
		// string(r) turns a surrogate into U+FFFD, as rune_str does
		return strconv.CanBackquote(string(r))
	}))
	b.WriteString("\n")
	stringsCase := func(name string, f func(string) string) {
		writeStrings(&b, name, mapStrings(corpus, f))
	}
	stringsCase("corpus_hex", hexOf)
	stringsCase("gold_quote", func(s string) string { return hexOf(strconv.Quote(s)) })
	stringsCase("gold_quote_to_ascii", func(s string) string { return hexOf(strconv.QuoteToASCII(s)) })
	stringsCase("gold_quote_to_graphic", func(s string) string { return hexOf(strconv.QuoteToGraphic(s)) })
	stringsCase("gold_append_quote", func(s string) string {
		return hexOf(string(strconv.AppendQuote([]byte("PRE"), s)))
	})
	stringsCase("gold_can_backquote", func(s string) string { return strconv.FormatBool(strconv.CanBackquote(s)) })
	runesCase := func(name string, f func(rune) string) {
		var out []string
		for _, r := range quoteRunes {
			out = append(out, f(r))
		}
		writeStrings(&b, name, out)
	}
	runesCase("corpus_runes", func(r rune) string { return strconv.Itoa(int(r)) })
	runesCase("gold_quote_rune", func(r rune) string { return hexOf(strconv.QuoteRune(r)) })
	runesCase("gold_quote_rune_to_ascii", func(r rune) string { return hexOf(strconv.QuoteRuneToASCII(r)) })
	runesCase("gold_quote_rune_to_graphic", func(r rune) string { return hexOf(strconv.QuoteRuneToGraphic(r)) })
	runesCase("gold_append_quote_rune", func(r rune) string {
		return hexOf(string(strconv.AppendQuoteRune([]byte("PRE"), r)))
	})
	runesCase("gold_is_print", func(r rune) string { return strconv.FormatBool(unicode.IsPrint(r)) })
	runesCase("gold_is_graphic", func(r rune) string { return strconv.FormatBool(unicode.IsGraphic(r)) })
	return b.String()
}

// unquoteCorpus must produce the same inputs, in the same order, as corpus()
// in unquote_test.v; corpus_hash checks that it does.
func unquoteCorpus() []string {
	var out []string
	for i := 0; i < 256; i++ {
		b := string([]byte{byte(i)})
		out = append(out, `"`+b+`"`, "'"+b+"'", "`"+b+"`")
	}
	for i := 0; i < 256; i++ {
		for j := 0; j < 0x29; j++ {
			ab := string([]byte{byte(i), byte(j)})
			out = append(out, `"`+ab+`"`, "'"+ab+"'")
		}
	}
	return out
}

// curatedInputs get explicit expectations, so a failure names the input.
var curatedInputs = []string{
	"\"\"", "\"a\"", "\"'\"", "`\"`", "`a`", "``", "''", "'a'",
	"\"a\\tb\"", "\"a\\nb\"", "\"a\\rb\"", "`a\rb`", "\"a\\\\b\"", "\"a\\\"b\"",
	"'\\''", "\"\\'\"", "'\"'",
	// numeric escapes, their limits and their malformed forms
	"\"\\x41\"", "\"\\u00e9\"", "\"\\U0001F600\"", "\"\\101\"", "\"\\0\"", "\"\\8\"",
	"\"\\400\"", "\"\\q\"", "\"\\\"", "\"\\uD800\"", "\"\\U110000\"", "\"\\x\"", "\"\\x4\"",
	// terminators
	"\"abc\"", "\"abc", "'ab'", "\"a\"tail", "`a`tail", "\"a\nb\"", "\"a`b\"", "'a", "\"a",
	"\"caf?\"", "\"\\xff\"", "\"\\xe9\"", "\"\\u0000\"", "\"\\uFFFF\"", "\"\\uFEFF\"",
	"'\\n'", "`a\tb`", "\"\\\\\"", "\"\\a\\b\\f\\n\\r\\t\\v\"",
	// multi-byte runes written literally, with and without escapes around them
	"\"caf\u00e9\"", "'\u00e9'", "'\U0001F600'", "\"\u00e9\\n\u4e16\"", "'\u00e9x'",
}

func unquoteTestData() string {
	corpus := unquoteCorpus()
	var b strings.Builder
	fmt.Fprintf(&b, "// Expected results from %s.\n", version())
	fmt.Fprintf(&b, "const corpus_count = %d\n\n", len(corpus))
	writeHash(&b, "corpus_hash", listHash(corpus, func(s string) string { return hexOf(s) }))
	b.WriteString("\n")
	writeHash(&b, "unquote_hash", listHash(corpus, func(s string) string {
		v, err := strconv.Unquote(s)
		return orError(hexOf(v), err)
	}))
	b.WriteString("\n")
	writeHash(&b, "prefix_hash", listHash(corpus, func(s string) string {
		v, err := strconv.QuotedPrefix(s)
		return orError(hexOf(v), err)
	}))
	b.WriteString("\n")
	for _, q := range []struct {
		name  string
		quote byte
	}{{"char_d_hash", '"'}, {"char_s_hash", '\''}} {
		writeHash(&b, q.name, listHash(corpus, func(s string) string {
			value, multibyte, tail, err := strconv.UnquoteChar(s, q.quote)
			return orError(fmt.Sprintf("%d:%t:%s", value, multibyte, hexOf(tail)), err)
		}))
		b.WriteString("\n")
	}
	writeStrings(&b, "curated_hex", mapStrings(curatedInputs, hexOf))
	writeStrings(&b, "curated_unquote", mapStrings(curatedInputs, func(s string) string {
		v, err := strconv.Unquote(s)
		return orError(hexOf(v), err)
	}))
	writeStrings(&b, "curated_prefix", mapStrings(curatedInputs, func(s string) string {
		v, err := strconv.QuotedPrefix(s)
		return orError(hexOf(v), err)
	}))
	return b.String()
}

// orError returns "E" when err is set; hex output never contains an "E".
func orError(s string, err error) string {
	if err != nil {
		return "E"
	}
	return s
}

func hexOf(s string) string {
	return fmt.Sprintf("%x", s)
}

func mapStrings(in []string, f func(string) string) []string {
	out := make([]string, len(in))
	for i, s := range in {
		out[i] = f(s)
	}
	return out
}

// flagHash is the FNV-1a hash of one byte per code point from 0 to
// unicode.MaxRune, 1 when f holds and 0 otherwise.
func flagHash(f func(rune) bool) uint64 {
	h := fnv.New64a()
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if f(r) {
			h.Write([]byte{1})
		} else {
			h.Write([]byte{0})
		}
	}
	return h.Sum64()
}

// listHash is the FNV-1a hash of "index:f(input);" over the inputs.
func listHash(in []string, f func(string) string) uint64 {
	h := fnv.New64a()
	for i, s := range in {
		fmt.Fprintf(h, "%d:%s;", i, f(s))
	}
	return h.Sum64()
}

func writeHash(b *strings.Builder, name string, h uint64) {
	fmt.Fprintf(b, "const %s = u64(%d)\n", name, h)
}

func writeStrings(b *strings.Builder, name string, values []string) {
	fmt.Fprintf(b, "const %s = [%d]string[\n", name, len(values))
	for _, v := range values {
		fmt.Fprintf(b, "\t'%s',\n", v)
	}
	b.WriteString("]\n\n")
}
