module multiwindow

const err_render_frame_active = 'multiwindow: window already has an active render attempt'
const err_render_attempt_stale = 'multiwindow: render attempt is stale'
const err_render_sample_count_invalid = 'multiwindow: sample count must be positive'
const err_render_sample_count_unsupported = 'multiwindow: requested sample count is not supported by the backend target'
const err_render_nil_batch_callback = 'multiwindow: render batch callback is nil'
const err_render_nil_pass_callback = 'multiwindow: render pass callback is nil'
const err_render_batch_active = 'multiwindow: a render batch is already active'
const err_render_batch_inactive = 'multiwindow: no render batch is active'
const err_render_batch_stale = 'multiwindow: render batch lease is stale'
const err_render_target_stale = 'multiwindow: render target lease is stale'
const err_render_target_not_eligible = 'multiwindow: render target has no backend ready credit'
const err_render_target_pass_used = 'multiwindow: render target pass was already recorded'
const err_render_metrics_unavailable = 'multiwindow: authoritative render metrics are unavailable'
const err_render_conversion_unavailable = 'multiwindow: authoritative coordinate conversion is unavailable'
const err_render_renderer_failed = 'multiwindow: renderer is in a terminal failed state'
const err_render_anchor_failed = 'multiwindow: renderer recovery anchor failed'
const err_render_terminal_aggregate = 'multiwindow: terminal lifecycle failed'
