import os

const vexe = @VEXE

fn cross_generate(name string, source string) string {
	return cross_generate_with('-os cross', name, source)
}

fn cross_generate_with(flags string, name string, source string) string {
	dir := os.join_path(os.vtmp_dir(), 'v3_cross_output_${name}_${os.getpid()}')
	os.rmdir_all(dir) or {}
	os.mkdir_all(dir) or { panic(err) }
	defer {
		os.rmdir_all(dir) or {}
	}
	src := os.join_path(dir, 'm.v')
	os.write_file(src, source) or { panic(err) }
	out := os.join_path(dir, 'out.c')
	res := os.execute('${os.quoted_path(vexe)} ${flags} -o ${os.quoted_path(out)} ${os.quoted_path(src)}')
	assert res.exit_code == 0, res.output
	return os.read_file(out) or { panic(err) }
}

fn test_cross_output_resolves_top_level_declarations_for_the_host() {
	// A declaration cannot be wrapped in `#if` by the C backend, which collects
	// nested functions, types, constants and globals directly. Keeping both
	// branches emitted both definitions unguarded and the first one silently won,
	// so a top-level `$if` holding declarations stays resolved for the host.
	c_code := cross_generate('top_level', "module main\n\n\$if windows {\n\tfn platform_marker() string {\n\t\treturn 'marker_windows'\n\t}\n} \$else {\n\tfn platform_marker() string {\n\t\treturn 'marker_nix'\n\t}\n}\n\nfn main() {\n\tprintln(platform_marker())\n}\n")
	$if windows {
		assert c_code.contains('marker_windows'), 'the host branch is missing'
		assert !c_code.contains('marker_nix'), 'the branch not taken leaked into the output'
	} $else {
		assert c_code.contains('marker_nix'), 'the host branch is missing'
		assert !c_code.contains('marker_windows'), 'the branch not taken leaked into the output'
	}
}

fn test_cross_output_keeps_directives_of_every_branch_behind_guards() {
	// Directives are the one thing the backend *can* guard, so both branches have
	// to survive: the snapshot is compiled on a machine the generator never saw.
	c_code := cross_generate('directives', "module main\n\n\$if windows {\n\t#include <winsock2.h>\n} \$else {\n\t#include <sys/select.h>\n}\n\nfn main() {\n\tprintln('ok')\n}\n")
	assert c_code.contains('#include <winsock2.h>'), c_code.all_before('typedef')
	assert c_code.contains('#include <sys/select.h>'), c_code.all_before('typedef')
	assert c_code.contains('#if defined(_WIN32)'), 'the windows include is not guarded'
	assert c_code.contains('#if !(defined(_WIN32))'), 'the non-windows include is not guarded'
}

fn test_cross_output_refuses_a_different_pointer_width() {
	// `int`, the type layouts and the literal ranges are baked while generating,
	// so a consumer of another width has to fail loudly instead of disagreeing
	// with the `$if x64`/`$if x32` branches the preprocessor picks.
	c_code := cross_generate('width', "module main\n\nfn main() {\n\tprintln('ok')\n}\n")
	assert c_code.contains('#error "this C was generated by `v -os cross`')
	$if x64 {
		assert c_code.contains('#if !defined(TARGET_IS_64BIT)')
	} $else {
		assert c_code.contains('#if !defined(TARGET_IS_32BIT)')
	}
}

fn test_cross_reports_its_custom_defines_in_the_generated_header() {
	// `gen_vc_ci.yml` greps a freshly generated snapshot for exactly these lines
	// to confirm it was built with `-cross`.
	c_code := cross_generate_with('-cross', 'defines', "module main\n\nfn main() {\n\tprintln('ok')\n}\n")
	assert c_code.contains('Turned ON custom defines: no_backtrace,cross'), c_code.all_before('typedef')
	assert c_code.contains('#define CUSTOM_DEFINE_cross')
	assert c_code.contains('#define CUSTOM_DEFINE_no_backtrace')
}

fn test_cross_is_a_modifier_that_keeps_an_explicit_target() {
	// `v -cross -os windows -cc msvc` builds the Windows snapshot: `-cross` must
	// not be swallowed by, or swallow, the `-os` that follows it.
	c_code := cross_generate_with('-cross -os windows -cc msvc', 'windows', "module main\n\nfn main() {\n\tprintln('ok')\n}\n")
	assert c_code.contains('Turned ON custom defines: no_backtrace,cross'), 'cross mode was lost'
	assert c_code.contains('#define CUSTOM_DEFINE_cross')
	// The target still selected Windows.
	assert c_code.contains('_WIN32'), 'the explicit -os windows target was lost'
}
