module ssa

fn (mut b Builder) register_native_float_format_helpers() {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	b.register_extern('snprintf', b.i32_type, [ptr_i8, b.u64_type, ptr_i8])
	b.register_extern('fabs', b.f64_type, [b.f64_type])
	b.register_extern('floor', b.f64_type, [b.f64_type])
	b.register_extern('strtod', b.f64_type, [ptr_i8, b.m.type_store.get_ptr(ptr_i8)])
	b.register_extern('atoi', b.i32_type, [ptr_i8])
	b.register_extern('free', b.void_type, [ptr_i8])
	for name, format in {
		'v3_f64_fixed':   '%.*f'
		'v3_f64_exp':     '%.*e'
		'v3_f64_general': '%.*g'
	} {
		mut params := [b.f64_type, b.i32_type]
		if name != 'v3_f64_fixed' {
			params << b.i32_type
		}
		id := b.register_synthetic_function(name, b.str_type, params)
		b.generate_native_float_format_body(id, format, name != 'v3_f64_fixed')
	}
	trimmed_id := b.register_synthetic_function('v3_f64_trimmed', b.str_type,
		[b.f64_type, b.i32_type])
	b.generate_native_float_trimmed_body(trimmed_id)
	for name in ['strconv__f32_to_str_l', 'strconv__f32_to_str_l_with_dot', 'f32_to_str_l',
		'f32_to_str_l_with_dot', 'strconv__f64_to_str_l', 'strconv__f64_to_str_l_with_dot',
		'f64_to_str_l', 'f64_to_str_l_with_dot'] {
		value_type := if name.contains('f32') { b.f32_type } else { b.f64_type }
		id := b.register_synthetic_function(name, b.str_type, [value_type])
		b.generate_native_float_string_body(id, value_type)
	}
}

// generate_native_float_format_body uses the platform formatter with an exact
// allocation size. The C variadic ABI carries precision and the floating value.
fn (mut b Builder) generate_native_float_format_body(func_id int, format string, has_upper bool) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	entry := b.m.add_block(func_id, 'float_format_entry')
	value := b.func_add_argument(func_id, b.f64_type, 'value')
	precision := b.func_add_argument(func_id, b.i32_type, 'precision')
	format_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(ptr_i8))
	value_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.f64_type))
	lower_format := b.m.add_value(.string_literal, ptr_i8, format, 0)
	lower_pointer := b.block_instr1(.bitcast, entry, ptr_i8, lower_format)
	b.block_instr2(.store, entry, b.void_type, lower_pointer, format_slot)
	b.block_instr2(.store, entry, b.void_type, value, value_slot)
	ready := b.m.add_block(func_id, 'float_format_ready')
	zero32 := b.m.get_or_add_const(b.i32_type, '0')
	if has_upper {
		upper := b.func_add_argument(func_id, b.i32_type, 'upper')
		use_upper := b.block_instr2(.ne, entry, b.i1_type, upper, zero32)
		uppercase := b.m.add_block(func_id, 'float_format_upper')
		b.block_instr3(.br, entry, b.void_type, use_upper, ValueID(uppercase), ValueID(ready))
		upper_format := b.m.add_value(.string_literal, ptr_i8, format.to_upper_ascii(), 0)
		upper_pointer := b.block_instr1(.bitcast, uppercase, ptr_i8, upper_format)
		b.block_instr2(.store, uppercase, b.void_type, upper_pointer, format_slot)
		b.block_instr1(.jmp, uppercase, b.void_type, ValueID(ready))
	} else {
		// V rounds a precision-zero fixed value away from zero at a half tie.
		zero_float := b.m.get_or_add_const(b.f64_type, '0.0')
		zero_precision := b.block_instr2(.eq, entry, b.i1_type, precision, zero32)
		nonzero_value := b.block_instr2(.ne, entry, b.i1_type, value, zero_float)
		needs_rounding := b.block_instr2(.and_, entry, b.i1_type, zero_precision, nonzero_value)
		round := b.m.add_block(func_id, 'float_format_round')
		negative := b.m.add_block(func_id, 'float_format_negative')
		b.block_instr3(.br, entry, b.void_type, needs_rounding, ValueID(round), ValueID(ready))
		fabs_ref := b.m.add_value(.func_ref, b.f64_type, 'fabs', b.fn_ids['fabs'])
		absolute := b.block_instr2(.call, round, b.f64_type, fabs_ref, value)
		half := b.m.get_or_add_const(b.f64_type, '0.5')
		adjusted := b.block_instr2(.fadd, round, b.f64_type, absolute, half)
		floor_ref := b.m.add_value(.func_ref, b.f64_type, 'floor', b.fn_ids['floor'])
		rounded := b.block_instr2(.call, round, b.f64_type, floor_ref, adjusted)
		b.block_instr2(.store, round, b.void_type, rounded, value_slot)
		is_negative := b.block_instr2(.lt, round, b.i1_type, value, zero_float)
		b.block_instr3(.br, round, b.void_type, is_negative, ValueID(negative), ValueID(ready))
		negative_one := b.m.get_or_add_const(b.f64_type, '-1.0')
		negative_rounded := b.block_instr2(.fmul, negative, b.f64_type, negative_one, rounded)
		b.block_instr2(.store, negative, b.void_type, negative_rounded, value_slot)
		b.block_instr1(.jmp, negative, b.void_type, ValueID(ready))
	}
	chosen_format := b.block_instr1(.load, ready, ptr_i8, format_slot)
	formatted_value := b.block_instr1(.load, ready, b.f64_type, value_slot)
	snprintf_ref := b.m.add_value(.func_ref, b.i32_type, 'snprintf', b.fn_ids['snprintf'])
	nil_buffer := b.m.get_or_add_const(ptr_i8, '0')
	zero_size := b.m.get_or_add_const(b.u64_type, '0')
	needed := b.m.add_instr(.call, ready, b.i32_type,
		[snprintf_ref, nil_buffer, zero_size, chosen_format, precision, formatted_value])
	has_result := b.block_instr2(.ge, ready, b.i1_type, needed, zero32)
	allocate := b.m.add_block(func_id, 'float_format_allocate')
	failure := b.m.add_block(func_id, 'float_format_failed')
	b.block_instr3(.br, ready, b.void_type, has_result, ValueID(allocate), ValueID(failure))
	empty := b.m.add_value(.string_literal, b.str_type, '', 0)
	b.block_instr1(.ret, failure, b.void_type, empty)
	len := b.block_instr1(.zext, allocate, b.i64_type, needed)
	one := b.m.get_or_add_const(b.i64_type, '1')
	size := b.block_instr2(.add, allocate, b.i64_type, len, one)
	malloc_ref := b.m.add_value(.func_ref, b.void_type, 'malloc', b.fn_ids['malloc'])
	out := b.block_instr2(.call, allocate, ptr_i8, malloc_ref, size)
	b.m.add_instr(.call, allocate, b.i32_type,
		[snprintf_ref, out, size, chosen_format, precision, formatted_value])
	result := b.emit_make_string(allocate, out, len, 0)
	b.block_instr1(.ret, allocate, b.void_type, result)
}

// generate_native_float_trimmed_body trims trailing mantissa zeros and preserves
// exponent text, matching interpolation precision without an explicit f verb.
fn (mut b Builder) generate_native_float_trimmed_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	ptr_i64 := b.m.type_store.get_ptr(b.i64_type)
	entry := b.m.add_block(func_id, 'float_trim_entry')
	value := b.func_add_argument(func_id, b.f64_type, 'value')
	precision := b.func_add_argument(func_id, b.i32_type, 'precision')
	s_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.str_type))
	i_slot := b.block_instr0(.alloca, entry, ptr_i64)
	dot_slot := b.block_instr0(.alloca, entry, ptr_i64)
	mant_slot := b.block_instr0(.alloca, entry, ptr_i64)
	end_slot := b.block_instr0(.alloca, entry, ptr_i64)
	prec_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.i32_type))
	zero32 := b.m.get_or_add_const(b.i32_type, '0')
	zero := b.m.get_or_add_const(b.i64_type, '0')
	one := b.m.get_or_add_const(b.i64_type, '1')
	minus_one := b.m.get_or_add_const(b.i64_type, '-1')
	fabs_ref := b.m.add_value(.func_ref, b.f64_type, 'fabs', b.fn_ids['fabs'])
	absolute := b.block_instr2(.call, entry, b.f64_type, fabs_ref, value)
	low := b.m.get_or_add_const(b.f64_type, '0.00001')
	high := b.m.get_or_add_const(b.f64_type, '999999.0')
	at_least_low := b.block_instr2(.ge, entry, b.i1_type, absolute, low)
	below_high := b.block_instr2(.lt, entry, b.i1_type, absolute, high)
	normal_range := b.block_instr2(.and_, entry, b.i1_type, at_least_low, below_high)
	zero_float := b.m.get_or_add_const(b.f64_type, '0.0')
	is_zero := b.block_instr2(.eq, entry, b.i1_type, value, zero_float)
	use_fixed := b.block_instr2(.or_, entry, b.i1_type, normal_range, is_zero)
	fixed := b.m.add_block(func_id, 'float_trim_fixed')
	exp := b.m.add_block(func_id, 'float_trim_exp')
	adjust := b.m.add_block(func_id, 'float_trim_precision')
	exp_call := b.m.add_block(func_id, 'float_trim_exp_call')
	prepare := b.m.add_block(func_id, 'float_trim_prepare')
	b.block_instr3(.br, entry, b.void_type, use_fixed, ValueID(fixed), ValueID(exp))
	fixed_ref := b.m.add_value(.func_ref, b.str_type, 'v3_f64_fixed', b.fn_ids['v3_f64_fixed'])
	fixed_text := b.block_instr3(.call, fixed, b.str_type, fixed_ref, value, precision)
	b.block_instr2(.store, fixed, b.void_type, fixed_text, s_slot)
	b.block_instr1(.jmp, fixed, b.void_type, ValueID(prepare))
	b.block_instr2(.store, exp, b.void_type, zero32, prec_slot)
	positive_precision := b.block_instr2(.gt, exp, b.i1_type, precision, zero32)
	b.block_instr3(.br, exp, b.void_type, positive_precision, ValueID(adjust), ValueID(exp_call))
	one32 := b.m.get_or_add_const(b.i32_type, '1')
	less_precision := b.block_instr2(.sub, adjust, b.i32_type, precision, one32)
	b.block_instr2(.store, adjust, b.void_type, less_precision, prec_slot)
	b.block_instr1(.jmp, adjust, b.void_type, ValueID(exp_call))
	exp_precision := b.block_instr1(.load, exp_call, b.i32_type, prec_slot)
	exp_ref := b.m.add_value(.func_ref, b.str_type, 'v3_f64_exp', b.fn_ids['v3_f64_exp'])
	exp_text := b.block_instr4(.call, exp_call, b.str_type, exp_ref, value, exp_precision, zero32)
	b.block_instr2(.store, exp_call, b.void_type, exp_text, s_slot)
	b.block_instr1(.jmp, exp_call, b.void_type, ValueID(prepare))
	data_ptr := b.block_struct_field_ptr(prepare, s_slot, b.str_type, 0)
	len_ptr := b.block_struct_field_ptr(prepare, s_slot, b.str_type, 1)
	data := b.block_instr1(.load, prepare, ptr_i8, data_ptr)
	len32 := b.block_instr1(.load, prepare, b.i32_type, len_ptr)
	len := b.block_instr1(.zext, prepare, b.i64_type, len32)
	b.block_instr2(.store, prepare, b.void_type, zero, i_slot)
	b.block_instr2(.store, prepare, b.void_type, minus_one, dot_slot)
	b.block_instr2(.store, prepare, b.void_type, len, mant_slot)
	scan := b.m.add_block(func_id, 'float_trim_scan')
	read := b.m.add_block(func_id, 'float_trim_read')
	set_dot := b.m.add_block(func_id, 'float_trim_dot')
	check_exp := b.m.add_block(func_id, 'float_trim_check_exp')
	set_mant := b.m.add_block(func_id, 'float_trim_mant')
	next := b.m.add_block(func_id, 'float_trim_next')
	start_trim := b.m.add_block(func_id, 'float_trim_start')
	original := b.m.add_block(func_id, 'float_trim_original')
	trim := b.m.add_block(func_id, 'float_trim_loop')
	read_last := b.m.add_block(func_id, 'float_trim_last')
	remove_zero := b.m.add_block(func_id, 'float_trim_zero')
	check_dot := b.m.add_block(func_id, 'float_trim_check_dot')
	remove_dot := b.m.add_block(func_id, 'float_trim_remove_dot')
	done := b.m.add_block(func_id, 'float_trim_done')
	b.block_instr1(.jmp, prepare, b.void_type, ValueID(scan))
	i := b.block_instr1(.load, scan, b.i64_type, i_slot)
	more := b.block_instr2(.lt, scan, b.i1_type, i, len)
	b.block_instr3(.br, scan, b.void_type, more, ValueID(read), ValueID(start_trim))
	byte_ptr := b.block_instr2(.add, read, ptr_i8, data, i)
	byte := b.block_instr1(.load, read, b.i8_type, byte_ptr)
	dot_char := b.m.get_or_add_const(b.i8_type, '46')
	is_dot := b.block_instr2(.eq, read, b.i1_type, byte, dot_char)
	b.block_instr3(.br, read, b.void_type, is_dot, ValueID(set_dot), ValueID(check_exp))
	b.block_instr2(.store, set_dot, b.void_type, i, dot_slot)
	b.block_instr1(.jmp, set_dot, b.void_type, ValueID(next))
	exp_char := b.m.get_or_add_const(b.i8_type, '101')
	is_exp := b.block_instr2(.eq, check_exp, b.i1_type, byte, exp_char)
	b.block_instr3(.br, check_exp, b.void_type, is_exp, ValueID(set_mant), ValueID(next))
	b.block_instr2(.store, set_mant, b.void_type, i, mant_slot)
	b.block_instr1(.jmp, set_mant, b.void_type, ValueID(start_trim))
	new_i := b.block_instr2(.add, next, b.i64_type, i, one)
	b.block_instr2(.store, next, b.void_type, new_i, i_slot)
	b.block_instr1(.jmp, next, b.void_type, ValueID(scan))
	dot := b.block_instr1(.load, start_trim, b.i64_type, dot_slot)
	mant := b.block_instr1(.load, start_trim, b.i64_type, mant_slot)
	b.block_instr2(.store, start_trim, b.void_type, mant, end_slot)
	has_dot := b.block_instr2(.ge, start_trim, b.i1_type, dot, zero)
	b.block_instr3(.br, start_trim, b.void_type, has_dot, ValueID(trim), ValueID(original))
	old_string := b.block_instr1(.load, original, b.str_type, s_slot)
	b.block_instr1(.ret, original, b.void_type, old_string)
	end := b.block_instr1(.load, trim, b.i64_type, end_slot)
	dot_end := b.block_instr2(.add, trim, b.i64_type, dot, one)
	has_fraction := b.block_instr2(.gt, trim, b.i1_type, end, dot_end)
	b.block_instr3(.br, trim, b.void_type, has_fraction, ValueID(read_last), ValueID(check_dot))
	last := b.block_instr2(.sub, read_last, b.i64_type, end, one)
	last_ptr := b.block_instr2(.add, read_last, ptr_i8, data, last)
	last_byte := b.block_instr1(.load, read_last, b.i8_type, last_ptr)
	zero_char := b.m.get_or_add_const(b.i8_type, '48')
	is_trailing_zero := b.block_instr2(.eq, read_last, b.i1_type, last_byte, zero_char)
	b.block_instr3(.br, read_last, b.void_type, is_trailing_zero, ValueID(remove_zero), ValueID(check_dot))
	b.block_instr2(.store, remove_zero, b.void_type, last, end_slot)
	b.block_instr1(.jmp, remove_zero, b.void_type, ValueID(trim))
	empty_fraction := b.block_instr2(.eq, check_dot, b.i1_type, end, dot_end)
	b.block_instr3(.br, check_dot, b.void_type, empty_fraction, ValueID(remove_dot), ValueID(done))
	b.block_instr2(.store, remove_dot, b.void_type, dot, end_slot)
	b.block_instr1(.jmp, remove_dot, b.void_type, ValueID(done))
	final_end := b.block_instr1(.load, done, b.i64_type, end_slot)
	suffix_len := b.block_instr2(.sub, done, b.i64_type, len, mant)
	dest := b.block_instr2(.add, done, ptr_i8, data, final_end)
	src := b.block_instr2(.add, done, ptr_i8, data, mant)
	memmove_ref := b.m.add_value(.func_ref, b.void_type, 'memmove', b.fn_ids['memmove'])
	b.block_instr4(.call, done, ptr_i8, memmove_ref, dest, src, suffix_len)
	removed := b.block_instr2(.sub, done, b.i64_type, mant, final_end)
	new_len := b.block_instr2(.sub, done, b.i64_type, len, removed)
	term := b.block_instr2(.add, done, ptr_i8, data, new_len)
	nul := b.m.get_or_add_const(b.i8_type, '0')
	b.block_instr2(.store, done, b.void_type, nul, term)
	result := b.emit_make_string(done, data, new_len, 0)
	b.block_instr1(.ret, done, b.void_type, result)
}
