module ssa

fn (mut b Builder) register_native_string_format_helpers() {
	for name in ['v3_string_zpad', 'v3_f64_zpad'] {
		id := b.register_synthetic_function(name, b.str_type, [b.str_type, b.i32_type])
		b.generate_native_string_zpad_body(id, name == 'v3_f64_zpad')
	}
	for name, value_type in {
		'v3_int_zpad': b.i32_type
		'v3_i64_zpad': b.i64_type
		'v3_u64_zpad': b.u64_type
	} {
		id := b.register_synthetic_function(name, b.str_type, [value_type, b.i32_type])
		b.generate_native_int_zpad_body(id, value_type, name == 'v3_u64_zpad')
	}
	upper_id := b.register_synthetic_function('v3_string_upper_ascii', b.str_type, [b.str_type])
	b.generate_native_upper_ascii_body(upper_id)
	plus_id := b.register_synthetic_function('v3_string_plus_sign', b.str_type, [b.str_type])
	b.generate_native_plus_sign_body(plus_id)
	rpad_id := b.register_synthetic_function('v3_string_rpad_zero', b.str_type, [
		b.str_type,
		b.i32_type,
	])
	b.generate_native_rpad_zero_body(rpad_id)
	char_id := b.register_synthetic_function('v3_char_string', b.str_type, [b.i32_type])
	b.generate_native_char_string_body(char_id)
	b.register_native_float_format_helpers()
}

// generate_native_string_zpad_body places zeros after an optional sign. Formatted
// floats with nonnumeric text, including inf and nan, use the ordinary space pad.
fn (mut b Builder) generate_native_string_zpad_body(func_id int, is_float bool) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	entry := b.m.add_block(func_id, 'zpad_entry')
	s := b.func_add_argument(func_id, b.str_type, 's')
	width := b.func_add_argument(func_id, b.i32_type, 'width')
	s_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.str_type))
	sign_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.i64_type))
	zero64 := b.m.get_or_add_const(b.i64_type, '0')
	b.block_instr2(.store, entry, b.void_type, s, s_slot)
	b.block_instr2(.store, entry, b.void_type, zero64, sign_slot)
	data_ptr := b.block_struct_field_ptr(entry, s_slot, b.str_type, 0)
	len_ptr := b.block_struct_field_ptr(entry, s_slot, b.str_type, 1)
	data := b.block_instr1(.load, entry, ptr_i8, data_ptr)
	len32 := b.block_instr1(.load, entry, b.i32_type, len_ptr)
	len := b.block_instr1(.zext, entry, b.i64_type, len32)
	already_wide := b.block_instr2(.ge, entry, b.i1_type, len32, width)
	original := b.m.add_block(func_id, 'zpad_original')
	check_sign := b.m.add_block(func_id, 'zpad_check_sign')
	read_sign := b.m.add_block(func_id, 'zpad_read_sign')
	pad := b.m.add_block(func_id, 'zpad_allocate')
	if is_float {
		b.block_instr1(.jmp, entry, b.void_type, ValueID(check_sign))
	} else {
		b.block_instr3(.br, entry, b.void_type, already_wide, ValueID(original), ValueID(check_sign))
	}
	b.block_instr1(.ret, original, b.void_type, s)
	sign_done := if is_float { b.m.add_block(func_id, 'zpad_float_check') } else { pad }
	nonempty := b.block_instr2(.gt, check_sign, b.i1_type, len, zero64)
	b.block_instr3(.br, check_sign, b.void_type, nonempty, ValueID(read_sign), ValueID(sign_done))
	first := b.block_instr1(.load, read_sign, b.i8_type, data)
	minus := b.m.get_or_add_const(b.i8_type, '45')
	plus := b.m.get_or_add_const(b.i8_type, '43')
	is_minus := b.block_instr2(.eq, read_sign, b.i1_type, first, minus)
	is_plus := b.block_instr2(.eq, read_sign, b.i1_type, first, plus)
	has_sign := b.block_instr2(.or_, read_sign, b.i1_type, is_minus, is_plus)
	sign_length := b.block_instr1(.zext, read_sign, b.i64_type, has_sign)
	b.block_instr2(.store, read_sign, b.void_type, sign_length, sign_slot)
	b.block_instr1(.jmp, read_sign, b.void_type, ValueID(sign_done))
	if is_float {
		space_pad := b.m.add_block(func_id, 'zpad_float_space_pad')
		check_digit := b.m.add_block(func_id, 'zpad_float_digit')
		check_width := b.m.add_block(func_id, 'zpad_float_width')
		sign := b.block_instr1(.load, sign_done, b.i64_type, sign_slot)
		has_text := b.block_instr2(.gt, sign_done, b.i1_type, len, sign)
		b.block_instr3(.br, sign_done, b.void_type, has_text, ValueID(check_digit),
			ValueID(space_pad))
		digit_ptr := b.block_instr2(.add, check_digit, ptr_i8, data, sign)
		digit := b.block_instr1(.load, check_digit, b.i8_type, digit_ptr)
		ascii_zero := b.m.get_or_add_const(b.i8_type, '48')
		ascii_nine := b.m.get_or_add_const(b.i8_type, '57')
		at_least_zero := b.block_instr2(.ge, check_digit, b.i1_type, digit, ascii_zero)
		at_most_nine := b.block_instr2(.le, check_digit, b.i1_type, digit, ascii_nine)
		is_digit := b.block_instr2(.and_, check_digit, b.i1_type, at_least_zero, at_most_nine)
		b.block_instr3(.br, check_digit, b.void_type, is_digit, ValueID(check_width), ValueID(space_pad))
		b.block_instr3(.br, check_width, b.void_type, already_wide, ValueID(original), ValueID(pad))
		pad_ref := b.m.add_value(.func_ref, b.str_type, 'v3_string_pad', b.fn_ids['v3_string_pad'])
		zero32 := b.m.get_or_add_const(b.i32_type, '0')
		space_result := b.block_instr4(.call, space_pad, b.str_type, pad_ref, s, width, zero32)
		b.block_instr1(.ret, space_pad, b.void_type, space_result)
	}
	width64 := b.block_instr1(.zext, pad, b.i64_type, width)
	sign := b.block_instr1(.load, pad, b.i64_type, sign_slot)
	pad_len := b.block_instr2(.sub, pad, b.i64_type, width64, len)
	one := b.m.get_or_add_const(b.i64_type, '1')
	alloc_len := b.block_instr2(.add, pad, b.i64_type, width64, one)
	malloc_ref := b.m.add_value(.func_ref, b.void_type, 'malloc', b.fn_ids['malloc'])
	out := b.block_instr2(.call, pad, ptr_i8, malloc_ref, alloc_len)
	memcpy_ref := b.m.add_value(.func_ref, b.void_type, 'memcpy', b.fn_ids['memcpy'])
	b.block_instr4(.call, pad, ptr_i8, memcpy_ref, out, data, sign)
	pad_dest := b.block_instr2(.add, pad, ptr_i8, out, sign)
	memset_ref := b.m.add_value(.func_ref, b.void_type, 'memset', b.fn_ids['memset'])
	zero_char := b.m.get_or_add_const(b.i32_type, '48')
	b.block_instr4(.call, pad, ptr_i8, memset_ref, pad_dest, zero_char, pad_len)
	dest := b.block_instr2(.add, pad, ptr_i8, pad_dest, pad_len)
	src := b.block_instr2(.add, pad, ptr_i8, data, sign)
	text_len := b.block_instr2(.sub, pad, b.i64_type, len, sign)
	b.block_instr4(.call, pad, ptr_i8, memcpy_ref, dest, src, text_len)
	term := b.block_instr2(.add, pad, ptr_i8, out, width64)
	nul := b.m.get_or_add_const(b.i8_type, '0')
	b.block_instr2(.store, pad, b.void_type, nul, term)
	result := b.emit_make_string(pad, out, width64, 0)
	b.block_instr1(.ret, pad, b.void_type, result)
}

fn (mut b Builder) generate_native_int_zpad_body(func_id int, value_type TypeID, is_unsigned bool) {
	entry := b.m.add_block(func_id, 'int_zpad_entry')
	value := b.func_add_argument(func_id, value_type, 'value')
	width := b.func_add_argument(func_id, b.i32_type, 'width')
	widened := if value_type == b.i32_type {
		b.block_instr1(.sext, entry, b.i64_type, value)
	} else {
		value
	}
	text := if is_unsigned {
		convert_ref := b.m.add_value(.func_ref, b.str_type, 'strconv__format_uint',
			b.fn_ids['strconv__format_uint'])
		radix := b.m.get_or_add_const(b.i64_type, '10')
		b.block_instr3(.call, entry, b.str_type, convert_ref, widened, radix)
	} else {
		convert_ref := b.m.add_value(.func_ref, b.str_type, 'int_str', b.fn_ids['int_str'])
		b.block_instr2(.call, entry, b.str_type, convert_ref, widened)
	}
	pad_ref := b.m.add_value(.func_ref, b.str_type, 'v3_string_zpad', b.fn_ids['v3_string_zpad'])
	result := b.block_instr3(.call, entry, b.str_type, pad_ref, text, width)
	b.block_instr1(.ret, entry, b.void_type, result)
}

fn (mut b Builder) generate_native_upper_ascii_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	entry := b.m.add_block(func_id, 'upper_entry')
	s := b.func_add_argument(func_id, b.str_type, 's')
	s_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.str_type))
	i_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.i64_type))
	b.block_instr2(.store, entry, b.void_type, s, s_slot)
	data_ptr := b.block_struct_field_ptr(entry, s_slot, b.str_type, 0)
	len_ptr := b.block_struct_field_ptr(entry, s_slot, b.str_type, 1)
	data := b.block_instr1(.load, entry, ptr_i8, data_ptr)
	len32 := b.block_instr1(.load, entry, b.i32_type, len_ptr)
	len := b.block_instr1(.zext, entry, b.i64_type, len32)
	zero := b.m.get_or_add_const(b.i64_type, '0')
	one := b.m.get_or_add_const(b.i64_type, '1')
	alloc_len := b.block_instr2(.add, entry, b.i64_type, len, one)
	malloc_ref := b.m.add_value(.func_ref, b.void_type, 'malloc', b.fn_ids['malloc'])
	out := b.block_instr2(.call, entry, ptr_i8, malloc_ref, alloc_len)
	b.block_instr2(.store, entry, b.void_type, zero, i_slot)
	loop := b.m.add_block(func_id, 'upper_loop')
	body := b.m.add_block(func_id, 'upper_read')
	convert := b.m.add_block(func_id, 'upper_convert')
	unchanged := b.m.add_block(func_id, 'upper_unchanged')
	next := b.m.add_block(func_id, 'upper_next')
	done := b.m.add_block(func_id, 'upper_done')
	b.block_instr1(.jmp, entry, b.void_type, ValueID(loop))
	i := b.block_instr1(.load, loop, b.i64_type, i_slot)
	more := b.block_instr2(.lt, loop, b.i1_type, i, len)
	b.block_instr3(.br, loop, b.void_type, more, ValueID(body), ValueID(done))
	src := b.block_instr2(.add, body, ptr_i8, data, i)
	dest := b.block_instr2(.add, body, ptr_i8, out, i)
	byte := b.block_instr1(.load, body, b.i8_type, src)
	a := b.m.get_or_add_const(b.i8_type, '97')
	z := b.m.get_or_add_const(b.i8_type, '122')
	from_a := b.block_instr2(.ge, body, b.i1_type, byte, a)
	to_z := b.block_instr2(.le, body, b.i1_type, byte, z)
	lower := b.block_instr2(.and_, body, b.i1_type, from_a, to_z)
	b.block_instr3(.br, body, b.void_type, lower, ValueID(convert), ValueID(unchanged))
	difference := b.m.get_or_add_const(b.i8_type, '32')
	capital := b.block_instr2(.sub, convert, b.i8_type, byte, difference)
	b.block_instr2(.store, convert, b.void_type, capital, dest)
	b.block_instr1(.jmp, convert, b.void_type, ValueID(next))
	b.block_instr2(.store, unchanged, b.void_type, byte, dest)
	b.block_instr1(.jmp, unchanged, b.void_type, ValueID(next))
	new_i := b.block_instr2(.add, next, b.i64_type, i, one)
	b.block_instr2(.store, next, b.void_type, new_i, i_slot)
	b.block_instr1(.jmp, next, b.void_type, ValueID(loop))
	term := b.block_instr2(.add, done, ptr_i8, out, len)
	nul := b.m.get_or_add_const(b.i8_type, '0')
	b.block_instr2(.store, done, b.void_type, nul, term)
	result := b.emit_make_string(done, out, len, 0)
	b.block_instr1(.ret, done, b.void_type, result)
}

fn (mut b Builder) generate_native_plus_sign_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	entry := b.m.add_block(func_id, 'plus_sign_entry')
	s := b.func_add_argument(func_id, b.str_type, 's')
	s_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.str_type))
	b.block_instr2(.store, entry, b.void_type, s, s_slot)
	len_ptr := b.block_struct_field_ptr(entry, s_slot, b.str_type, 1)
	len := b.block_instr1(.load, entry, b.i32_type, len_ptr)
	zero := b.m.get_or_add_const(b.i32_type, '0')
	nonempty := b.block_instr2(.gt, entry, b.i1_type, len, zero)
	check_sign := b.m.add_block(func_id, 'plus_sign_check')
	original := b.m.add_block(func_id, 'plus_sign_original')
	append := b.m.add_block(func_id, 'plus_sign_add')
	b.block_instr3(.br, entry, b.void_type, nonempty, ValueID(check_sign), ValueID(append))
	data_ptr := b.block_struct_field_ptr(check_sign, s_slot, b.str_type, 0)
	data := b.block_instr1(.load, check_sign, ptr_i8, data_ptr)
	first := b.block_instr1(.load, check_sign, b.i8_type, data)
	minus := b.m.get_or_add_const(b.i8_type, '45')
	plus := b.m.get_or_add_const(b.i8_type, '43')
	is_minus := b.block_instr2(.eq, check_sign, b.i1_type, first, minus)
	is_plus := b.block_instr2(.eq, check_sign, b.i1_type, first, plus)
	has_sign := b.block_instr2(.or_, check_sign, b.i1_type, is_minus, is_plus)
	b.block_instr3(.br, check_sign, b.void_type, has_sign, ValueID(original), ValueID(append))
	b.block_instr1(.ret, original, b.void_type, s)
	plus_literal := b.m.add_value(.string_literal, b.str_type, '+', 0)
	plus_ref := b.m.add_value(.func_ref, b.str_type, 'string__plus', b.fn_ids['string__plus'])
	result := b.block_instr3(.call, append, b.str_type, plus_ref, plus_literal, s)
	b.block_instr1(.ret, append, b.void_type, result)
}

fn (mut b Builder) generate_native_rpad_zero_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	entry := b.m.add_block(func_id, 'rpad_entry')
	s := b.func_add_argument(func_id, b.str_type, 's')
	width := b.func_add_argument(func_id, b.i32_type, 'width')
	s_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.str_type))
	b.block_instr2(.store, entry, b.void_type, s, s_slot)
	len_ptr := b.block_struct_field_ptr(entry, s_slot, b.str_type, 1)
	len32 := b.block_instr1(.load, entry, b.i32_type, len_ptr)
	already_wide := b.block_instr2(.ge, entry, b.i1_type, len32, width)
	original := b.m.add_block(func_id, 'rpad_original')
	pad := b.m.add_block(func_id, 'rpad_fill')
	b.block_instr3(.br, entry, b.void_type, already_wide, ValueID(original), ValueID(pad))
	b.block_instr1(.ret, original, b.void_type, s)
	pad_ref := b.m.add_value(.func_ref, b.str_type, 'v3_string_pad', b.fn_ids['v3_string_pad'])
	left := b.m.get_or_add_const(b.i32_type, '1')
	result := b.block_instr4(.call, pad, b.str_type, pad_ref, s, width, left)
	b.block_instr2(.store, pad, b.void_type, result, s_slot)
	data_ptr := b.block_struct_field_ptr(pad, s_slot, b.str_type, 0)
	data := b.block_instr1(.load, pad, ptr_i8, data_ptr)
	len := b.block_instr1(.zext, pad, b.i64_type, len32)
	dest := b.block_instr2(.add, pad, ptr_i8, data, len)
	pad_len32 := b.block_instr2(.sub, pad, b.i32_type, width, len32)
	pad_len := b.block_instr1(.zext, pad, b.i64_type, pad_len32)
	zero_char := b.m.get_or_add_const(b.i32_type, '48')
	memset_ref := b.m.add_value(.func_ref, b.void_type, 'memset', b.fn_ids['memset'])
	b.block_instr4(.call, pad, ptr_i8, memset_ref, dest, zero_char, pad_len)
	b.block_instr1(.ret, pad, b.void_type, result)
}
