module ssa

fn (mut b Builder) generate_array_byte_hex_body(func_id int) {
	ptr_u8 := b.m.type_store.get_ptr(b.u8_type)
	entry := b.m.add_block(func_id, 'entry')
	arr := b.func_add_argument(func_id, b.array_type, 'arr')
	arr_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.array_type))
	b.block_instr2(.store, entry, b.void_type, arr, arr_slot)
	data_slot := b.block_struct_field_ptr(entry, arr_slot, b.array_type, 0)
	data := b.block_instr1(.load, entry, ptr_u8, data_slot)
	len := b.block_load_array_int_field(entry, arr_slot, 2)
	zero := b.m.get_or_add_const(b.i64_type, '0')
	one := b.m.get_or_add_const(b.i64_type, '1')
	empty := b.m.add_block(func_id, 'hex_empty')
	allocate := b.m.add_block(func_id, 'hex_allocate')
	is_empty := b.block_instr2(.eq, entry, b.i1_type, len, zero)
	b.block_instr3(.br, entry, b.void_type, is_empty, ValueID(empty), ValueID(allocate))
	empty_string := b.m.add_value(.string_literal, b.str_type, '', 0)
	b.block_instr1(.ret, empty, b.void_type, empty_string)

	output_len := b.block_instr2(.add, allocate, b.i64_type, len, len)
	allocation_len := b.block_instr2(.add, allocate, b.i64_type, output_len, one)
	malloc_ref := b.m.add_value(.func_ref, b.void_type, 'malloc', b.fn_ids['malloc'])
	output := b.block_instr2(.call, allocate, ptr_u8, malloc_ref, allocation_len)
	idx_slot := b.block_instr0(.alloca, allocate, b.m.type_store.get_ptr(b.i64_type))
	b.block_instr2(.store, allocate, b.void_type, zero, idx_slot)
	digits := b.m.add_value(.string_literal, b.str_type, '0123456789abcdef', 0)
	digits_ptr := b.block_instr1(.bitcast, allocate, ptr_u8, digits)
	condition := b.m.add_block(func_id, 'hex_condition')
	body := b.m.add_block(func_id, 'hex_body')
	done := b.m.add_block(func_id, 'hex_done')
	b.block_instr1(.jmp, allocate, b.void_type, ValueID(condition))
	idx := b.block_instr1(.load, condition, b.i64_type, idx_slot)
	more := b.block_instr2(.lt, condition, b.i1_type, idx, len)
	b.block_instr3(.br, condition, b.void_type, more, ValueID(body), ValueID(done))

	input_ptr := b.block_instr2(.add, body, ptr_u8, data, idx)
	byte := b.block_instr1(.load, body, b.u8_type, input_ptr)
	value := b.block_instr1(.zext, body, b.u64_type, byte)
	four := b.m.get_or_add_const(b.u64_type, '4')
	fifteen := b.m.get_or_add_const(b.u64_type, '15')
	high := b.block_instr2(.lshr, body, b.u64_type, value, four)
	low := b.block_instr2(.and_, body, b.u64_type, value, fifteen)
	high_digit_ptr := b.block_instr2(.add, body, ptr_u8, digits_ptr, high)
	low_digit_ptr := b.block_instr2(.add, body, ptr_u8, digits_ptr, low)
	high_digit := b.block_instr1(.load, body, b.u8_type, high_digit_ptr)
	low_digit := b.block_instr1(.load, body, b.u8_type, low_digit_ptr)
	offset := b.block_instr2(.add, body, b.i64_type, idx, idx)
	high_output_ptr := b.block_instr2(.add, body, ptr_u8, output, offset)
	low_output_ptr := b.block_instr2(.add, body, ptr_u8, high_output_ptr, one)
	b.block_instr2(.store, body, b.void_type, high_digit, high_output_ptr)
	b.block_instr2(.store, body, b.void_type, low_digit, low_output_ptr)
	next := b.block_instr2(.add, body, b.i64_type, idx, one)
	b.block_instr2(.store, body, b.void_type, next, idx_slot)
	b.block_instr1(.jmp, body, b.void_type, ValueID(condition))

	terminator := b.block_instr2(.add, done, ptr_u8, output, output_len)
	zero8 := b.m.get_or_add_const(b.u8_type, '0')
	b.block_instr2(.store, done, b.void_type, zero8, terminator)
	string_data := b.block_instr1(.bitcast, done, b.m.type_store.get_ptr(b.i8_type), output)
	result := b.emit_make_string(done, string_data, output_len, 0)
	b.block_instr1(.ret, done, b.void_type, result)
}
