module ssa

// generate_native_float_string_body expands the shortest round-tripping decimal.
fn (mut b Builder) generate_native_float_string_body(func_id int, value_type TypeID) {
	b.generate_native_shortest_float_body(func_id, value_type, true)
}

fn (mut b Builder) native_float_bits(block BlockID, value ValueID) ValueID {
	slot := b.block_instr0(.alloca, block, b.m.type_store.get_ptr(b.f64_type))
	b.block_instr2(.store, block, b.void_type, value, slot)
	bits_ptr := b.block_instr1(.bitcast, block, b.m.type_store.get_ptr(b.u64_type), slot)
	return b.block_instr1(.load, block, b.u64_type, bits_ptr)
}

fn (mut b Builder) native_float_choice(func_id int, block BlockID, typ TypeID, condition ValueID,
	if_true ValueID, if_false ValueID) (BlockID, ValueID) {
	slot := b.block_instr0(.alloca, block, b.m.type_store.get_ptr(typ))
	b.block_instr2(.store, block, b.void_type, if_false, slot)
	choose_true := b.m.add_block(func_id, 'float_choose_true')
	ready := b.m.add_block(func_id, 'float_choice_ready')
	b.block_instr3(.br, block, b.void_type, condition, ValueID(choose_true), ValueID(ready))
	b.block_instr2(.store, choose_true, b.void_type, if_true, slot)
	b.block_instr1(.jmp, choose_true, b.void_type, ValueID(ready))
	value := b.block_instr1(.load, ready, typ, slot)
	return ready, value
}

// Selecting the decimal and rendering it are separate: formatting the original
// binary value again would lose the chosen shortest digits.
fn (mut b Builder) generate_native_shortest_float_body(func_id int, value_type TypeID, expand bool) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	entry := b.m.add_block(func_id, 'float_string_entry')
	value := b.func_add_argument(func_id, value_type, 'value')
	x := if value_type == b.f32_type {
		b.block_instr1(.bitcast, entry, b.f64_type, value)
	} else {
		value
	}
	bits := b.native_float_bits(entry, x)
	shift63 := b.m.get_or_add_const(b.u64_type, '63')
	sign := b.block_instr2(.lshr, entry, b.u64_type, bits, shift63)
	negative := b.block_instr1(.trunc, entry, b.i32_type, sign)
	exponent_mask := b.m.get_or_add_const(b.u64_type, '9218868437227405312')
	exponent := b.block_instr2(.and_, entry, b.u64_type, bits, exponent_mask)
	special := b.block_instr2(.eq, entry, b.i1_type, exponent, exponent_mask)
	special_block := b.m.add_block(func_id, 'float_string_special')
	finite := b.m.add_block(func_id, 'float_string_finite')
	b.block_instr3(.br, entry, b.void_type, special, ValueID(special_block), ValueID(finite))
	mantissa_mask := b.m.get_or_add_const(b.u64_type, '4503599627370495')
	mantissa := b.block_instr2(.and_, special_block, b.u64_type, bits, mantissa_mask)
	zero64 := b.m.get_or_add_const(b.u64_type, '0')
	is_nan := b.block_instr2(.ne, special_block, b.i1_type, mantissa, zero64)
	nan_block := b.m.add_block(func_id, 'float_string_nan')
	inf_block := b.m.add_block(func_id, 'float_string_inf')
	b.block_instr3(.br, special_block, b.void_type, is_nan, ValueID(nan_block), ValueID(inf_block))
	nan_text := b.m.add_value(.string_literal, b.str_type, 'nan', 0)
	b.block_instr1(.ret, nan_block, b.void_type, nan_text)
	zero32 := b.m.get_or_add_const(b.i32_type, '0')
	is_negative := b.block_instr2(.ne, inf_block, b.i1_type, negative, zero32)
	negative_inf := b.m.add_block(func_id, 'float_string_negative_inf')
	positive_inf := b.m.add_block(func_id, 'float_string_positive_inf')
	b.block_instr3(.br, inf_block, b.void_type, is_negative, ValueID(negative_inf), ValueID(positive_inf))
	for block, text in {
		negative_inf: '-inf'
		positive_inf: '+inf'
	} {
		string_value := b.m.add_value(.string_literal, b.str_type, text, 0)
		b.block_instr1(.ret, block, b.void_type, string_value)
	}
	s_slot := b.block_instr0(.alloca, finite, b.m.type_store.get_ptr(b.str_type))
	p_slot := b.block_instr0(.alloca, finite, b.m.type_store.get_ptr(b.i32_type))
	one32 := b.m.get_or_add_const(b.i32_type, '1')
	limit := b.m.get_or_add_const(b.i32_type, if value_type == b.f32_type { '9' } else { '17' })
	b.block_instr2(.store, finite, b.void_type, one32, p_slot)
	format := b.m.add_block(func_id, 'float_string_format')
	next_precision := b.m.add_block(func_id, 'float_string_next_precision')
	finish := b.m.add_block(func_id, 'float_string_finish')
	b.block_instr1(.jmp, finite, b.void_type, ValueID(format))
	precision := b.block_instr1(.load, format, b.i32_type, p_slot)
	general_ref := b.m.add_value(.func_ref, b.str_type, 'v3_f64_general', b.fn_ids['v3_f64_general'])
	s := b.block_instr4(.call, format, b.str_type, general_ref, x, precision, zero32)
	b.block_instr2(.store, format, b.void_type, s, s_slot)
	data_field := b.block_struct_field_ptr(format, s_slot, b.str_type, 0)
	data := b.block_instr1(.load, format, ptr_i8, data_field)
	strtod_ref := b.m.add_value(.func_ref, b.f64_type, 'strtod', b.fn_ids['strtod'])
	nil_end := b.m.get_or_add_const(b.m.type_store.get_ptr(ptr_i8), '0')
	parsed := b.block_instr3(.call, format, b.f64_type, strtod_ref, data, nil_end)
	parsed_value := if value_type == b.f32_type {
		b.block_instr1(.bitcast, format, b.f32_type, parsed)
	} else {
		parsed
	}
	roundtrips := b.block_instr2(.eq, format, b.i1_type, parsed_value, value)
	last_precision := b.block_instr2(.ge, format, b.i1_type, precision, limit)
	finished := b.block_instr2(.or_, format, b.i1_type, roundtrips, last_precision)
	b.block_instr3(.br, format, b.void_type, finished, ValueID(finish), ValueID(next_precision))
	free_ref := b.m.add_value(.func_ref, b.void_type, 'free', b.fn_ids['free'])
	b.block_instr2(.call, next_precision, b.void_type, free_ref, data)
	next_p := b.block_instr2(.add, next_precision, b.i32_type, precision, one32)
	b.block_instr2(.store, next_precision, b.void_type, next_p, p_slot)
	b.block_instr1(.jmp, next_precision, b.void_type, ValueID(format))
	chosen := b.block_instr1(.load, finish, b.str_type, s_slot)
	if !expand {
		b.block_instr1(.ret, finish, b.void_type, chosen)
		return
	}
	auto_precision := b.m.get_or_add_const(b.i32_type, '-1')
	decimal_ref := b.m.add_value(.func_ref, b.str_type, 'v3_float_decimal', b.fn_ids['v3_float_decimal'])
	result := b.block_instr4(.call, finish, b.str_type, decimal_ref, chosen, auto_precision, negative)
	b.block_instr2(.call, finish, b.void_type, free_ref, data)
	b.block_instr1(.ret, finish, b.void_type, result)
}

// generate_native_float_decimal_body renders selected mantissa digits at their
// decimal position. Negative precision preserves every digit and adds .0 to integers.
fn (mut b Builder) generate_native_float_decimal_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	ptr_i64 := b.m.type_store.get_ptr(b.i64_type)
	entry := b.m.add_block(func_id, 'float_decimal_entry')
	source := b.func_add_argument(func_id, b.str_type, 'source')
	precision := b.func_add_argument(func_id, b.i32_type, 'precision')
	negative32 := b.func_add_argument(func_id, b.i32_type, 'negative')
	negative := b.block_instr1(.zext, entry, b.i64_type, negative32)
	requested := b.block_instr1(.sext, entry, b.i64_type, precision)
	source_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.str_type))
	b.block_instr2(.store, entry, b.void_type, source, source_slot)
	data_field := b.block_struct_field_ptr(entry, source_slot, b.str_type, 0)
	len_field := b.block_struct_field_ptr(entry, source_slot, b.str_type, 1)
	data := b.block_instr1(.load, entry, ptr_i8, data_field)
	len32 := b.block_instr1(.load, entry, b.i32_type, len_field)
	len := b.block_instr1(.zext, entry, b.i64_type, len32)
	digits_type := b.m.type_store.register(Type{ kind: .array_t, elem_type: b.i8_type, len: 32 })
	digits_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(digits_type))
	digits := b.block_instr1(.bitcast, entry, ptr_i8, digits_slot)
	index_slot := b.block_instr0(.alloca, entry, ptr_i64)
	count_slot := b.block_instr0(.alloca, entry, ptr_i64)
	point_slot := b.block_instr0(.alloca, entry, ptr_i64)
	exponent_slot := b.block_instr0(.alloca, entry, ptr_i64)
	fraction_slot := b.block_instr0(.alloca, entry, ptr_i64)
	digit_index_slot := b.block_instr0(.alloca, entry, ptr_i64)
	zero := b.m.get_or_add_const(b.i64_type, '0')
	one := b.m.get_or_add_const(b.i64_type, '1')
	minus_one := b.m.get_or_add_const(b.i64_type, '-1')
	b.block_instr2(.store, entry, b.void_type, zero, index_slot)
	b.block_instr2(.store, entry, b.void_type, zero, count_slot)
	b.block_instr2(.store, entry, b.void_type, minus_one, point_slot)
	b.block_instr2(.store, entry, b.void_type, zero, exponent_slot)
	scan := b.m.add_block(func_id, 'float_decimal_scan')
	read := b.m.add_block(func_id, 'float_decimal_read')
	append_digit := b.m.add_block(func_id, 'float_decimal_digit')
	check_dot := b.m.add_block(func_id, 'float_decimal_check_dot')
	set_dot := b.m.add_block(func_id, 'float_decimal_dot')
	check_exp := b.m.add_block(func_id, 'float_decimal_check_exp')
	set_exp := b.m.add_block(func_id, 'float_decimal_exponent')
	next := b.m.add_block(func_id, 'float_decimal_next')
	finish_scan := b.m.add_block(func_id, 'float_decimal_finish_scan')
	no_dot := b.m.add_block(func_id, 'float_decimal_no_dot')
	mut position := b.m.add_block(func_id, 'float_decimal_position')
	b.block_instr1(.jmp, entry, b.void_type, ValueID(scan))
	index := b.block_instr1(.load, scan, b.i64_type, index_slot)
	more := b.block_instr2(.lt, scan, b.i1_type, index, len)
	b.block_instr3(.br, scan, b.void_type, more, ValueID(read), ValueID(finish_scan))
	byte_ptr := b.block_instr2(.add, read, ptr_i8, data, index)
	byte := b.block_instr1(.load, read, b.i8_type, byte_ptr)
	char_zero := b.m.get_or_add_const(b.i8_type, '48')
	char_nine := b.m.get_or_add_const(b.i8_type, '57')
	at_least_zero := b.block_instr2(.ge, read, b.i1_type, byte, char_zero)
	at_most_nine := b.block_instr2(.le, read, b.i1_type, byte, char_nine)
	is_digit := b.block_instr2(.and_, read, b.i1_type, at_least_zero, at_most_nine)
	b.block_instr3(.br, read, b.void_type, is_digit, ValueID(append_digit), ValueID(check_dot))
	count := b.block_instr1(.load, append_digit, b.i64_type, count_slot)
	digit_ptr := b.block_instr2(.add, append_digit, ptr_i8, digits, count)
	b.block_instr2(.store, append_digit, b.void_type, byte, digit_ptr)
	new_count := b.block_instr2(.add, append_digit, b.i64_type, count, one)
	b.block_instr2(.store, append_digit, b.void_type, new_count, count_slot)
	b.block_instr1(.jmp, append_digit, b.void_type, ValueID(next))
	char_dot := b.m.get_or_add_const(b.i8_type, '46')
	is_dot := b.block_instr2(.eq, check_dot, b.i1_type, byte, char_dot)
	b.block_instr3(.br, check_dot, b.void_type, is_dot, ValueID(set_dot), ValueID(check_exp))
	dot_count := b.block_instr1(.load, set_dot, b.i64_type, count_slot)
	b.block_instr2(.store, set_dot, b.void_type, dot_count, point_slot)
	b.block_instr1(.jmp, set_dot, b.void_type, ValueID(next))
	char_e := b.m.get_or_add_const(b.i8_type, '101')
	char_upper_e := b.m.get_or_add_const(b.i8_type, '69')
	is_e := b.block_instr2(.eq, check_exp, b.i1_type, byte, char_e)
	is_upper_e := b.block_instr2(.eq, check_exp, b.i1_type, byte, char_upper_e)
	has_exp := b.block_instr2(.or_, check_exp, b.i1_type, is_e, is_upper_e)
	b.block_instr3(.br, check_exp, b.void_type, has_exp, ValueID(set_exp), ValueID(next))
	exponent_index := b.block_instr2(.add, set_exp, b.i64_type, index, one)
	exponent_ptr := b.block_instr2(.add, set_exp, ptr_i8, data, exponent_index)
	atoi_ref := b.m.add_value(.func_ref, b.i32_type, 'atoi', b.fn_ids['atoi'])
	exponent32 := b.block_instr2(.call, set_exp, b.i32_type, atoi_ref, exponent_ptr)
	exponent := b.block_instr1(.sext, set_exp, b.i64_type, exponent32)
	b.block_instr2(.store, set_exp, b.void_type, exponent, exponent_slot)
	b.block_instr1(.jmp, set_exp, b.void_type, ValueID(finish_scan))
	new_index := b.block_instr2(.add, next, b.i64_type, index, one)
	b.block_instr2(.store, next, b.void_type, new_index, index_slot)
	b.block_instr1(.jmp, next, b.void_type, ValueID(scan))
	point := b.block_instr1(.load, finish_scan, b.i64_type, point_slot)
	missing_dot := b.block_instr2(.lt, finish_scan, b.i1_type, point, zero)
	b.block_instr3(.br, finish_scan, b.void_type, missing_dot, ValueID(no_dot), ValueID(position))
	final_count := b.block_instr1(.load, no_dot, b.i64_type, count_slot)
	b.block_instr2(.store, no_dot, b.void_type, final_count, point_slot)
	b.block_instr1(.jmp, no_dot, b.void_type, ValueID(position))
	decimal_point := b.block_instr1(.load, position, b.i64_type, point_slot)
	final_exp := b.block_instr1(.load, position, b.i64_type, exponent_slot)
	decimal_pos := b.block_instr2(.add, position, b.i64_type, decimal_point, final_exp)
	whole_positive := b.block_instr2(.gt, position, b.i1_type, decimal_pos, zero)
	whole_ready, whole := b.native_float_choice(func_id, position, b.i64_type, whole_positive,
		decimal_pos, one)
	position = whole_ready
	b.block_instr2(.store, position, b.void_type, requested, fraction_slot)
	auto := b.block_instr2(.lt, position, b.i1_type, requested, zero)
	mut auto_fraction := b.m.add_block(func_id, 'float_decimal_auto_fraction')
	allocate := b.m.add_block(func_id, 'float_decimal_allocate')
	b.block_instr3(.br, position, b.void_type, auto, ValueID(auto_fraction), ValueID(allocate))
	digit_count := b.block_instr1(.load, auto_fraction, b.i64_type, count_slot)
	remaining := b.block_instr2(.sub, auto_fraction, b.i64_type, digit_count, decimal_pos)
	has_remaining := b.block_instr2(.gt, auto_fraction, b.i1_type, remaining, zero)
	auto_ready, auto_digits := b.native_float_choice(func_id, auto_fraction, b.i64_type,
		has_remaining, remaining, one)
	auto_fraction = auto_ready
	b.block_instr2(.store, auto_fraction, b.void_type, auto_digits, fraction_slot)
	b.block_instr1(.jmp, auto_fraction, b.void_type, ValueID(allocate))
	fraction := b.block_instr1(.load, allocate, b.i64_type, fraction_slot)
	has_fraction := b.block_instr2(.gt, allocate, b.i1_type, fraction, zero)
	dot_width := b.block_instr1(.zext, allocate, b.i64_type, has_fraction)
	total_digits := b.block_instr2(.add, allocate, b.i64_type, whole, fraction)
	with_sign := b.block_instr2(.add, allocate, b.i64_type, total_digits, negative)
	out_len := b.block_instr2(.add, allocate, b.i64_type, with_sign, dot_width)
	size := b.block_instr2(.add, allocate, b.i64_type, out_len, one)
	malloc_ref := b.m.add_value(.func_ref, ptr_i8, 'malloc', b.fn_ids['malloc'])
	out := b.block_instr2(.call, allocate, ptr_i8, malloc_ref, size)
	negative_flag := b.block_instr2(.ne, allocate, b.i1_type, negative, zero)
	set_sign := b.m.add_block(func_id, 'float_decimal_set_sign')
	check_fraction := b.m.add_block(func_id, 'float_decimal_fraction')
	b.block_instr3(.br, allocate, b.void_type, negative_flag, ValueID(set_sign), ValueID(check_fraction))
	minus := b.m.get_or_add_const(b.i8_type, '45')
	b.block_instr2(.store, set_sign, b.void_type, minus, out)
	b.block_instr1(.jmp, set_sign, b.void_type, ValueID(check_fraction))
	write_dot := b.m.add_block(func_id, 'float_decimal_write_dot')
	start_write := b.m.add_block(func_id, 'float_decimal_start_write')
	b.block_instr3(.br, check_fraction, b.void_type, has_fraction, ValueID(write_dot), ValueID(start_write))
	dot_offset := b.block_instr2(.add, write_dot, b.i64_type, negative, whole)
	dot_ptr := b.block_instr2(.add, write_dot, ptr_i8, out, dot_offset)
	b.block_instr2(.store, write_dot, b.void_type, char_dot, dot_ptr)
	b.block_instr1(.jmp, write_dot, b.void_type, ValueID(start_write))
	b.block_instr2(.store, start_write, b.void_type, zero, index_slot)
	write_loop := b.m.add_block(func_id, 'float_decimal_write_loop')
	write_index := b.m.add_block(func_id, 'float_decimal_write_index')
	mut whole_index := b.m.add_block(func_id, 'float_decimal_whole_index')
	fraction_index := b.m.add_block(func_id, 'float_decimal_fraction_index')
	choose_digit := b.m.add_block(func_id, 'float_decimal_choose_digit')
	copy_digit := b.m.add_block(func_id, 'float_decimal_copy_digit')
	write_zero := b.m.add_block(func_id, 'float_decimal_write_zero')
	next_digit := b.m.add_block(func_id, 'float_decimal_next_digit')
	done := b.m.add_block(func_id, 'float_decimal_done')
	b.block_instr1(.jmp, start_write, b.void_type, ValueID(write_loop))
	out_index := b.block_instr1(.load, write_loop, b.i64_type, index_slot)
	write_more := b.block_instr2(.lt, write_loop, b.i1_type, out_index, total_digits)
	b.block_instr3(.br, write_loop, b.void_type, write_more, ValueID(write_index), ValueID(done))
	in_whole := b.block_instr2(.lt, write_index, b.i1_type, out_index, whole)
	b.block_instr3(.br, write_index, b.void_type, in_whole, ValueID(whole_index), ValueID(fraction_index))
	whole_index_ready, whole_digit := b.native_float_choice(func_id, whole_index, b.i64_type,
		whole_positive, out_index, minus_one)
	whole_index = whole_index_ready
	b.block_instr2(.store, whole_index, b.void_type, whole_digit, digit_index_slot)
	b.block_instr1(.jmp, whole_index, b.void_type, ValueID(choose_digit))
	fraction_index0 := b.block_instr2(.sub, fraction_index, b.i64_type, out_index, whole)
	fraction_digit := b.block_instr2(.add, fraction_index, b.i64_type, decimal_pos, fraction_index0)
	b.block_instr2(.store, fraction_index, b.void_type, fraction_digit, digit_index_slot)
	b.block_instr1(.jmp, fraction_index, b.void_type, ValueID(choose_digit))
	input_index := b.block_instr1(.load, choose_digit, b.i64_type, digit_index_slot)
	input_count := b.block_instr1(.load, choose_digit, b.i64_type, count_slot)
	nonnegative_index := b.block_instr2(.ge, choose_digit, b.i1_type, input_index, zero)
	before_end := b.block_instr2(.lt, choose_digit, b.i1_type, input_index, input_count)
	has_digit := b.block_instr2(.and_, choose_digit, b.i1_type, nonnegative_index, before_end)
	after_whole := b.block_instr2(.ge, choose_digit, b.i1_type, out_index, whole)
	skip_dot := b.block_instr1(.zext, choose_digit, b.i64_type, after_whole)
	signed_offset := b.block_instr2(.add, choose_digit, b.i64_type, out_index, negative)
	output_offset := b.block_instr2(.add, choose_digit, b.i64_type, signed_offset, skip_dot)
	output_ptr := b.block_instr2(.add, choose_digit, ptr_i8, out, output_offset)
	b.block_instr3(.br, choose_digit, b.void_type, has_digit, ValueID(copy_digit), ValueID(write_zero))
	input_ptr := b.block_instr2(.add, copy_digit, ptr_i8, digits, input_index)
	input_digit := b.block_instr1(.load, copy_digit, b.i8_type, input_ptr)
	b.block_instr2(.store, copy_digit, b.void_type, input_digit, output_ptr)
	b.block_instr1(.jmp, copy_digit, b.void_type, ValueID(next_digit))
	b.block_instr2(.store, write_zero, b.void_type, char_zero, output_ptr)
	b.block_instr1(.jmp, write_zero, b.void_type, ValueID(next_digit))
	next_out_index := b.block_instr2(.add, next_digit, b.i64_type, out_index, one)
	b.block_instr2(.store, next_digit, b.void_type, next_out_index, index_slot)
	b.block_instr1(.jmp, next_digit, b.void_type, ValueID(write_loop))
	terminator := b.block_instr2(.add, done, ptr_i8, out, out_len)
	nul := b.m.get_or_add_const(b.i8_type, '0')
	b.block_instr2(.store, done, b.void_type, nul, terminator)
	result := b.emit_make_string(done, out, out_len, 0)
	b.block_instr1(.ret, done, b.void_type, result)
}
