module ssa

// generate_native_map_get_and_set_body inserts the fallback only for a missing
// key, then returns the map's writable value slot used by compound assignments.
fn (mut b Builder) generate_native_map_get_and_set_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	entry := b.m.add_block(func_id, 'map_get_and_set_entry')
	map_ptr := b.func_add_argument(func_id, b.m.type_store.get_ptr(b.map_type), 'map')
	key := b.func_add_argument(func_id, ptr_i8, 'key')
	fallback := b.func_add_argument(func_id, ptr_i8, 'fallback')
	lookup := b.m.add_value(.func_ref, ptr_i8, 'map__get_check', b.fn_ids['map__get_check'])
	existing := b.block_instr3(.call, entry, ptr_i8, lookup, map_ptr, key)
	nil_ptr := b.m.get_or_add_const(ptr_i8, '0')
	found := b.block_instr2(.ne, entry, b.i1_type, existing, nil_ptr)
	return_existing := b.m.add_block(func_id, 'map_get_and_set_found')
	insert := b.m.add_block(func_id, 'map_get_and_set_insert')
	b.block_instr3(.br, entry, b.void_type, found, ValueID(return_existing), ValueID(insert))
	b.block_instr1(.ret, return_existing, b.void_type, existing)
	set := b.m.add_value(.func_ref, b.void_type, 'map__set', b.fn_ids['map__set'])
	b.block_instr4(.call, insert, b.void_type, set, map_ptr, key, fallback)
	inserted := b.block_instr3(.call, insert, ptr_i8, lookup, map_ptr, key)
	b.block_instr1(.ret, insert, b.void_type, inserted)
}

// Native maps have a different storage layout from the C runtime. Backtraces use
// the platform unwinder directly rather than TinyCC's embedded runtime.
fn (mut b Builder) register_native_runtime_helpers() {
	b.register_native_telemetry_helpers()
	for name in ['map_map_eq', 'v3_map_map_eq'] {
		eq_id := b.register_synthetic_function(name, b.i1_type, [b.map_type, b.map_type])
		b.generate_native_map_eq_body(eq_id)
	}
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	b.register_extern('backtrace', b.i32_type, [ptr_i8, b.i32_type])
	b.register_extern('backtrace_symbols_fd', b.void_type, [ptr_i8, b.i32_type, b.i32_type])
	skip_id := b.register_synthetic_function('print_backtrace_skipping_top_frames', b.i1_type,
		[b.i32_type])
	b.generate_native_backtrace_body(skip_id)
	print_id := b.register_synthetic_function('print_backtrace', b.void_type, []TypeID{})
	entry := b.m.add_block(print_id, 'backtrace_entry')
	skip := b.m.get_or_add_const(b.i32_type, '2')
	callee := b.m.add_value(.func_ref, b.i1_type, 'print_backtrace_skipping_top_frames', skip_id)
	b.block_instr2(.call, entry, b.i1_type, callee, skip)
	b.block_instr0(.ret, entry, b.void_type)
}

fn (mut b Builder) generate_native_backtrace_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	buffer_type := b.m.type_store.get_array(ptr_i8, 100)
	entry := b.m.add_block(func_id, 'backtrace_capture')
	requested_skip := b.func_add_argument(func_id, b.i32_type, 'skipframes')
	buffer := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(buffer_type))
	buffer_ptr := b.block_instr1(.bitcast, entry, ptr_i8, buffer)
	capacity := b.m.get_or_add_const(b.i32_type, '100')
	capture := b.m.add_value(.func_ref, b.i32_type, 'backtrace', b.fn_ids['backtrace'])
	count := b.block_instr3(.call, entry, b.i32_type, capture, buffer_ptr, capacity)
	internal_frames := b.m.get_or_add_const(b.i32_type, '2')
	skip := b.block_instr2(.add, entry, b.i32_type, requested_skip, internal_frames)
	has_frames := b.block_instr2(.gt, entry, b.i1_type, count, skip)
	print_block := b.m.add_block(func_id, 'backtrace_print')
	empty_block := b.m.add_block(func_id, 'backtrace_empty')
	b.block_instr3(.br, entry, b.void_type, has_frames, ValueID(print_block), ValueID(empty_block))
	skip64 := b.block_instr1(.sext, print_block, b.i64_type, skip)
	stride := b.m.get_or_add_const(b.i64_type, '8')
	offset := b.block_instr2(.mul, print_block, b.i64_type, skip64, stride)
	frames := b.block_instr2(.add, print_block, ptr_i8, buffer_ptr, offset)
	remaining := b.block_instr2(.sub, print_block, b.i32_type, count, skip)
	stderr := b.m.get_or_add_const(b.i32_type, '2')
	print_ref := b.m.add_value(.func_ref, b.void_type, 'backtrace_symbols_fd',
		b.fn_ids['backtrace_symbols_fd'])
	b.block_instr4(.call, print_block, b.void_type, print_ref, frames, remaining, stderr)
	true_value := b.m.get_or_add_const(b.i1_type, '1')
	false_value := b.m.get_or_add_const(b.i1_type, '0')
	b.block_instr1(.ret, print_block, b.void_type, true_value)
	b.block_instr1(.ret, empty_block, b.void_type, false_value)
}

fn (mut b Builder) generate_native_map_eq_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	ptr_map := b.m.type_store.get_ptr(b.map_type)
	ptr_i64 := b.m.type_store.get_ptr(b.i64_type)
	ptr_state := b.m.type_store.get_ptr(b.map_state_type)
	entry := b.m.add_block(func_id, 'map_eq_entry')
	left := b.func_add_argument(func_id, b.map_type, 'left')
	right := b.func_add_argument(func_id, b.map_type, 'right')
	left_slot := b.block_instr0(.alloca, entry, ptr_map)
	right_slot := b.block_instr0(.alloca, entry, ptr_map)
	left_len_slot := b.block_instr0(.alloca, entry, ptr_i64)
	right_len_slot := b.block_instr0(.alloca, entry, ptr_i64)
	i_slot := b.block_instr0(.alloca, entry, ptr_i64)
	zero := b.m.get_or_add_const(b.i64_type, '0')
	one := b.m.get_or_add_const(b.i64_type, '1')
	nil_state := b.m.get_or_add_const(ptr_state, '0')
	nil_data := b.m.get_or_add_const(ptr_i8, '0')
	b.block_instr2(.store, entry, b.void_type, left, left_slot)
	b.block_instr2(.store, entry, b.void_type, right, right_slot)
	b.block_instr2(.store, entry, b.void_type, zero, left_len_slot)
	b.block_instr2(.store, entry, b.void_type, zero, right_len_slot)
	b.block_instr2(.store, entry, b.void_type, zero, i_slot)
	left_state := b.map_state_ptr(entry, left_slot)
	right_state := b.map_state_ptr(entry, right_slot)
	has_left := b.block_instr2(.ne, entry, b.i1_type, left_state, nil_state)
	read_left := b.m.add_block(func_id, 'map_eq_left_len')
	check_right := b.m.add_block(func_id, 'map_eq_check_right')
	read_right := b.m.add_block(func_id, 'map_eq_right_len')
	check_lengths := b.m.add_block(func_id, 'map_eq_lengths')
	check_empty := b.m.add_block(func_id, 'map_eq_empty')
	loop := b.m.add_block(func_id, 'map_eq_loop')
	body := b.m.add_block(func_id, 'map_eq_lookup')
	compare := b.m.add_block(func_id, 'map_eq_compare')
	next := b.m.add_block(func_id, 'map_eq_next')
	return_true := b.m.add_block(func_id, 'map_eq_true')
	return_false := b.m.add_block(func_id, 'map_eq_false')
	b.block_instr3(.br, entry, b.void_type, has_left, ValueID(read_left), ValueID(check_right))
	left_len_ptr := b.map_state_field_ptr(read_left, left_state, 3)
	left_count := b.block_instr1(.load, read_left, b.i64_type, left_len_ptr)
	b.block_instr2(.store, read_left, b.void_type, left_count, left_len_slot)
	b.block_instr1(.jmp, read_left, b.void_type, ValueID(check_right))
	has_right := b.block_instr2(.ne, check_right, b.i1_type, right_state, nil_state)
	b.block_instr3(.br, check_right, b.void_type, has_right, ValueID(read_right),
		ValueID(check_lengths))
	right_len_ptr := b.map_state_field_ptr(read_right, right_state, 3)
	right_count := b.block_instr1(.load, read_right, b.i64_type, right_len_ptr)
	b.block_instr2(.store, read_right, b.void_type, right_count, right_len_slot)
	b.block_instr1(.jmp, read_right, b.void_type, ValueID(check_lengths))
	left_len := b.block_instr1(.load, check_lengths, b.i64_type, left_len_slot)
	right_len := b.block_instr1(.load, check_lengths, b.i64_type, right_len_slot)
	same_len := b.block_instr2(.eq, check_lengths, b.i1_type, left_len, right_len)
	b.block_instr3(.br, check_lengths, b.void_type, same_len, ValueID(check_empty),
		ValueID(return_false))
	is_empty := b.block_instr2(.eq, check_empty, b.i1_type, left_len, zero)
	b.block_instr3(.br, check_empty, b.void_type, is_empty, ValueID(return_true), ValueID(loop))
	i := b.block_instr1(.load, loop, b.i64_type, i_slot)
	more := b.block_instr2(.lt, loop, b.i1_type, i, left_len)
	b.block_instr3(.br, loop, b.void_type, more, ValueID(body), ValueID(return_true))
	keys_ptr := b.map_state_field_ptr(body, left_state, 0)
	values_ptr := b.map_state_field_ptr(body, left_state, 1)
	key_size_ptr := b.map_state_field_ptr(body, left_state, 4)
	value_size_ptr := b.map_state_field_ptr(body, left_state, 5)
	keys := b.block_instr1(.load, body, ptr_i8, keys_ptr)
	values := b.block_instr1(.load, body, ptr_i8, values_ptr)
	key_size := b.block_instr1(.load, body, b.i64_type, key_size_ptr)
	value_size := b.block_instr1(.load, body, b.i64_type, value_size_ptr)
	key_offset := b.block_instr2(.mul, body, b.i64_type, i, key_size)
	value_offset := b.block_instr2(.mul, body, b.i64_type, i, value_size)
	key := b.block_instr2(.add, body, ptr_i8, keys, key_offset)
	left_value := b.block_instr2(.add, body, ptr_i8, values, value_offset)
	lookup := b.m.add_value(.func_ref, ptr_i8, 'map__get_check', b.fn_ids['map__get_check'])
	right_value := b.block_instr3(.call, body, ptr_i8, lookup, right_slot, key)
	found := b.block_instr2(.ne, body, b.i1_type, right_value, nil_data)
	b.block_instr3(.br, body, b.void_type, found, ValueID(compare), ValueID(return_false))
	memcmp_ref := b.m.add_value(.func_ref, b.i64_type, 'memcmp', b.fn_ids['memcmp'])
	comparison := b.block_instr4(.call, compare, b.i64_type, memcmp_ref, left_value, right_value,
		value_size)
	equal := b.block_instr2(.eq, compare, b.i1_type, comparison, zero)
	b.block_instr3(.br, compare, b.void_type, equal, ValueID(next), ValueID(return_false))
	next_i := b.block_instr2(.add, next, b.i64_type, i, one)
	b.block_instr2(.store, next, b.void_type, next_i, i_slot)
	b.block_instr1(.jmp, next, b.void_type, ValueID(loop))
	true_value := b.m.get_or_add_const(b.i1_type, '1')
	false_value := b.m.get_or_add_const(b.i1_type, '0')
	b.block_instr1(.ret, return_true, b.void_type, true_value)
	b.block_instr1(.ret, return_false, b.void_type, false_value)
}
