module ssa

// The index stores dense key positions, so growing the key/value vectors keeps
// aliases and iteration order unchanged. A lookup indexes only new entries.
fn (mut b Builder) register_native_map_index_helpers() {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	ptr_state := b.m.type_store.get_ptr(b.map_state_type)
	hash_id := b.register_synthetic_function('v3_native_map_hash_key', b.i64_type,
		[ptr_state, ptr_i8])
	b.generate_native_map_hash_body(hash_id)
	index_id := b.register_synthetic_function('v3_native_map_index', b.void_type, [ptr_state])
	b.generate_native_map_index_body(index_id)
}

fn (mut b Builder) invalidate_native_map_index(block BlockID, state ValueID) {
	indexed_len_ptr := b.map_state_field_ptr(block, state, 8)
	invalid := b.m.get_or_add_const(b.i64_type, '-1')
	b.block_instr2(.store, block, b.void_type, invalid, indexed_len_ptr)
}

fn (mut b Builder) native_map_key_hash(block BlockID, state ValueID, key ValueID) ValueID {
	ref := b.m.add_value(.func_ref, b.i64_type, 'v3_native_map_hash_key',
		b.fn_ids['v3_native_map_hash_key'])
	return b.block_instr3(.call, block, b.i64_type, ref, state, key)
}

fn (mut b Builder) generate_native_map_hash_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	entry := b.m.add_block(func_id, 'map_hash_entry')
	state := b.func_add_argument(func_id, b.m.type_store.get_ptr(b.map_state_type), 'state')
	key := b.func_add_argument(func_id, ptr_i8, 'key')
	size_ptr := b.map_state_field_ptr(entry, state, 4)
	size := b.block_instr1(.load, entry, b.i64_type, size_ptr)
	string_size := b.m.get_or_add_const(b.i64_type, '16')
	is_string := b.block_instr2(.eq, entry, b.i1_type, size, string_size)
	string_block := b.m.add_block(func_id, 'map_hash_string')
	bytes_block := b.m.add_block(func_id, 'map_hash_bytes')
	b.block_instr3(.br, entry, b.void_type, is_string, ValueID(string_block), ValueID(bytes_block))
	ref := b.m.add_value(.func_ref, b.i64_type, 'wyhash', b.fn_ids['wyhash'])
	zero := b.m.get_or_add_const(b.i64_type, '0')
	secret := b.m.get_or_add_const(b.m.type_store.get_ptr(b.u64_type), '0')
	string_ptr := b.block_instr1(.bitcast, string_block, b.m.type_store.get_ptr(b.str_type),
		key)
	data_ptr := b.block_struct_field_ptr(string_block, string_ptr, b.str_type, 0)
	len_ptr := b.block_struct_field_ptr(string_block, string_ptr, b.str_type, 1)
	data := b.block_instr1(.load, string_block, ptr_i8, data_ptr)
	len32 := b.block_instr1(.load, string_block, b.i32_type, len_ptr)
	len := b.block_instr1(.zext, string_block, b.i64_type, len32)
	string_hash := b.m.add_instr(.call, string_block, b.i64_type, [ref, data, len, zero, secret])
	b.block_instr1(.ret, string_block, b.void_type, string_hash)
	bytes_hash := b.m.add_instr(.call, bytes_block, b.i64_type, [ref, key, size, zero, secret])
	b.block_instr1(.ret, bytes_block, b.void_type, bytes_hash)
}

fn (mut b Builder) generate_native_map_index_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	ptr_i64 := b.m.type_store.get_ptr(b.i64_type)
	entry := b.m.add_block(func_id, 'map_index_entry')
	state := b.func_add_argument(func_id, b.m.type_store.get_ptr(b.map_state_type), 'state')
	keys_ptr := b.map_state_field_ptr(entry, state, 0)
	len_ptr := b.map_state_field_ptr(entry, state, 3)
	key_size_ptr := b.map_state_field_ptr(entry, state, 4)
	slots_ptr := b.map_state_field_ptr(entry, state, 6)
	cap_ptr := b.map_state_field_ptr(entry, state, 7)
	indexed_len_ptr := b.map_state_field_ptr(entry, state, 8)
	len := b.block_instr1(.load, entry, b.i64_type, len_ptr)
	cap := b.block_instr1(.load, entry, b.i64_type, cap_ptr)
	indexed_len := b.block_instr1(.load, entry, b.i64_type, indexed_len_ptr)
	zero := b.m.get_or_add_const(b.i64_type, '0')
	one := b.m.get_or_add_const(b.i64_type, '1')
	two := b.m.get_or_add_const(b.i64_type, '2')
	eight := b.m.get_or_add_const(b.i64_type, '8')
	sixteen := b.m.get_or_add_const(b.i64_type, '16')
	capacity_needed := b.block_instr2(.mul, entry, b.i64_type, len, two)
	has_capacity := b.block_instr2(.ge, entry, b.i1_type, cap, capacity_needed)
	has_table := b.block_instr2(.gt, entry, b.i1_type, cap, zero)
	valid := b.block_instr2(.ge, entry, b.i1_type, indexed_len, zero)
	sized := b.block_instr2(.and_, entry, b.i1_type, has_table, has_capacity)
	reuse := b.block_instr2(.and_, entry, b.i1_type, sized, valid)
	capacity_slot := b.block_instr0(.alloca, entry, ptr_i64)
	i_slot := b.block_instr0(.alloca, entry, ptr_i64)
	slot_slot := b.block_instr0(.alloca, entry, ptr_i64)
	rebuild := b.m.add_block(func_id, 'map_index_rebuild')
	capacity_loop := b.m.add_block(func_id, 'map_index_capacity_loop')
	capacity_grow := b.m.add_block(func_id, 'map_index_capacity_grow')
	allocate := b.m.add_block(func_id, 'map_index_allocate')
	prepare := b.m.add_block(func_id, 'map_index_prepare')
	loop := b.m.add_block(func_id, 'map_index_loop')
	body := b.m.add_block(func_id, 'map_index_body')
	probe := b.m.add_block(func_id, 'map_index_probe')
	probe_next := b.m.add_block(func_id, 'map_index_probe_next')
	store := b.m.add_block(func_id, 'map_index_store')
	finish := b.m.add_block(func_id, 'map_index_finish')
	b.block_instr3(.br, entry, b.void_type, reuse, ValueID(prepare), ValueID(rebuild))
	b.block_instr2(.store, rebuild, b.void_type, sixteen, capacity_slot)
	b.block_instr1(.jmp, rebuild, b.void_type, ValueID(capacity_loop))
	candidate := b.block_instr1(.load, capacity_loop, b.i64_type, capacity_slot)
	fits := b.block_instr2(.ge, capacity_loop, b.i1_type, candidate, capacity_needed)
	b.block_instr3(.br, capacity_loop, b.void_type, fits, ValueID(allocate),
		ValueID(capacity_grow))
	doubled := b.block_instr2(.mul, capacity_grow, b.i64_type, candidate, two)
	b.block_instr2(.store, capacity_grow, b.void_type, doubled, capacity_slot)
	b.block_instr1(.jmp, capacity_grow, b.void_type, ValueID(capacity_loop))
	calloc_ref := b.m.add_value(.func_ref, ptr_i8, 'calloc', b.fn_ids['calloc'])
	new_slots := b.block_instr3(.call, allocate, ptr_i8, calloc_ref, candidate, eight)
	old_slots := b.block_instr1(.load, allocate, ptr_i8, slots_ptr)
	free_ref := b.m.add_value(.func_ref, b.void_type, 'free', b.fn_ids['free'])
	b.block_instr2(.call, allocate, b.void_type, free_ref, old_slots)
	b.block_instr2(.store, allocate, b.void_type, new_slots, slots_ptr)
	b.block_instr2(.store, allocate, b.void_type, candidate, cap_ptr)
	b.block_instr2(.store, allocate, b.void_type, zero, indexed_len_ptr)
	b.block_instr1(.jmp, allocate, b.void_type, ValueID(prepare))
	first := b.block_instr1(.load, prepare, b.i64_type, indexed_len_ptr)
	current_cap := b.block_instr1(.load, prepare, b.i64_type, cap_ptr)
	mask := b.block_instr2(.sub, prepare, b.i64_type, current_cap, one)
	slots_raw := b.block_instr1(.load, prepare, ptr_i8, slots_ptr)
	slots := b.block_instr1(.bitcast, prepare, ptr_i64, slots_raw)
	keys := b.block_instr1(.load, prepare, ptr_i8, keys_ptr)
	key_size := b.block_instr1(.load, prepare, b.i64_type, key_size_ptr)
	b.block_instr2(.store, prepare, b.void_type, first, i_slot)
	b.block_instr1(.jmp, prepare, b.void_type, ValueID(loop))
	i := b.block_instr1(.load, loop, b.i64_type, i_slot)
	more := b.block_instr2(.lt, loop, b.i1_type, i, len)
	b.block_instr3(.br, loop, b.void_type, more, ValueID(body), ValueID(finish))
	key_offset := b.block_instr2(.mul, body, b.i64_type, i, key_size)
	key := b.block_instr2(.add, body, ptr_i8, keys, key_offset)
	hash := b.native_map_key_hash(body, state, key)
	initial_slot := b.block_instr2(.and_, body, b.i64_type, hash, mask)
	b.block_instr2(.store, body, b.void_type, initial_slot, slot_slot)
	b.block_instr1(.jmp, body, b.void_type, ValueID(probe))
	slot := b.block_instr1(.load, probe, b.i64_type, slot_slot)
	slot_offset := b.block_instr2(.mul, probe, b.i64_type, slot, eight)
	slot_ptr := b.block_instr2(.add, probe, ptr_i64, slots, slot_offset)
	position := b.block_instr1(.load, probe, b.i64_type, slot_ptr)
	empty := b.block_instr2(.eq, probe, b.i1_type, position, zero)
	b.block_instr3(.br, probe, b.void_type, empty, ValueID(store), ValueID(probe_next))
	advanced := b.block_instr2(.add, probe_next, b.i64_type, slot, one)
	next_slot := b.block_instr2(.and_, probe_next, b.i64_type, advanced, mask)
	b.block_instr2(.store, probe_next, b.void_type, next_slot, slot_slot)
	b.block_instr1(.jmp, probe_next, b.void_type, ValueID(probe))
	encoded_position := b.block_instr2(.add, store, b.i64_type, i, one)
	b.block_instr2(.store, store, b.void_type, encoded_position, slot_ptr)
	b.block_instr2(.store, store, b.void_type, encoded_position, i_slot)
	b.block_instr1(.jmp, store, b.void_type, ValueID(loop))
	b.block_instr2(.store, finish, b.void_type, len, indexed_len_ptr)
	b.block_instr0(.ret, finish, b.void_type)
}

fn (mut b Builder) generate_native_map_find_body(func_id int) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	ptr_i64 := b.m.type_store.get_ptr(b.i64_type)
	ptr_map := b.m.type_store.get_ptr(b.map_type)
	entry := b.m.add_block(func_id, 'map_find_entry')
	map_ptr := b.func_add_argument(func_id, ptr_map, 'map')
	key := b.func_add_argument(func_id, ptr_i8, 'key')
	slot_slot := b.block_instr0(.alloca, entry, ptr_i64)
	zero := b.m.get_or_add_const(b.i64_type, '0')
	one := b.m.get_or_add_const(b.i64_type, '1')
	eight := b.m.get_or_add_const(b.i64_type, '8')
	nil_map := b.m.get_or_add_const(ptr_map, '0')
	has_map := b.block_instr2(.ne, entry, b.i1_type, map_ptr, nil_map)
	check_state := b.m.add_block(func_id, 'map_find_state')
	check_len := b.m.add_block(func_id, 'map_find_len')
	prepare := b.m.add_block(func_id, 'map_find_prepare')
	probe := b.m.add_block(func_id, 'map_find_probe')
	compare := b.m.add_block(func_id, 'map_find_compare')
	string_compare := b.m.add_block(func_id, 'map_find_string')
	bytes_compare := b.m.add_block(func_id, 'map_find_bytes')
	next := b.m.add_block(func_id, 'map_find_next')
	found := b.m.add_block(func_id, 'map_find_found')
	missing := b.m.add_block(func_id, 'map_find_missing')
	b.block_instr3(.br, entry, b.void_type, has_map, ValueID(check_state), ValueID(missing))
	state := b.map_state_ptr(check_state, map_ptr)
	nil_state := b.m.get_or_add_const(b.m.type_store.get_ptr(b.map_state_type), '0')
	has_state := b.block_instr2(.ne, check_state, b.i1_type, state, nil_state)
	b.block_instr3(.br, check_state, b.void_type, has_state, ValueID(check_len),
		ValueID(missing))
	len_ptr := b.map_state_field_ptr(check_len, state, 3)
	len := b.block_instr1(.load, check_len, b.i64_type, len_ptr)
	has_entries := b.block_instr2(.gt, check_len, b.i1_type, len, zero)
	b.block_instr3(.br, check_len, b.void_type, has_entries, ValueID(prepare), ValueID(missing))
	index_ref := b.m.add_value(.func_ref, b.void_type, 'v3_native_map_index',
		b.fn_ids['v3_native_map_index'])
	b.block_instr2(.call, prepare, b.void_type, index_ref, state)
	keys_ptr := b.map_state_field_ptr(prepare, state, 0)
	key_size_ptr := b.map_state_field_ptr(prepare, state, 4)
	slots_ptr := b.map_state_field_ptr(prepare, state, 6)
	cap_ptr := b.map_state_field_ptr(prepare, state, 7)
	keys := b.block_instr1(.load, prepare, ptr_i8, keys_ptr)
	key_size := b.block_instr1(.load, prepare, b.i64_type, key_size_ptr)
	slots_raw := b.block_instr1(.load, prepare, ptr_i8, slots_ptr)
	slots := b.block_instr1(.bitcast, prepare, ptr_i64, slots_raw)
	cap := b.block_instr1(.load, prepare, b.i64_type, cap_ptr)
	mask := b.block_instr2(.sub, prepare, b.i64_type, cap, one)
	hash := b.native_map_key_hash(prepare, state, key)
	initial_slot := b.block_instr2(.and_, prepare, b.i64_type, hash, mask)
	b.block_instr2(.store, prepare, b.void_type, initial_slot, slot_slot)
	b.block_instr1(.jmp, prepare, b.void_type, ValueID(probe))
	slot := b.block_instr1(.load, probe, b.i64_type, slot_slot)
	slot_offset := b.block_instr2(.mul, probe, b.i64_type, slot, eight)
	slot_ptr := b.block_instr2(.add, probe, ptr_i64, slots, slot_offset)
	encoded_position := b.block_instr1(.load, probe, b.i64_type, slot_ptr)
	occupied := b.block_instr2(.ne, probe, b.i1_type, encoded_position, zero)
	b.block_instr3(.br, probe, b.void_type, occupied, ValueID(compare), ValueID(missing))
	position := b.block_instr2(.sub, compare, b.i64_type, encoded_position, one)
	key_offset := b.block_instr2(.mul, compare, b.i64_type, position, key_size)
	stored_key := b.block_instr2(.add, compare, ptr_i8, keys, key_offset)
	string_size := b.m.get_or_add_const(b.i64_type, '16')
	is_string := b.block_instr2(.eq, compare, b.i1_type, key_size, string_size)
	b.block_instr3(.br, compare, b.void_type, is_string, ValueID(string_compare),
		ValueID(bytes_compare))
	ptr_string := b.m.type_store.get_ptr(b.str_type)
	stored_string_ptr := b.block_instr1(.bitcast, string_compare, ptr_string, stored_key)
	key_string_ptr := b.block_instr1(.bitcast, string_compare, ptr_string, key)
	stored_string := b.block_instr1(.load, string_compare, b.str_type, stored_string_ptr)
	key_string := b.block_instr1(.load, string_compare, b.str_type, key_string_ptr)
	eq_ref := b.m.add_value(.func_ref, b.i1_type, 'fast_string_eq', b.fn_ids['fast_string_eq'])
	equal_string := b.block_instr3(.call, string_compare, b.i1_type, eq_ref, stored_string,
		key_string)
	b.block_instr3(.br, string_compare, b.void_type, equal_string, ValueID(found), ValueID(next))
	memcmp_ref := b.m.add_value(.func_ref, b.i64_type, 'memcmp', b.fn_ids['memcmp'])
	comparison := b.block_instr4(.call, bytes_compare, b.i64_type, memcmp_ref, stored_key, key,
		key_size)
	equal_bytes := b.block_instr2(.eq, bytes_compare, b.i1_type, comparison, zero)
	b.block_instr3(.br, bytes_compare, b.void_type, equal_bytes, ValueID(found), ValueID(next))
	advanced := b.block_instr2(.add, next, b.i64_type, slot, one)
	next_slot := b.block_instr2(.and_, next, b.i64_type, advanced, mask)
	b.block_instr2(.store, next, b.void_type, next_slot, slot_slot)
	b.block_instr1(.jmp, next, b.void_type, ValueID(probe))
	b.block_instr1(.ret, found, b.void_type, position)
	not_found := b.m.get_or_add_const(b.i64_type, '-1')
	b.block_instr1(.ret, missing, b.void_type, not_found)
}
