module ssa

// generate_native_float_string_body finds the shortest decimal that round trips
// to the input, then expands scientific notation for strconv's decimal helpers.
fn (mut b Builder) generate_native_float_string_body(func_id int, value_type TypeID) {
	ptr_i8 := b.m.type_store.get_ptr(b.i8_type)
	entry := b.m.add_block(func_id, 'float_string_entry')
	value := b.func_add_argument(func_id, value_type, 'value')
	x := if value_type == b.f32_type {
		b.block_instr1(.bitcast, entry, b.f64_type, value)
	} else {
		value
	}
	s_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.str_type))
	p_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.i32_type))
	i_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.i64_type))
	dot_slot := b.block_instr0(.alloca, entry, b.m.type_store.get_ptr(b.i1_type))
	one32 := b.m.get_or_add_const(b.i32_type, '1')
	zero32 := b.m.get_or_add_const(b.i32_type, '0')
	zero := b.m.get_or_add_const(b.i64_type, '0')
	one := b.m.get_or_add_const(b.i64_type, '1')
	limit := b.m.get_or_add_const(b.i32_type, if value_type == b.f32_type { '9' } else { '17' })
	b.block_instr2(.store, entry, b.void_type, one32, p_slot)
	format := b.m.add_block(func_id, 'float_string_format')
	next_precision := b.m.add_block(func_id, 'float_string_next_precision')
	prepare := b.m.add_block(func_id, 'float_string_prepare')
	scan := b.m.add_block(func_id, 'float_string_scan')
	read := b.m.add_block(func_id, 'float_string_read')
	dot := b.m.add_block(func_id, 'float_string_dot')
	check_exp := b.m.add_block(func_id, 'float_string_check_exp')
	expand := b.m.add_block(func_id, 'float_string_expand')
	exp_nonnegative := b.m.add_block(func_id, 'float_string_exp_nonnegative')
	exp_format := b.m.add_block(func_id, 'float_string_exp_format')
	next_byte := b.m.add_block(func_id, 'float_string_next_byte')
	finish := b.m.add_block(func_id, 'float_string_finish')
	original := b.m.add_block(func_id, 'float_string_original')
	append_dot := b.m.add_block(func_id, 'float_string_append_dot')
	b.block_instr1(.jmp, entry, b.void_type, ValueID(format))
	precision := b.block_instr1(.load, format, b.i32_type, p_slot)
	general_ref := b.m.add_value(.func_ref, b.str_type, 'v3_f64_general', b.fn_ids['v3_f64_general'])
	s := b.block_instr4(.call, format, b.str_type, general_ref, x, precision, zero32)
	b.block_instr2(.store, format, b.void_type, s, s_slot)
	data_field := b.block_struct_field_ptr(format, s_slot, b.str_type, 0)
	data := b.block_instr1(.load, format, ptr_i8, data_field)
	strtod_ref := b.m.add_value(.func_ref, b.f64_type, 'strtod', b.fn_ids['strtod'])
	nil_end := b.m.get_or_add_const(b.m.type_store.get_ptr(ptr_i8), '0')
	parsed := b.block_instr3(.call, format, b.f64_type, strtod_ref, data, nil_end)
	parsed_value := if value_type == b.f32_type {
		b.block_instr1(.bitcast, format, b.f32_type, parsed)
	} else {
		parsed
	}
	roundtrips := b.block_instr2(.eq, format, b.i1_type, parsed_value, value)
	last_precision := b.block_instr2(.ge, format, b.i1_type, precision, limit)
	finished := b.block_instr2(.or_, format, b.i1_type, roundtrips, last_precision)
	b.block_instr3(.br, format, b.void_type, finished, ValueID(prepare), ValueID(next_precision))
	free_ref := b.m.add_value(.func_ref, b.void_type, 'free', b.fn_ids['free'])
	b.block_instr2(.call, next_precision, b.void_type, free_ref, data)
	next_p := b.block_instr2(.add, next_precision, b.i32_type, precision, one32)
	b.block_instr2(.store, next_precision, b.void_type, next_p, p_slot)
	b.block_instr1(.jmp, next_precision, b.void_type, ValueID(format))
	len_field := b.block_struct_field_ptr(prepare, s_slot, b.str_type, 1)
	len32 := b.block_instr1(.load, prepare, b.i32_type, len_field)
	len := b.block_instr1(.zext, prepare, b.i64_type, len32)
	no_dot := b.m.get_or_add_const(b.i1_type, '0')
	b.block_instr2(.store, prepare, b.void_type, no_dot, dot_slot)
	b.block_instr2(.store, prepare, b.void_type, zero, i_slot)
	b.block_instr1(.jmp, prepare, b.void_type, ValueID(scan))
	i := b.block_instr1(.load, scan, b.i64_type, i_slot)
	more := b.block_instr2(.lt, scan, b.i1_type, i, len)
	b.block_instr3(.br, scan, b.void_type, more, ValueID(read), ValueID(finish))
	byte_ptr := b.block_instr2(.add, read, ptr_i8, data, i)
	byte := b.block_instr1(.load, read, b.i8_type, byte_ptr)
	dot_char := b.m.get_or_add_const(b.i8_type, '46')
	is_dot := b.block_instr2(.eq, read, b.i1_type, byte, dot_char)
	b.block_instr3(.br, read, b.void_type, is_dot, ValueID(dot), ValueID(check_exp))
	yes_dot := b.m.get_or_add_const(b.i1_type, '1')
	b.block_instr2(.store, dot, b.void_type, yes_dot, dot_slot)
	b.block_instr1(.jmp, dot, b.void_type, ValueID(next_byte))
	exp_char := b.m.get_or_add_const(b.i8_type, '101')
	is_exp := b.block_instr2(.eq, check_exp, b.i1_type, byte, exp_char)
	b.block_instr3(.br, check_exp, b.void_type, is_exp, ValueID(expand), ValueID(next_byte))
	exponent_pos := b.block_instr2(.add, expand, b.i64_type, i, one)
	exponent_ptr := b.block_instr2(.add, expand, ptr_i8, data, exponent_pos)
	atoi_ref := b.m.add_value(.func_ref, b.i32_type, 'atoi', b.fn_ids['atoi'])
	exponent := b.block_instr2(.call, expand, b.i32_type, atoi_ref, exponent_ptr)
	one_less := b.block_instr2(.sub, expand, b.i32_type, precision, one32)
	decimals := b.block_instr2(.sub, expand, b.i32_type, one_less, exponent)
	b.block_instr2(.store, expand, b.void_type, zero32, p_slot)
	positive_decimals := b.block_instr2(.gt, expand, b.i1_type, decimals, zero32)
	b.block_instr3(.br, expand, b.void_type, positive_decimals, ValueID(exp_nonnegative), ValueID(exp_format))
	b.block_instr2(.store, exp_nonnegative, b.void_type, decimals, p_slot)
	b.block_instr1(.jmp, exp_nonnegative, b.void_type, ValueID(exp_format))
	decimal_precision := b.block_instr1(.load, exp_format, b.i32_type, p_slot)
	fixed_ref := b.m.add_value(.func_ref, b.str_type, 'v3_f64_fixed', b.fn_ids['v3_f64_fixed'])
	decimal_text := b.block_instr3(.call, exp_format, b.str_type, fixed_ref, x, decimal_precision)
	b.block_instr2(.call, exp_format, b.void_type, free_ref, data)
	b.block_instr2(.store, exp_format, b.void_type, decimal_text, s_slot)
	has_decimals := b.block_instr2(.gt, exp_format, b.i1_type, decimal_precision, zero32)
	b.block_instr3(.br, exp_format, b.void_type, has_decimals, ValueID(original), ValueID(append_dot))
	new_i := b.block_instr2(.add, next_byte, b.i64_type, i, one)
	b.block_instr2(.store, next_byte, b.void_type, new_i, i_slot)
	b.block_instr1(.jmp, next_byte, b.void_type, ValueID(scan))
	has_dot := b.block_instr1(.load, finish, b.i1_type, dot_slot)
	first := b.block_instr1(.load, finish, b.i8_type, data)
	n_char := b.m.get_or_add_const(b.i8_type, '110')
	i_char := b.m.get_or_add_const(b.i8_type, '105')
	second_ptr := b.block_instr2(.add, finish, ptr_i8, data, one)
	second := b.block_instr1(.load, finish, b.i8_type, second_ptr)
	first_n := b.block_instr2(.eq, finish, b.i1_type, first, n_char)
	first_i := b.block_instr2(.eq, finish, b.i1_type, first, i_char)
	second_i := b.block_instr2(.eq, finish, b.i1_type, second, i_char)
	special_first := b.block_instr2(.or_, finish, b.i1_type, first_n, first_i)
	special := b.block_instr2(.or_, finish, b.i1_type, special_first, second_i)
	complete := b.block_instr2(.or_, finish, b.i1_type, has_dot, special)
	b.block_instr3(.br, finish, b.void_type, complete, ValueID(original), ValueID(append_dot))
	result := b.block_instr1(.load, original, b.str_type, s_slot)
	b.block_instr1(.ret, original, b.void_type, result)
	base := b.block_instr1(.load, append_dot, b.str_type, s_slot)
	suffix := b.m.add_value(.string_literal, b.str_type, '.0', 0)
	plus_ref := b.m.add_value(.func_ref, b.str_type, 'string__plus', b.fn_ids['string__plus'])
	with_dot := b.block_instr3(.call, append_dot, b.str_type, plus_ref, base, suffix)
	b.block_instr1(.ret, append_dot, b.void_type, with_dot)
}
