// Copyright (c) 2019-2024 Alexander Medvednikov. All rights reserved.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.
// Package hkdf implements the HMAC-based Extract-and-Expand Key Derivation
// Function (HKDF) as defined in RFC 5869.
//
// HKDF is a cryptographic key derivation function (KDF) with the goal of
// expanding limited input keying material into one or more cryptographically
// strong secret keys.
// Based off:   https://github.com/golang/go/tree/master/src/crypto/hkdf
module hkdf

import crypto.hmac
import crypto.sha1
import crypto.sha256
import crypto.sha512
import hash

// extract generates a pseudorandom key for use with `expand` from an input
// secret and an optional independent salt.
//
// Only use this function if you need to reuse the extracted key with multiple
// `expand` invocations and different context values. Most common scenarios,
// including the generation of multiple keys, should use `key` instead.
pub fn extract[H](h fn () H, secret []u8, salt []u8) ![]u8 {
	check_fips140_only(h, secret)!
	mut digest := h()
	// RFC 5869: if the salt is not provided, it is set to HashLen zeros
	xkey := if salt.len == 0 { []u8{len: digest.size()} } else { salt }
	$if H is hash.Hash {
		if prk := prekeyed_hmac(digest, .extract, xkey, secret, 0) {
			return prk
		}
	}
	return hmac_sum(h, xkey, secret)
}

// expand derives a key from the given hash, key, and optional context info,
// returning a []u8 of length key_length that can be used as cryptographic key.
// The extraction step is skipped.
//
// The key should have been generated by `extract`, or be a uniformly
// random or pseudorandom cryptographically strong key. See RFC 5869, Section
// 3.3. Most common scenarios will want to use `key` instead.
pub fn expand[H](h fn () H, pseudorandom_key []u8, info string, key_length int) ![]u8 {
	check_fips140_only(h, pseudorandom_key)!
	mut digest := h()
	if key_length < 0 {
		return error('hkdf: requested key length must be non-negative')
	}
	limit := digest.size() * 255
	if key_length > limit {
		return error('hkdf: requested key length too large')
	}
	info_bytes := info.bytes()
	$if H is hash.Hash {
		if out := prekeyed_hmac(digest, .expand, pseudorandom_key, info_bytes, key_length) {
			return out
		}
	}
	mut out := []u8{cap: key_length}
	mut counter := u8(0)
	mut buf := []u8{}
	for out.len < key_length {
		counter++
		if counter == 0 {
			panic('hkdf: counter overflow')
		}
		mut data := []u8{cap: buf.len + info_bytes.len + 1}
		data << buf
		data << info_bytes
		data << counter
		buf = hmac_sum(h, pseudorandom_key, data)
		remaining := key_length - out.len
		if remaining < buf.len {
			out << buf[..remaining]
		} else {
			out << buf
		}
	}
	return out
}

// key derives a key from the given hash, secret, salt and context info,
// returning a []u8 of length key_length that can be used as cryptographic key.
// Salt and info can be empty.
pub fn key[H](h fn () H, secret []u8, salt []u8, info string, key_length int) ![]u8 {
	check_fips140_only(h, secret)!
	if key_length < 0 {
		return error('hkdf: requested key length must be non-negative')
	}
	mut digest := h()
	limit := digest.size() * 255
	if key_length > limit {
		return error('hkdf: requested key length too large')
	}
	prk := extract(h, secret, salt)!
	return expand(h, prk, info, key_length)
}

fn check_fips140_only[H](_h fn () H, _key []u8) ! {
	// V does not currently have a FIPS 140-only mode.
	return
}

// Step selects which HKDF step `prekeyed_hmac` computes.
enum Step {
	extract
	expand
}

// prekeyed_hmac computes HKDF-Extract(`key`, `data`) or HKDF-Expand(`key`, `data`,
// `key_length`) with `hmac.Hmac` when `h` is a SHA-1 or SHA-2 digest, and returns
// none for any other hash, which then takes the generic path.
fn prekeyed_hmac(h hash.Hash, step Step, key []u8, data []u8, key_length int) ?[]u8 {
	match h {
		sha1.Digest {
			mut mac := hmac.new_hmac(sha1.new, key)
			return hmac_step(mut mac, step, data, key_length)
		}
		sha256.Digest {
			new_digest := if h.size() == sha256.size224 { sha256.new224 } else { sha256.new }
			mut mac := hmac.new_hmac(new_digest, key)
			return hmac_step(mut mac, step, data, key_length)
		}
		sha512.Digest {
			new_digest := match h.size() {
				sha512.size384 { sha512.new384 }
				sha512.size256 { sha512.new512_256 }
				sha512.size224 { sha512.new512_224 }
				else { sha512.new }
			}
			mut mac := hmac.new_hmac(new_digest, key)
			return hmac_step(mut mac, step, data, key_length)
		}
		else {
			return none
		}
	}
}

// hmac_step computes one HKDF step with `mac`, which is keyed with the salt for
// `.extract` and with the pseudorandom key for `.expand`. `hmac.Hmac` processes
// the key once, so the expand loop does not allocate.
fn hmac_step[D](mut mac hmac.Hmac[D], step Step, data []u8, key_length int) []u8 {
	hash_length := mac.size()
	if step == .extract {
		// PRK = HMAC(salt, IKM)
		mut prk := []u8{len: hash_length}
		mac.write(data) or { panic(err) }
		mac.sum_into(mut prk)
		return prk
	}
	mut out := []u8{len: key_length}
	mut t := []u8{len: hash_length}
	mut counter := []u8{len: 1}
	for offset := 0; offset < key_length; offset += hash_length {
		// T(i) = HMAC(PRK, T(i-1) || info || i), where T(0) is empty
		counter[0]++
		if offset > 0 {
			mac.write(t) or { panic(err) }
		}
		mac.write(data) or { panic(err) }
		mac.write(counter) or { panic(err) }
		mac.sum_into(mut t)
		copy(mut out[offset..], t)
	}
	return out
}

fn hmac_sum[H](h fn () H, key []u8, data []u8) []u8 {
	mut digest := h()
	block_size := digest.block_size()
	mut b_key := if key.len <= block_size { key.clone() } else { hash_sum(h, key) }
	if b_key.len > block_size {
		b_key = b_key[..block_size].clone()
	}
	mut inner := []u8{len: block_size, init: 0x36}
	mut outer := []u8{len: block_size, init: 0x5c}
	for i, b in b_key {
		inner[i] = b ^ 0x36
		outer[i] = b ^ 0x5c
	}
	inner << data
	inner_hash := hash_sum(h, inner)
	outer << inner_hash
	return hash_sum(h, outer)
}

fn hash_sum[H](h fn () H, data []u8) []u8 {
	mut digest := h()
	digest.write(data) or { panic(err) }
	return digest.sum([]u8{})
}
