#!/bin/bash

set -e 

if (( $# != 2 )); then
    echo "Usage: compare_v_to_c_performance COMMIT_BEFORE COMMIT_AFTER"
    exit
fi

######################################################################
## NB: This tool depends that you have the following cli instruments:
##
##     bash
##     git
##     cp
##     stat
##     strip
##     upx
##     make
##     hyperfine
##     cc -> working, recent, sane C99 compiler (both gcc/clang work)
##
## If you are a C/V developer in a unix environment, you most probably 
## already have the above installed, with the possible exception of:
## https://github.com/sharkdp/hyperfine
##
## Installing them is out of scope of this tool.
######################################################################

COMMIT_B=$1
COMMIT_A=$2

CWD=$(pwd)
WORKDIR=/tmp

B=$WORKDIR/v_at_$COMMIT_B
A=$WORKDIR/v_at_$COMMIT_A

function prepare_v() {
  echo 
  echo "Cloning current v source to $1 ..."
  git clone --quiet $CWD $1
  
  cd $1
  git checkout --quiet $2
  
  echo "Making v and vprod compilers in $1"
  make > /dev/null
  ./v -o v compiler 
  ./v -prod -o vprod compiler
  cp v     v_stripped 
  cp vprod vprod_stripped 
  strip *_stripped
  cp v_stripped      v_stripped_upxed
  cp vprod_stripped  vprod_stripped_upxed
  upx -qqq --lzma v_stripped_upxed 
  upx -qqq --lzma vprod_stripped_upxed
  stat -c "%10s %n" $1/v       $1/v_stripped          $1/v_stripped_upxed
  stat -c "%10s %n" $1/vprod   $1/vprod_stripped      $1/vprod_stripped_upxed
  echo "v version is: $($1/v --version) , local source commit: $(git rev-parse --short  --verify HEAD)"
}

function compare_v_performance() {
  CMD=$1
  echo "---------------------------------------------------------------------------------"
  echo "Compare '$CMD'"
  hyperfine --warmup=3 "cd $B/; time $CMD " \
                       "cd $A/; time $CMD "
  echo
}

##############################################################################
# Cleanup artifacts from previous runs of this tool:
cd $WORKDIR
rm -rf $A/ $B/
##############################################################################

echo "Comparing v compiler performance of commit $COMMIT_B (before) vs commit $COMMIT_A (after) ..."
##echo "WORKDIR: $WORKDIR | BEFORE: $B | AFTER: A: $A"
prepare_v "$B" "$COMMIT_B"
prepare_v "$A" "$COMMIT_A"

cd $WORKDIR
compare_v_performance "./v     -o x.c compiler"
compare_v_performance "./vprod -o x.c compiler"
compare_v_performance "./vprod -o x   compiler"
