name: CI FreeBSD

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'cmd/tools/**'
      - '!**/freebsd_ci.yml'
      - '!**/freebsd_ci.sh'
      - '!cmd/tools/builders/**.v'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'cmd/tools/**'
      - '!**/freebsd_ci.yml'
      - '!**/freebsd_ci.sh'
      - '!cmd/tools/builders/**.v'

### See https://github.com/vmactions/freebsd-vm
### for a description of the used fields here

jobs:
  test-on-freebsd-14-x86:
    runs-on: ubuntu-latest
    name: Run a FreeBSD 14 x86 VM
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test-freebsd-14-runs-in-vm
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.0"
          ## arch: aarch64
          mem: 2048
          ## cpu: 3
          usesh: true
          copyback: false
          prepare: pkg install -y git sqlite3 bash
          run: |
            ./.github/workflows/freebsd_ci.sh

  test-on-freebsd-15-aarch64:
    runs-on: ubuntu-latest
    name: Run a FreeBSD 15 ARM VM
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test-freebsd-15-runs-in-vm
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.0"
          arch: aarch64
          mem: 2048
          usesh: true
          copyback: false
          prepare: pkg install -y git sqlite3 bash
          run: |
            ./.github/workflows/freebsd_ci.sh
