name: CI FreeBSD
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'cmd/tools/**'
      - '!**/freebsd_ci.yml'
      - '!cmd/tools/builders/**.v'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'cmd/tools/**'
      - '!**/frebsd_ci.yml'
      - '!cmd/tools/builders/**.v'

jobs:
  test-on-freebsd:
    runs-on: ubuntu-latest
    name: A simple job to test running in a FreeBSD VM
    env:
      MYTOKEN: ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          envs: 'MYTOKEN MYTOKEN2'
          usesh: true
          prepare: |
            pkg install -y curl

          run: |
            pwd
            ls -lah
            whoami
            env
            freebsd-version
            sysctl hw.model
            sysctl hw.ncpu
            sysctl hw.physmem
            sysctl hw.usermem
