name: VC gen

on:
  pull_request:
    paths-ignore:
      - '**.vv'
      - '**.out'
      - '**.yml'
      - '**.md'
      - '!**/gen_vc_ci.yml'
  push:
    paths-ignore:
      - '**.vv'
      - '**.out'
      - '**.yml'
      - '**.md'
      - '!**/gen_vc_ci.yml'

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master')}}

jobs:
  build-vc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: make -j4
      - name: Regenerate v.c and v_win.c
        run: |
          git config --global user.email "vlang-bot@users.noreply.github.com"
          git config --global user.name "vlang-bot"

          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_MSG=$(git log -1 --oneline --pretty='%s' HEAD)

          rm -rf vc
          .github/workflows/retry.sh git clone --depth=1 \
            https://vlang-bot:${{ secrets.VLANG_BOT_SECRET }}@github.com/vlang/vc.git

          rm -rf vc/v.c vc/v_win.c

          ./v -o vc/v.c -os cross cmd/v
          ./v -o vc/v_win.c -os windows -cc msvc cmd/v

          sed -i "1s/^/#define V_COMMIT_HASH \"$COMMIT_HASH\"\n/" vc/v.c
          sed -i "1s/^/#define V_COMMIT_HASH \"$COMMIT_HASH\"\n/" vc/v_win.c

          # ensure the C files are over 5000 lines long, as a safety measure
          [ $(wc -l < vc/v.c) -gt 5000 ]
          [ $(wc -l < vc/v_win.c) -gt 5000 ]

          git -C vc add v.c v_win.c
          git -C vc commit -m "[v:master] $COMMIT_HASH - $COMMIT_MSG"

          # in case there are recent commits:
          .github/workflows/retry.sh git -C vc pull --rebase origin master
          git -C vc log -3

      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'vlang/v' && github.ref == 'refs/heads/master'
        run: git -C vc push || true
