name: Code CI vlib modules

on:
  push:
    paths:
      - '**/cmd/tools/vdoc/theme/**'
  pull_request:
    paths:
      - '**/cmd/tools/vdoc/theme/**'

jobs:
  lint-module-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Formatting
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --check cmd/tools/vdoc/theme
