name: Workflow Lint

## Note: to install `prettier` locally, see https://prettier.io/docs/en/install,
## or just: `npm install --save-dev --save-exact prettier`

## If you already have `prettier` installed, to run it locally,
## just run: `npx prettier --check **.yml` .

on:
  push:
    paths:
      - '**.yml'
  pull_request:
    paths:
      - '**.yml'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify formatting
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check **.yml
